<?php
/*
    Copyright (C) 2004-2009 Kestas J. Kuliukas
	
	This file is part of webDiplomacy.

    webDiplomacy is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    webDiplomacy is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with webDiplomacy.  If not, see <http://www.gnu.org/licenses/>.
 */

defined('IN_CODE') or die('This script can not be run by itself.');
/**
 * @package Base
 * @subpackage Static
 */
print libHTML::pageTitle('Nutzungsbedingungen','Die Bedingungen, zu denen der Service auf Diplomacy\'s Website genutzt werden darf.');
?>

<p>Durch die Benutzung der Webseite &quot;Diplomacy's Website.de&quot; und ihrer Inhalte, die mit dem Abschluss der Registrierung beginnt, akzeptiert der Nutzer die nachfolgenden Nutzungsbedingungen. Als Nutzer im Sinne dieser Nutzungsbedinungen gelten die Besucher von Diplomacy's Website, die sich mit ihrer Email-Adresse einen Account registrieren / registriert haben.</p><p>Betreiber der Webseite diplomacy.s-website.de ist Stefan Behrendt (ichtyst.de) (nachfolgend "ichTyst" oder "Der Anbieter" genannt). ichTyst bietet mit Diplomacy's Website eine für den Nutzer kostenfreie Möglichkeit, das Runden-basierte Strategie-Spiel „Diplomacy“ online mit anderen Spielern zu spielen.</p>
<p>§ 1 Änderungen der Nutzungsbedingungen <br/>ichTyst ist berechtigt, die hier aufgeführten Nutzungsbedingungen jederzeit anzupassen. Da jeder Nutzer selbst dafür verantwortlich ist, die Nutzungsbedingungen auf eventuelle Änderungen hin zu prüfen, möchten wir Sie bitten, dies in regelmäßigen Abständen zu tun. Die weitere Nutzung der Webseite bei geänderten Nutzungsbedingungen ist gleichbedeutend mit der Akzeptierung dieser Bedingungen. Die aktuellen Nutzungsbedinungen sind immer auf diplomacy.s-website.de über die Hilfe im Hauptmenü oder Link im Footer einzusehen. </p><p><span/></p>
<p>§ 2 Änderungen an der Webseite und ihren Inhalten<br/>a) ichTyst ist jederzeit berechtigt, Änderungen an der Webseite, bzw. an den Inhalten der Webseite ohne vorherige Ankündigung durchzuführen. Durch die weitere Nutzung der Webseite erkennt der Nutzer diese Änderungen an. Solche Änderungen werden aber niemals in irgendeiner Weise die Familien- und Kinderfreundlichkeit des Portals beeinträchtigen, sondern lediglich der leichteren Bedienung und Übersichtlichkeit von Diplomacy's Website dienen. </p><p>b) ichTyst bemüht sich stets um Vollständigkeit, Aktualität und Funktionstüchtigkeit seines Online-Angebotes, ist dazu aber nicht verpflichtet.</p><p>c) ichTyst haftet nicht für eine eventuell ausbleibende Verfügbarkeit des Online-Angebotes. Trotzdem sind wir stets bemüht, immer für unsere Nutzer verfügbar zu sein. </p><p><span/></p>
<p>§ 3 Urheberrecht<br/>ichTyst bietet auf diplomacy.s-website.de das Runden-basierte Strategie-Spiel „Diplomacy“ an. Die zugrunde liegende Software ist webDiplomacy, ein Open Source Projekt, veröffentlicht unter der GNU Affero General Public License. Die genauen Lizenzbestimmungen sind <a href="/AGPL.txt">hier</a> im Original nachzulesen.</p><p>Um den Bestimmungen der  GNU Affero General Public License nachzukommen ist der von Diplomacy's Website genutzte und für diese Nutzung modifizierte Code von webDiplomacy ständig über diesen Link verfügbar: <a class="light" href="http://diplomacy.s-website.de/dipl1.04.dw.2.0b.tar.bz2">http://diplomacy.s-website.de/dipl1.04.dw.2.0b.tar.bz2</a></p><p><span/></p>
<p>§ 4 Kosten<br/>a) Das gesamte Online-Angebot von Diplomacy's Website ist kostenfrei. </p><p>b) Je nach genutzter Internetverbindung oder gewähltem Internettarif (z.B. zeit- oder volumenbasiert) entstehen Ihnen durch eine Verbindung zum Internet Kosten (Informationen dazu erhalten Sie von ihrem Internetanbieter). Wir möchten insbesondere Eltern darum bitten, ihre Kinder über solche Kosten aufzuklären.</p>
<a name="datenschutz"></a><p>§ 5 Datenschutz<br/>Der Schutz von persönlichen Daten ist für Diplomacy's Website sehr wichtig. Daher werden, abgesehen von der IP-Adresse, erst gar keine Personen-bezogene Daten erhoben. Der Nutzer von Diplomacy's Website erklärt sich damit einverstanden, dass die IP-Adresse zum Aufspüren von s.g. Multi-Accunts gespeichert und genutzt werden darf. Für die Registrierung wird lediglich eine Email-Adresse benötigt. Diese wird von Diplomacy's Website nicht an dritte weitergegeben und auf Wunsch des Nutzers in dessen Profil auch vor anderen Nutzern versteckt.</p><p>IchTyst behält sich allerdings das Recht vor, relevante Informationen über das Angebot von Diplomacy's Website per Email an die Nutzer zu senden.</p><p>Die Privatsphäre der Nutzer von Diplomacy's Website ist bei den eingebundenen "SozialPlugins" (wie dem Facebook-Like-Button auf der Homepage) ist durch das vom heise-Verlag entwickelten 2-Klick-System geschützt. Erst wenn der Nutzer den Button durch einen ersten Klick aktiviert werden die "SocialPlugins" im Browser des Nutzers geladen, so dass vor diesem ersten Klick keinerlei Daten an die SocialNetworks Facebook, Twitter oder Google+ gesendet werden. Weitere Information zum 2-Klick-Verfahren gibt es direkt auf der <a href="http://www.heise.de/ct/artikel/2-Klicks-fuer-mehr-Datenschutz-1333879.html" class="light">Projekt-Seite des Heise-Verlags</a>.</p><p><span/></p>
<p>§ 6 Registrierung<br/>a) Die Registrierung auf diplomacy.s-website.de ist freiwillig, kostenlos und völlig unverbindlich.</p><p>b) Der Verstoß eines registrierten Nutzers gegen die Spielregeln von Diplomacy oder die in den FAQ beschriebenen besonderen Regeln für das Spielen der „Online-Variante“ kann ohne vorausgehende Ankündigung zum sofortigen Ausschluss vom Angebot von Diplomacy's Website führen.</p><p><span/></p>
<p>§ 7 Nutzung der Kommunikationsfunktionen<br/>a) Die Nutzung der Kommunikationsfunktionen auf Diplomacy's Website ist ausschließlich zu privaten Zwecken erlaubt.</p><p>b) Das Verschicken von Massenmails (Spam) ist ausdrücklich verboten. Ebenso untersagt ist jegliche Art der Belästigung anderer Nutzer durch eine der angebotenen Kommunikationsmöglichkeiten.</p><p>Belästigung liegt insbesondere vor, wenn:</p><p>- rechtswidrige, bedrohliche, beleidigende, irreführende oder betrügerische Äußerungen getätigt werden</p><p>- Personen auf Grund ihrer Herkunft, Religion, ihres Geschlechts, Alters oder sonstiger Merkmale und Eigenschaften schikaniert, eingeschüchtert oder diffamiert werden.</p><p>c) ichTyst hat das Recht, bei konkretem Verdacht auf Missachtung der oben genannten Regelung, die privaten Nachrichten betreffender Nutzer auf Verstöße hin zu untersuchen. </p><p><span/></p>
<p>§ 8 Haftungsbeschränkung<br/>a) Schadensersatzansprüche des Nutzers sind ausgeschlossen </p><p>b) ichTyst garantiert keine ununterbrochene Erreichbarkeit der Webseite oder ihrer Inhalte. Insbesondere bei Wartungsarbeiten, Sicherheits- oder Kapazitätsanpassungen kann es zu Störungen oder Ausfällen kommen. In diesem Falle besteht keine Haftung durch ichTyst.</p><p>c) Ebenso auszuschließen ist die Haftung von ichTyst bei Ausfällen und Störungen, die nicht durch uns zu vertreten sind oder bei höherer Gewalt.</p><p>d) Die Webseite kann Links zu Webseiten von Dritten enthalten, einschließlich Links, die als automatisierte Suchergebnisse angeboten werden. Der Inhalt einiger dieser Webseiten kann zu beanstanden, rechtswidrig oder unrichtig sein. Diese Links bedeuten nicht, dass ichTyst die Webseiten oder Dienstleistungen dieser Dritten unterstützt. Der Nutzer erkennt an und erklärt sich damit einverstanden, dass ichTyst nicht für den Inhalt oder sonstige Materialien auf diesen Webseiten von Dritten verantwortlich ist oder haftet. Alle Geschäfte, die der Nutzer mit Inserenten auf der Webseite tätigt, gelten zwischen dem Nutzer und diesen Inserenten, und der Nutzer erkennt an und erklärt sich damit einverstanden, dass ichTyst nicht für Schäden oder Ansprüche haftet, die der Nutzer gegenüber einem Inserenten geltend machen kann.</p><p><span/></p>
<p>§ 9 Schlussbestimmungen <br/>a) Es gilt das Recht der Bundesrepublik Deutschland. </p><p>b) ichTyst gewährleistet nicht, dass die Inhalte der Webseite für die Benutzung an Orten außerhalb der Bundesrepublik Deutschland geeignet oder verfügbar sind; es ist nicht erlaubt, die Webseite von Gebieten aus zu besuchen, in denen deren Inhalte gesetzlich verboten sind. Wenn der Nutzer die Webseite von einem Standort außerhalb der Bundesrepublik Deutschland aus besucht, geschieht dies aus eigenem Antrieb und er ist für die Einhaltung der örtlichen Rechtsvorschriften verantwortlich.</p><p>c) Sollten Bestimmungen dieser Allgemeinen Geschäftsbedingungen unwirksam sein oder werden, so berührt dies die Wirksamkeit der übrigen Bestimmungen nicht.<br/><br/>
ichTyst<br/>Stefan Behrendt<br/>Gracht 201b<br/>45472 Mühleim / Deutschland<br/><br/>Tel: +49 (0)208 / 43798007<br/>E-Mail: info@diplomacy.s-website.de<br/><br/><br/>Diese Nutzungsbedingungen gelten für das gesamte Angebot ichTysts auf diplomacy.s-website.de und für alle Nutzer, die sich ab dem 30. Januar 2010 unter Zustimmung zu diesen Benutzungsbedingungen erfolgreich registriert haben oder, wenn sie sich bereits zu einem früheren Zeitpunkt registriert haben, ab dem Zeitpunkt, zu dem diesen Benutzungsbedingungen zugestimmt wurde.</p><p><br/></p>
