<?php
// This is file installs the map data for the Africa variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Nord-Atlantik', 'Sea', 'No', 0, 35, 73, 12, 44),
	array('westliches Mittelmeer', 'Sea', 'No', 0, 422, 20, 187, 10),
	array('zentrales Mittelmeer', 'Sea', 'No', 0, 666, 64, 349, 11),
	array('&Auml;g&auml;isches Meer', 'Sea', 'No', 0, 873, 42, 423, 10),
	array('&Ouml;stliches Mittelmeer', 'Sea', 'No', 0, 1037, 84, 491, 41),
	array('Sueskanal', 'Sea', 'No', 0, 1040, 134, 485, 59),
	array('Rotes Meer', 'Sea', 'No', 0, 1172, 393, 533, 148),
	array('Golf von Aden', 'Sea', 'No', 0, 1453, 458, 639, 227),
	array('Nord-Indischer Ozean', 'Sea', 'No', 0, 1327, 761, 674, 285),
	array('Mittel-Atlantik', 'Sea', 'No', 0, 30, 618, 36, 236),
	array('Romanchegraben', 'Sea', 'No', 0, 150, 654, 75, 297),
	array('Golf von Guinea', 'Sea', 'No', 0, 400, 803, 145, 346),
	array('Bucht von Benin', 'Sea', 'No', 0, 473, 688, 218, 320),
	array('S&uuml;dwest-Atlantik', 'Sea', 'No', 0, 160, 1139, 54, 536),
	array('S&uuml;dost-Atlantik', 'Sea', 'No', 0, 567, 1267, 251, 578),
	array('Kap der Guten Hoffnung', 'Sea', 'No', 0, 738, 1393, 380, 675),
	array('S&uuml;d-Indischer Ozean', 'Sea', 'No', 0, 1198, 1325, 556, 636),
	array('Stra&szlig;e von Mosambik', 'Sea', 'No', 0, 1143, 1161, 532, 536),
	array('Maskarenen Plateau', 'Sea', 'No', 0, 1402, 1041, 631, 552),
	array('Victoriasee', 'Sea', 'No', 0, 1065, 756, 495, 353),
	array('Stra&szlig;e von Gibraltar', 'Sea', 'No', 0, 303, 23, 140, 8),
	array('Sinai', 'Coast', 'No', 2, 1056, 164, 492, 72),
	array('Kairo', 'Coast', 'Yes', 2, 1025, 225, 474, 77),
	array('Alexandria', 'Coast', 'Yes', 2, 928, 157, 440, 71),
	array('Luxor', 'Coast', 'Yes', 2, 1005, 304, 467, 123),
	array('Bengasi', 'Coast', 'Yes', 0, 881, 157, 392, 59),
	array('Syrte', 'Coast', 'No', 0, 737, 156, 346, 72),
	array('Fessan', 'Land', 'No', 0, 751, 260, 346, 110),
	array('Tripolis', 'Coast', 'Yes', 9, 706, 142, 322, 62),
	array('Nord-Tschad', 'Land', 'Yes', 0, 845, 383, 360, 160),
	array('N\\\'Djamena', 'Land', 'No', 0, 728, 464, 356, 231),
	array('Tamanrasset', 'Land', 'Yes', 0, 550, 232, 254, 103),
	array('Adrar', 'Land', 'Yes', 0, 376, 245, 172, 116),
	array('West-Algerien', 'Land', 'No', 0, 425, 142, 204, 51),
	array('Darfur', 'Land', 'No', 0, 918, 392, 427, 176),
	array('Azawad', 'Land', 'No', 0, 352, 313, 169, 145),
	array('West-Sahara', 'Coast', 'No', 0, 184, 264, 78, 133),
	array('Nord-Mauretanien', 'Coast', 'Yes', 0, 154, 356, 71, 166),
	array('Nuakschott', 'Coast', 'No', 0, 203, 420, 72, 183),
	array('Casablanca', 'Coast', 'Yes', 6, 319, 62, 127, 42),
	array('Ost-Marokko', 'Coast', 'Yes', 6, 389, 65, 181, 27),
	array('Marrakesch', 'Coast', 'Yes', 6, 246, 195, 113, 87),
	array('Timbuktu', 'Coast', 'Yes', 9, 342, 375, 169, 192),
	array('Agadez', 'Land', 'Yes', 0, 578, 380, 296, 158),
	array('Zentralafrikanische Republik', 'Land', 'No', 0, 757, 641, 349, 294),
	array('Orientale', 'Coast', 'No', 1, 882, 712, 428, 339),
	array('S&uuml;d-Niger', 'Land', 'No', 0, 545, 445, 252, 196),
	array('Algier', 'Coast', 'Yes', 0, 564, 28, 233, 11),
	array('Tunesien', 'Coast', 'Yes', 9, 610, 50, 282, 17),
	array('Ascension', 'Sea', 'No', 0, 211, 894, 96, 411),
	array('Kano', 'Land', 'Yes', 7, 652, 535, 306, 249),
	array('Nordwest-Nigeria', 'Coast', 'No', 7, 539, 498, 248, 233),
	array('Gao', 'Coast', 'Yes', 9, 402, 426, 210, 193),
	array('Burkina Faso', 'Land', 'No', 0, 359, 532, 166, 247),
	array('Kamerun', 'Coast', 'Yes', 0, 617, 658, 288, 302),
	array('&Auml;quatorialguinea', 'Coast', 'No', 0, 623, 707, 291, 328),
	array('Gabun', 'Coast', 'No', 0, 628, 768, 292, 358),
	array('Luanda', 'Coast', 'Yes', 0, 686, 899, 327, 439),
	array('Juba', 'Coast', 'Yes', 0, 1011, 620, 468, 276),
	array('Abuja', 'Coast', 'Yes', 7, 571, 587, 265, 270),
	array('&Ouml;stlicher S&uuml;d-Sudan', 'Coast', 'No', 0, 1043, 574, 484, 263),
	array('Omdurman', 'Coast', 'Yes', 0, 1025, 432, 487, 182),
	array('Eritrea', 'Coast', 'No', 0, 1149, 429, 545, 208),
	array('Amhara', 'Coast', 'Yes', 3, 1144, 495, 547, 252),
	array('Dschibuti', 'Coast', 'No', 0, 1229, 534, 569, 244),
	array('Somaliland', 'Coast', 'No', 0, 1328, 549, 618, 254),
	array('Mogadischu', 'Coast', 'Yes', 9, 1298, 672, 601, 313),
	array('Nairobi', 'Coast', 'Yes', 0, 1117, 711, 518, 346),
	array('Mombasa', 'Coast', 'No', 0, 1181, 767, 553, 350),
	array('S&uuml;d-Somalia', 'Coast', 'No', 0, 1220, 726, 584, 310),
	array('Uganda', 'Coast', 'Yes', 0, 1062, 703, 475, 339),
	array('Kivu', 'Land', 'Yes', 9, 972, 819, 448, 358),
	array('Lagos', 'Coast', 'Yes', 7, 543, 619, 252, 290),
	array('Liberia', 'Coast', 'No', 0, 262, 632, 121, 291),
	array('Guinea', 'Coast', 'No', 0, 182, 550, 85, 254),
	array('Guinea-Bissau', 'Coast', 'No', 0, 155, 520, 73, 239),
	array('Dakar', 'Coast', 'Yes', 0, 179, 457, 71, 201),
	array('Gambia', 'Coast', 'No', 0, 133, 485, 66, 224),
	array('S&uuml;d-Senegal', 'Coast', 'No', 0, 193, 482, 91, 224),
	array('Kayes', 'Coast', 'Yes', 5, 245, 487, 116, 211),
	array('Ghana', 'Coast', 'Yes', 0, 396, 636, 185, 295),
	array('Elfenbeink&uuml;ste', 'Coast', 'Yes', 0, 316, 629, 152, 292),
	array('Sierra Leone', 'Coast', 'Yes', 0, 210, 591, 97, 274),
	array('Niamey', 'Coast', 'Yes', 0, 502, 465, 235, 218),
	array('Ruanda', 'Land', 'Yes', 0, 998, 767, 470, 356),
	array('West-Tanganjika', 'Coast', 'No', 0, 1064, 809, 510, 364),
	array('Daressalaam', 'Coast', 'Yes', 0, 1127, 872, 528, 384),
	array('Kasai', 'Coast', 'No', 1, 892, 810, 414, 369),
	array('Burundi', 'Land', 'No', 0, 997, 797, 466, 370),
	array('Lubumbashi', 'Coast', 'Yes', 1, 921, 917, 430, 416),
	array('Dire Dawa', 'Coast', 'Yes', 3, 1263, 613, 569, 297),
	array('Port Harcourt', 'Coast', 'No', 7, 581, 634, 271, 291),
	array('Ost-Sambia', 'Land', 'No', 0, 1000, 926, 473, 458),
	array('Lusaka', 'Land', 'No', 0, 871, 1024, 407, 466),
	array('Sikasso', 'Land', 'Yes', 5, 333, 501, 135, 250),
	array('Cabinda', 'Coast', 'No', 0, 655, 827, 306, 380),
	array('S&uuml;d-Angola', 'Coast', 'Yes', 0, 669, 1044, 319, 467),
	array('Namibia', 'Coast', 'Yes', 0, 689, 1117, 319, 507),
	array('Botswana', 'Land', 'No', 0, 875, 1134, 417, 550),
	array('Lesotho', 'Land', 'No', 0, 965, 1313, 449, 608),
	array('Swasiland', 'Coast', 'No', 0, 1025, 1234, 477, 574),
	array('Kinshasa', 'Coast', 'Yes', 1, 689, 834, 321, 387),
	array('Sansibar', 'Sea', 'No', 0, 1200, 822, 558, 396),
	array('Malawi', 'Land', 'Yes', 0, 1091, 1033, 498, 456),
	array('Mosambik', 'Coast', 'Yes', 0, 1136, 1046, 496, 544),
	array('Antananarivo', 'Coast', 'Yes', 4, 1336, 1045, 624, 489),
	array('Simbabwe', 'Land', 'Yes', 9, 997, 1117, 458, 500),
	array('Johannesburg', 'Land', 'Yes', 8, 973, 1213, 462, 566),
	array('Oranje-Freistaat', 'Land', 'No', 8, 955, 1282, 421, 615),
	array('Port Elizabeth', 'Coast', 'No', 8, 949, 1356, 417, 640),
	array('S&uuml;d-Madagaskar', 'Coast', 'No', 4, 1306, 1137, 597, 522),
	array('Kapstadt', 'Coast', 'Yes', 8, 849, 1383, 373, 651),
	array('Nordkap', 'Coast', 'No', 8, 771, 1316, 359, 608),
	array('Durban', 'Coast', 'Yes', 8, 1006, 1268, 473, 587),
	array('Southern Nations, Nationalities & People\\\'s Region', 'Land', 'No', 3, 1138, 611, 521, 294),
	array('Mopti & S&eacute;gou', 'Coast', 'No', 5, 357, 470, 168, 214),
	array('&Eacute;quateur', 'Coast', 'Yes', 1, 813, 687, 376, 319),
	array('Kap Verde', 'Sea', 'No', 0, 18, 396, 9, 187),
	array('Hurghada', 'Coast', 'No', 2, 1057, 278, 490, 116),
	array('Hurghada (East Coast)', 'Coast', 'No', 2, 1060, 245, 491, 107),
	array('Hurghada (West Coast)', 'Coast', 'No', 2, 1043, 284, 483, 142),
	array('Kanarische Inseln', 'Coast', 'Yes', 0, 144, 200, 66, 92),
	array('Seychellen', 'Coast', 'Yes', 0, 1428, 835, 664, 388),
	array('Komoren', 'Coast', 'Yes', 4, 1280, 978, 595, 454),
	array('Mauritius', 'Coast', 'Yes', 4, 1494, 1121, 696, 521),
	array('St Helena', 'Coast', 'Yes', 0, 342, 1049, 158, 487),
	array('Bamako', 'Coast', 'Yes', 5, 298, 509, 142, 218),
	array('Bamako (West Coast)', 'Coast', 'No', 5, 291, 448, 138, 212),
	array('Bamako (East Coast)', 'Coast', 'No', 5, 314, 467, 145, 224),
	array('R&eacute;union', 'Coast', 'Yes', 0, 1461, 1132, 680, 526),
	array('Tristan da Cunha', 'Coast', 'Yes', 0, 79, 1401, 36, 652),
	array('Togo & Benin', 'Coast', 'No', 0, 461, 576, 218, 261),
	array('Togo & Benin (North Coast)', 'Coast', 'No', 0, 494, 514, 231, 241),
	array('Togo & Benin (South Coast)', 'Coast', 'No', 0, 482, 610, 219, 284),
	array('S&atilde;o Tom&eacute; und Pr&iacute;ncipe', 'Coast', 'Yes', 0, 556, 722, 258, 336),
	array('Republik Kongo', 'Coast', 'Yes', 0, 746, 707, 350, 328),
	array('Republik Kongo (East Coast)', 'Coast', 'No', 0, 720, 773, 337, 358),
	array('Republik Kongo (West Coast)', 'Coast', 'No', 0, 649, 796, 302, 371),
	array('Khartum', 'Coast', 'Yes', 0, 1097, 405, 510, 192),
	array('Khartum (East Coast)', 'Coast', 'No', 0, 1103, 325, 515, 155),
	array('Khartum (West Coast)', 'Coast', 'No', 0, 1041, 480, 489, 222),
	array('Addis Abeba', 'Coast', 'Yes', 3, 1168, 587, 542, 271),
	array('Addis Abeba (East Coast)', 'Coast', 'No', 3, 1186, 603, 555, 284),
	array('Addis Abeba (North Coast)', 'Coast', 'No', 3, 1088, 544, 514, 244)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Nord-Atlantik','Mittel-Atlantik','Yes','No'),
	array('Nord-Atlantik','Stra&szlig;e von Gibraltar','Yes','No'),
	array('Nord-Atlantik','West-Sahara','Yes','No'),
	array('Nord-Atlantik','Nord-Mauretanien','Yes','No'),
	array('Nord-Atlantik','Nuakschott','Yes','No'),
	array('Nord-Atlantik','Casablanca','Yes','No'),
	array('Nord-Atlantik','Marrakesch','Yes','No'),
	array('Nord-Atlantik','Dakar','Yes','No'),
	array('Nord-Atlantik','Kap Verde','Yes','No'),
	array('Nord-Atlantik','Kanarische Inseln','Yes','No'),
	array('westliches Mittelmeer','zentrales Mittelmeer','Yes','No'),
	array('westliches Mittelmeer','Stra&szlig;e von Gibraltar','Yes','No'),
	array('westliches Mittelmeer','Ost-Marokko','Yes','No'),
	array('westliches Mittelmeer','Algier','Yes','No'),
	array('westliches Mittelmeer','Tunesien','Yes','No'),
	array('zentrales Mittelmeer','&Auml;g&auml;isches Meer','Yes','No'),
	array('zentrales Mittelmeer','&Ouml;stliches Mittelmeer','Yes','No'),
	array('zentrales Mittelmeer','Bengasi','Yes','No'),
	array('zentrales Mittelmeer','Syrte','Yes','No'),
	array('zentrales Mittelmeer','Tripolis','Yes','No'),
	array('zentrales Mittelmeer','Tunesien','Yes','No'),
	array('&Auml;g&auml;isches Meer','&Ouml;stliches Mittelmeer','Yes','No'),
	array('&Ouml;stliches Mittelmeer','Sueskanal','Yes','No'),
	array('&Ouml;stliches Mittelmeer','Kairo','Yes','No'),
	array('&Ouml;stliches Mittelmeer','Alexandria','Yes','No'),
	array('&Ouml;stliches Mittelmeer','Bengasi','Yes','No'),
	array('Sueskanal','Rotes Meer','Yes','No'),
	array('Sueskanal','Sinai','Yes','No'),
	array('Sueskanal','Kairo','Yes','No'),
	array('Sueskanal','Hurghada (East Coast)','Yes','No'),
	array('Rotes Meer','Golf von Aden','Yes','No'),
	array('Rotes Meer','Sinai','Yes','No'),
	array('Rotes Meer','Eritrea','Yes','No'),
	array('Rotes Meer','Hurghada (East Coast)','Yes','No'),
	array('Rotes Meer','Khartum (East Coast)','Yes','No'),
	array('Golf von Aden','Nord-Indischer Ozean','Yes','No'),
	array('Golf von Aden','Eritrea','Yes','No'),
	array('Golf von Aden','Dschibuti','Yes','No'),
	array('Golf von Aden','Somaliland','Yes','No'),
	array('Golf von Aden','Mogadischu','Yes','No'),
	array('Nord-Indischer Ozean','Stra&szlig;e von Mosambik','Yes','No'),
	array('Nord-Indischer Ozean','Mogadischu','Yes','No'),
	array('Nord-Indischer Ozean','S&uuml;d-Somalia','Yes','No'),
	array('Nord-Indischer Ozean','Daressalaam','Yes','No'),
	array('Nord-Indischer Ozean','Sansibar','Yes','No'),
	array('Nord-Indischer Ozean','Mosambik','Yes','No'),
	array('Nord-Indischer Ozean','Seychellen','Yes','No'),
	array('Nord-Indischer Ozean','Komoren','Yes','No'),
	array('Mittel-Atlantik','Romanchegraben','Yes','No'),
	array('Mittel-Atlantik','Guinea','Yes','No'),
	array('Mittel-Atlantik','Guinea-Bissau','Yes','No'),
	array('Mittel-Atlantik','Dakar','Yes','No'),
	array('Mittel-Atlantik','Gambia','Yes','No'),
	array('Mittel-Atlantik','S&uuml;d-Senegal','Yes','No'),
	array('Mittel-Atlantik','Sierra Leone','Yes','No'),
	array('Mittel-Atlantik','Kap Verde','Yes','No'),
	array('Romanchegraben','Golf von Guinea','Yes','No'),
	array('Romanchegraben','S&uuml;dwest-Atlantik','Yes','No'),
	array('Romanchegraben','Liberia','Yes','No'),
	array('Romanchegraben','Sierra Leone','Yes','No'),
	array('Golf von Guinea','Bucht von Benin','Yes','No'),
	array('Golf von Guinea','S&uuml;dwest-Atlantik','Yes','No'),
	array('Golf von Guinea','S&uuml;dost-Atlantik','Yes','No'),
	array('Golf von Guinea','Ascension','Yes','No'),
	array('Golf von Guinea','Gabun','Yes','No'),
	array('Golf von Guinea','Luanda','Yes','No'),
	array('Golf von Guinea','Liberia','Yes','No'),
	array('Golf von Guinea','Ghana','Yes','No'),
	array('Golf von Guinea','Elfenbeink&uuml;ste','Yes','No'),
	array('Golf von Guinea','Cabinda','Yes','No'),
	array('Golf von Guinea','Kinshasa','Yes','No'),
	array('Golf von Guinea','St Helena','Yes','No'),
	array('Golf von Guinea','S&atilde;o Tom&eacute; und Pr&iacute;ncipe','Yes','No'),
	array('Golf von Guinea','Republik Kongo (West Coast)','Yes','No'),
	array('Bucht von Benin','Lagos','Yes','No'),
	array('Bucht von Benin','Ghana','Yes','No'),
	array('Bucht von Benin','Togo & Benin (South Coast)','Yes','No'),
	array('Bucht von Benin','S&atilde;o Tom&eacute; und Pr&iacute;ncipe','Yes','No'),
	array('S&uuml;dwest-Atlantik','S&uuml;dost-Atlantik','Yes','No'),
	array('S&uuml;dwest-Atlantik','Ascension','Yes','No'),
	array('S&uuml;dwest-Atlantik','St Helena','Yes','No'),
	array('S&uuml;dwest-Atlantik','Tristan da Cunha','Yes','No'),
	array('S&uuml;dost-Atlantik','Kap der Guten Hoffnung','Yes','No'),
	array('S&uuml;dost-Atlantik','Luanda','Yes','No'),
	array('S&uuml;dost-Atlantik','S&uuml;d-Angola','Yes','No'),
	array('S&uuml;dost-Atlantik','Namibia','Yes','No'),
	array('S&uuml;dost-Atlantik','Nordkap','Yes','No'),
	array('S&uuml;dost-Atlantik','St Helena','Yes','No'),
	array('S&uuml;dost-Atlantik','Tristan da Cunha','Yes','No'),
	array('Kap der Guten Hoffnung','S&uuml;d-Indischer Ozean','Yes','No'),
	array('Kap der Guten Hoffnung','Kapstadt','Yes','No'),
	array('Kap der Guten Hoffnung','Nordkap','Yes','No'),
	array('S&uuml;d-Indischer Ozean','Stra&szlig;e von Mosambik','Yes','No'),
	array('S&uuml;d-Indischer Ozean','Maskarenen Plateau','Yes','No'),
	array('S&uuml;d-Indischer Ozean','Swasiland','Yes','No'),
	array('S&uuml;d-Indischer Ozean','Mosambik','Yes','No'),
	array('S&uuml;d-Indischer Ozean','Port Elizabeth','Yes','No'),
	array('S&uuml;d-Indischer Ozean','S&uuml;d-Madagaskar','Yes','No'),
	array('S&uuml;d-Indischer Ozean','Kapstadt','Yes','No'),
	array('S&uuml;d-Indischer Ozean','Durban','Yes','No'),
	array('S&uuml;d-Indischer Ozean','R&eacute;union','Yes','No'),
	array('Stra&szlig;e von Mosambik','Mosambik','Yes','No'),
	array('Stra&szlig;e von Mosambik','Antananarivo','Yes','No'),
	array('Stra&szlig;e von Mosambik','S&uuml;d-Madagaskar','Yes','No'),
	array('Stra&szlig;e von Mosambik','Komoren','Yes','No'),
	array('Maskarenen Plateau','Antananarivo','Yes','No'),
	array('Maskarenen Plateau','S&uuml;d-Madagaskar','Yes','No'),
	array('Maskarenen Plateau','Seychellen','Yes','No'),
	array('Maskarenen Plateau','Komoren','Yes','No'),
	array('Maskarenen Plateau','Mauritius','Yes','No'),
	array('Maskarenen Plateau','R&eacute;union','Yes','No'),
	array('Victoriasee','Nairobi','Yes','No'),
	array('Victoriasee','Uganda','Yes','No'),
	array('Victoriasee','West-Tanganjika','Yes','No'),
	array('Stra&szlig;e von Gibraltar','Casablanca','Yes','No'),
	array('Stra&szlig;e von Gibraltar','Ost-Marokko','Yes','No'),
	array('Sinai','Kairo','Yes','Yes'),
	array('Kairo','Alexandria','Yes','Yes'),
	array('Kairo','Luxor','Yes','Yes'),
	array('Kairo','Hurghada','No','Yes'),
	array('Kairo','Hurghada (East Coast)','Yes','No'),
	array('Kairo','Hurghada (West Coast)','Yes','No'),
	array('Alexandria','Luxor','Yes','Yes'),
	array('Alexandria','Bengasi','Yes','Yes'),
	array('Luxor','Bengasi','No','Yes'),
	array('Luxor','Omdurman','Yes','Yes'),
	array('Luxor','Hurghada','No','Yes'),
	array('Luxor','Hurghada (West Coast)','Yes','No'),
	array('Bengasi','Syrte','Yes','Yes'),
	array('Bengasi','Fessan','No','Yes'),
	array('Bengasi','Nord-Tschad','No','Yes'),
	array('Bengasi','Darfur','No','Yes'),
	array('Bengasi','Omdurman','No','Yes'),
	array('Syrte','Fessan','No','Yes'),
	array('Syrte','Tripolis','Yes','Yes'),
	array('Fessan','Tripolis','No','Yes'),
	array('Fessan','Nord-Tschad','No','Yes'),
	array('Fessan','Tamanrasset','No','Yes'),
	array('Fessan','Agadez','No','Yes'),
	array('Tripolis','Tamanrasset','No','Yes'),
	array('Tripolis','Tunesien','Yes','Yes'),
	array('Nord-Tschad','N\\\'Djamena','No','Yes'),
	array('Nord-Tschad','Darfur','No','Yes'),
	array('Nord-Tschad','Agadez','No','Yes'),
	array('Nord-Tschad','S&uuml;d-Niger','No','Yes'),
	array('N\\\'Djamena','Darfur','No','Yes'),
	array('N\\\'Djamena','Zentralafrikanische Republik','No','Yes'),
	array('N\\\'Djamena','S&uuml;d-Niger','No','Yes'),
	array('N\\\'Djamena','Kano','No','Yes'),
	array('N\\\'Djamena','Kamerun','No','Yes'),
	array('Tamanrasset','Adrar','No','Yes'),
	array('Tamanrasset','West-Algerien','No','Yes'),
	array('Tamanrasset','Azawad','No','Yes'),
	array('Tamanrasset','Agadez','No','Yes'),
	array('Tamanrasset','Algier','No','Yes'),
	array('Tamanrasset','Tunesien','No','Yes'),
	array('Adrar','West-Algerien','No','Yes'),
	array('Adrar','Azawad','No','Yes'),
	array('Adrar','West-Sahara','No','Yes'),
	array('Adrar','Nord-Mauretanien','No','Yes'),
	array('Adrar','Marrakesch','No','Yes'),
	array('West-Algerien','Ost-Marokko','No','Yes'),
	array('West-Algerien','Marrakesch','No','Yes'),
	array('West-Algerien','Algier','No','Yes'),
	array('Darfur','Zentralafrikanische Republik','No','Yes'),
	array('Darfur','Juba','No','Yes'),
	array('Darfur','Omdurman','No','Yes'),
	array('Azawad','Nord-Mauretanien','No','Yes'),
	array('Azawad','Nuakschott','No','Yes'),
	array('Azawad','Timbuktu','No','Yes'),
	array('Azawad','Agadez','No','Yes'),
	array('Azawad','S&uuml;d-Niger','No','Yes'),
	array('Azawad','Gao','No','Yes'),
	array('West-Sahara','Nord-Mauretanien','Yes','Yes'),
	array('West-Sahara','Marrakesch','Yes','Yes'),
	array('West-Sahara','Kanarische Inseln','Yes','No'),
	array('Nord-Mauretanien','Nuakschott','Yes','Yes'),
	array('Nuakschott','Timbuktu','No','Yes'),
	array('Nuakschott','Dakar','Yes','Yes'),
	array('Nuakschott','Kayes','Yes','Yes'),
	array('Nuakschott','Mopti & S&eacute;gou','No','Yes'),
	array('Nuakschott','Bamako','No','Yes'),
	array('Casablanca','Ost-Marokko','Yes','Yes'),
	array('Casablanca','Marrakesch','Yes','Yes'),
	array('Ost-Marokko','Marrakesch','No','Yes'),
	array('Ost-Marokko','Algier','Yes','Yes'),
	array('Marrakesch','Kanarische Inseln','Yes','No'),
	array('Timbuktu','Gao','Yes','Yes'),
	array('Timbuktu','Mopti & S&eacute;gou','Yes','Yes'),
	array('Agadez','S&uuml;d-Niger','No','Yes'),
	array('Zentralafrikanische Republik','Orientale','No','Yes'),
	array('Zentralafrikanische Republik','Kamerun','No','Yes'),
	array('Zentralafrikanische Republik','Juba','No','Yes'),
	array('Zentralafrikanische Republik','&Eacute;quateur','No','Yes'),
	array('Zentralafrikanische Republik','Republik Kongo','No','Yes'),
	array('Orientale','Juba','No','Yes'),
	array('Orientale','Uganda','No','Yes'),
	array('Orientale','Kivu','No','Yes'),
	array('Orientale','Kasai','Yes','Yes'),
	array('Orientale','&Eacute;quateur','Yes','Yes'),
	array('S&uuml;d-Niger','Kano','No','Yes'),
	array('S&uuml;d-Niger','Nordwest-Nigeria','No','Yes'),
	array('S&uuml;d-Niger','Gao','No','Yes'),
	array('S&uuml;d-Niger','Niamey','No','Yes'),
	array('Algier','Tunesien','Yes','Yes'),
	array('Ascension','St Helena','Yes','No'),
	array('Kano','Nordwest-Nigeria','No','Yes'),
	array('Kano','Kamerun','No','Yes'),
	array('Kano','Abuja','No','Yes'),
	array('Kano','Port Harcourt','No','Yes'),
	array('Nordwest-Nigeria','Abuja','Yes','Yes'),
	array('Nordwest-Nigeria','Lagos','Yes','Yes'),
	array('Nordwest-Nigeria','Niamey','Yes','Yes'),
	array('Gao','Burkina Faso','No','Yes'),
	array('Gao','Niamey','Yes','Yes'),
	array('Gao','Mopti & S&eacute;gou','No','Yes'),
	array('Burkina Faso','Ghana','No','Yes'),
	array('Burkina Faso','Elfenbeink&uuml;ste','No','Yes'),
	array('Burkina Faso','Niamey','No','Yes'),
	array('Burkina Faso','Sikasso','No','Yes'),
	array('Burkina Faso','Mopti & S&eacute;gou','No','Yes'),
	array('Burkina Faso','Togo & Benin','No','Yes'),
	array('Kamerun','&Auml;quatorialguinea','Yes','Yes'),
	array('Kamerun','Gabun','No','Yes'),
	array('Kamerun','Port Harcourt','Yes','Yes'),
	array('Kamerun','S&atilde;o Tom&eacute; und Pr&iacute;ncipe','Yes','No'),
	array('Kamerun','Republik Kongo','No','Yes'),
	array('&Auml;quatorialguinea','Gabun','Yes','Yes'),
	array('&Auml;quatorialguinea','S&atilde;o Tom&eacute; und Pr&iacute;ncipe','Yes','No'),
	array('Gabun','S&atilde;o Tom&eacute; und Pr&iacute;ncipe','Yes','No'),
	array('Gabun','Republik Kongo','No','Yes'),
	array('Gabun','Republik Kongo (West Coast)','Yes','No'),
	array('Luanda','Kasai','No','Yes'),
	array('Luanda','Lubumbashi','No','Yes'),
	array('Luanda','Lusaka','No','Yes'),
	array('Luanda','S&uuml;d-Angola','Yes','Yes'),
	array('Luanda','Kinshasa','Yes','Yes'),
	array('Juba','&Ouml;stlicher S&uuml;d-Sudan','Yes','Yes'),
	array('Juba','Omdurman','Yes','Yes'),
	array('Juba','Uganda','Yes','Yes'),
	array('Abuja','Lagos','Yes','Yes'),
	array('Abuja','Port Harcourt','Yes','Yes'),
	array('&Ouml;stlicher S&uuml;d-Sudan','Omdurman','Yes','Yes'),
	array('&Ouml;stlicher S&uuml;d-Sudan','Nairobi','No','Yes'),
	array('&Ouml;stlicher S&uuml;d-Sudan','Uganda','Yes','Yes'),
	array('&Ouml;stlicher S&uuml;d-Sudan','Southern Nations, Nationalities & People\\\'s Region','No','Yes'),
	array('&Ouml;stlicher S&uuml;d-Sudan','Khartum','No','Yes'),
	array('&Ouml;stlicher S&uuml;d-Sudan','Khartum (West Coast)','Yes','No'),
	array('&Ouml;stlicher S&uuml;d-Sudan','Addis Abeba','No','Yes'),
	array('Omdurman','Khartum','No','Yes'),
	array('Omdurman','Khartum (West Coast)','Yes','No'),
	array('Eritrea','Amhara','No','Yes'),
	array('Eritrea','Dschibuti','Yes','Yes'),
	array('Eritrea','Khartum','No','Yes'),
	array('Eritrea','Khartum (East Coast)','Yes','No'),
	array('Amhara','Dschibuti','No','Yes'),
	array('Amhara','Dire Dawa','No','Yes'),
	array('Amhara','Khartum','No','Yes'),
	array('Amhara','Addis Abeba','No','Yes'),
	array('Amhara','Addis Abeba (North Coast)','Yes','No'),
	array('Dschibuti','Somaliland','Yes','Yes'),
	array('Dschibuti','Dire Dawa','No','Yes'),
	array('Somaliland','Mogadischu','Yes','Yes'),
	array('Somaliland','Dire Dawa','No','Yes'),
	array('Mogadischu','S&uuml;d-Somalia','Yes','Yes'),
	array('Mogadischu','Dire Dawa','Yes','Yes'),
	array('Nairobi','Mombasa','No','Yes'),
	array('Nairobi','Uganda','Yes','Yes'),
	array('Nairobi','West-Tanganjika','Yes','Yes'),
	array('Nairobi','Daressalaam','No','Yes'),
	array('Nairobi','Southern Nations, Nationalities & People\\\'s Region','No','Yes'),
	array('Nairobi','Addis Abeba','No','Yes'),
	array('Mombasa','S&uuml;d-Somalia','Yes','Yes'),
	array('Mombasa','Daressalaam','Yes','Yes'),
	array('Mombasa','Dire Dawa','No','Yes'),
	array('Mombasa','Sansibar','Yes','No'),
	array('Mombasa','Addis Abeba','No','Yes'),
	array('S&uuml;d-Somalia','Dire Dawa','Yes','Yes'),
	array('S&uuml;d-Somalia','Sansibar','Yes','No'),
	array('Uganda','Kivu','No','Yes'),
	array('Uganda','Ruanda','No','Yes'),
	array('Uganda','West-Tanganjika','Yes','Yes'),
	array('Kivu','Ruanda','No','Yes'),
	array('Kivu','West-Tanganjika','No','Yes'),
	array('Kivu','Kasai','No','Yes'),
	array('Kivu','Burundi','No','Yes'),
	array('Kivu','Lubumbashi','No','Yes'),
	array('Lagos','Port Harcourt','Yes','Yes'),
	array('Lagos','Togo & Benin','No','Yes'),
	array('Lagos','Togo & Benin (North Coast)','Yes','No'),
	array('Lagos','Togo & Benin (South Coast)','Yes','No'),
	array('Lagos','S&atilde;o Tom&eacute; und Pr&iacute;ncipe','Yes','No'),
	array('Liberia','Guinea','No','Yes'),
	array('Liberia','Elfenbeink&uuml;ste','Yes','Yes'),
	array('Liberia','Sierra Leone','Yes','Yes'),
	array('Guinea','Guinea-Bissau','Yes','Yes'),
	array('Guinea','S&uuml;d-Senegal','No','Yes'),
	array('Guinea','Kayes','No','Yes'),
	array('Guinea','Elfenbeink&uuml;ste','No','Yes'),
	array('Guinea','Sierra Leone','Yes','Yes'),
	array('Guinea','Sikasso','No','Yes'),
	array('Guinea','Bamako','No','Yes'),
	array('Guinea-Bissau','S&uuml;d-Senegal','Yes','Yes'),
	array('Dakar','Gambia','Yes','Yes'),
	array('Dakar','S&uuml;d-Senegal','No','Yes'),
	array('Dakar','Kayes','Yes','Yes'),
	array('Gambia','S&uuml;d-Senegal','Yes','Yes'),
	array('S&uuml;d-Senegal','Kayes','No','Yes'),
	array('Kayes','Bamako','No','Yes'),
	array('Kayes','Bamako (West Coast)','Yes','No'),
	array('Ghana','Elfenbeink&uuml;ste','Yes','Yes'),
	array('Ghana','Togo & Benin','No','Yes'),
	array('Ghana','Togo & Benin (South Coast)','Yes','No'),
	array('Elfenbeink&uuml;ste','Sikasso','No','Yes'),
	array('Niamey','Togo & Benin','No','Yes'),
	array('Niamey','Togo & Benin (North Coast)','Yes','No'),
	array('Ruanda','West-Tanganjika','No','Yes'),
	array('Ruanda','Burundi','No','Yes'),
	array('West-Tanganjika','Daressalaam','No','Yes'),
	array('West-Tanganjika','Burundi','No','Yes'),
	array('West-Tanganjika','Lubumbashi','No','Yes'),
	array('West-Tanganjika','Ost-Sambia','No','Yes'),
	array('Daressalaam','Ost-Sambia','No','Yes'),
	array('Daressalaam','Sansibar','Yes','No'),
	array('Daressalaam','Malawi','No','Yes'),
	array('Daressalaam','Mosambik','Yes','Yes'),
	array('Kasai','Lubumbashi','Yes','Yes'),
	array('Kasai','Kinshasa','No','Yes'),
	array('Kasai','&Eacute;quateur','No','Yes'),
	array('Lubumbashi','Ost-Sambia','No','Yes'),
	array('Lubumbashi','Lusaka','No','Yes'),
	array('Dire Dawa','Addis Abeba','No','Yes'),
	array('Dire Dawa','Addis Abeba (East Coast)','Yes','No'),
	array('Port Harcourt','S&atilde;o Tom&eacute; und Pr&iacute;ncipe','Yes','No'),
	array('Ost-Sambia','Lusaka','No','Yes'),
	array('Ost-Sambia','Malawi','No','Yes'),
	array('Ost-Sambia','Mosambik','No','Yes'),
	array('Lusaka','S&uuml;d-Angola','No','Yes'),
	array('Lusaka','Botswana','No','Yes'),
	array('Lusaka','Mosambik','No','Yes'),
	array('Lusaka','Simbabwe','No','Yes'),
	array('Sikasso','Mopti & S&eacute;gou','No','Yes'),
	array('Sikasso','Bamako','No','Yes'),
	array('Cabinda','Kinshasa','Yes','Yes'),
	array('Cabinda','Republik Kongo','No','Yes'),
	array('Cabinda','Republik Kongo (East Coast)','Yes','No'),
	array('Cabinda','Republik Kongo (West Coast)','Yes','No'),
	array('S&uuml;d-Angola','Namibia','Yes','Yes'),
	array('S&uuml;d-Angola','Botswana','No','Yes'),
	array('Namibia','Botswana','No','Yes'),
	array('Namibia','Nordkap','Yes','Yes'),
	array('Botswana','Simbabwe','No','Yes'),
	array('Botswana','Johannesburg','No','Yes'),
	array('Botswana','Nordkap','No','Yes'),
	array('Lesotho','Oranje-Freistaat','No','Yes'),
	array('Lesotho','Port Elizabeth','No','Yes'),
	array('Lesotho','Durban','No','Yes'),
	array('Swasiland','Mosambik','Yes','Yes'),
	array('Swasiland','Johannesburg','No','Yes'),
	array('Swasiland','Durban','Yes','Yes'),
	array('Kinshasa','&Eacute;quateur','Yes','Yes'),
	array('Kinshasa','Republik Kongo','No','Yes'),
	array('Kinshasa','Republik Kongo (East Coast)','Yes','No'),
	array('Malawi','Mosambik','No','Yes'),
	array('Mosambik','Simbabwe','No','Yes'),
	array('Mosambik','Johannesburg','No','Yes'),
	array('Antananarivo','S&uuml;d-Madagaskar','Yes','Yes'),
	array('Antananarivo','Komoren','Yes','No'),
	array('Simbabwe','Johannesburg','No','Yes'),
	array('Johannesburg','Oranje-Freistaat','No','Yes'),
	array('Johannesburg','Nordkap','No','Yes'),
	array('Johannesburg','Durban','No','Yes'),
	array('Oranje-Freistaat','Port Elizabeth','No','Yes'),
	array('Oranje-Freistaat','Nordkap','No','Yes'),
	array('Oranje-Freistaat','Durban','No','Yes'),
	array('Port Elizabeth','Kapstadt','Yes','Yes'),
	array('Port Elizabeth','Nordkap','No','Yes'),
	array('Port Elizabeth','Durban','Yes','Yes'),
	array('Kapstadt','Nordkap','Yes','Yes'),
	array('Southern Nations, Nationalities & People\\\'s Region','Addis Abeba','No','Yes'),
	array('Mopti & S&eacute;gou','Bamako','No','Yes'),
	array('Mopti & S&eacute;gou','Bamako (East Coast)','Yes','No'),
	array('&Eacute;quateur','Republik Kongo','No','Yes'),
	array('&Eacute;quateur','Republik Kongo (East Coast)','Yes','No'),
	array('Hurghada','Khartum','No','Yes'),
	array('Hurghada (East Coast)','Khartum (East Coast)','Yes','No'),
	array('Hurghada (West Coast)','Khartum (West Coast)','Yes','No'),
	array('Seychellen','Komoren','Yes','No'),
	array('Seychellen','Mauritius','Yes','No'),
	array('Mauritius','R&eacute;union','Yes','No'),
	array('Khartum','Addis Abeba','No','Yes'),
	array('Khartum (West Coast)','Addis Abeba (North Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
