<?php
// This is file installs the map data for the GobbleEarth variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Abyssinia', 'Land', 'Yes', 0, 1197, 503, 1198, 503),
	array('Accra', 'Coast', 'Yes', 2, 905, 515, 906, 516),
	array('Aden', 'Coast', 'Yes', 2, 1249, 453, 1250, 453),
	array('Adriatic Sea', 'Sea', 'No', 0, 1020, 239, 1021, 240),
	array('Aegean Sea', 'Sea', 'No', 0, 1081, 271, 1082, 272),
	array('Afghanistan', 'Land', 'Yes', 0, 1348, 305, 1349, 306),
	array('Albania', 'Coast', 'No', 0, 1047, 249, 1047, 250),
	array('Amazon', 'Land', 'No', 10, 486, 602, 487, 602),
	array('Angola', 'Coast', 'No', 0, 1023, 668, 1024, 668),
	array('Ankara', 'Coast', 'Yes', 7, 1129, 255, 1130, 256),
	array('Antananarivo', 'Coast', 'Yes', 3, 1229, 726, 1230, 727),
	array('Apulia', 'Coast', 'No', 5, 1021, 248, 1022, 249),
	array('Arabia', 'Coast', 'No', 0, 1225, 367, 1226, 368),
	array('Arabian Sea', 'Sea', 'No', 0, 1333, 476, 1333, 476),
	array('Armenia', 'Coast', 'No', 7, 1180, 267, 1181, 268),
	array('Asmara', 'Coast', 'Yes', 5, 1179, 442, 1179, 443),
	array('Astrakhan', 'Land', 'No', 6, 1219, 200, 1220, 201),
	array('Baghdad', 'Coast', 'Yes', 7, 1218, 321, 1219, 322),
	array('Baltic Sea', 'Sea', 'No', 0, 1031, 136, 1031, 136),
	array('Bamako', 'Land', 'Yes', 3, 887, 473, 888, 474),
	array('Barents Sea', 'Sea', 'No', 0, 1100, 20, 1101, 20),
	array('Barranquilla', 'Coast', 'Yes', 12, 406, 507, 407, 508),
	array('Bay of Bengal', 'Sea', 'No', 0, 1522, 485, 1522, 485),
	array('Bechuanaland', 'Land', 'No', 2, 1093, 733, 1094, 733),
	array('Belgian Congo', 'Coast', 'Yes', 0, 1038, 608, 1039, 609),
	array('Belgium', 'Coast', 'Yes', 0, 949, 177, 949, 178),
	array('Bengal', 'Coast', 'No', 2, 1479, 374, 1479, 374),
	array('Berlin', 'Coast', 'Yes', 4, 998, 166, 999, 167),
	array('Black Sea', 'Sea', 'No', 0, 1138, 236, 1138, 237),
	array('Bogota', 'Coast', 'Yes', 12, 414, 546, 415, 547),
	array('Bohemia', 'Land', 'No', 1, 1015, 185, 1016, 185),
	array('Bolivia', 'Land', 'Yes', 0, 477, 699, 478, 700),
	array('Bombay', 'Coast', 'Yes', 2, 1394, 379, 1394, 380),
	array('Brest', 'Coast', 'Yes', 3, 916, 202, 917, 203),
	array('East Africa', 'Coast', 'No', 2, 1174, 569, 1174, 569),
	array('British Guiana', 'Coast', 'No', 2, 511, 531, 511, 531),
	array('Somaliland', 'Coast', 'No', 2, 1237, 493, 1238, 494),
	array('Budapest', 'Land', 'Yes', 1, 1052, 208, 1052, 209),
	array('Buenos Aires', 'Coast', 'Yes', 11, 530, 853, 531, 853),
	array('Bulgaria', 'Coast', 'Yes', 0, 1081, 237, 1081, 238),
	array('Burgundy', 'Land', 'No', 3, 958, 200, 959, 201),
	array('Burma', 'Coast', 'No', 2, 1563, 412, 1564, 413),
	array('Cairo', 'Coast', 'Yes', 2, 1129, 345, 1129, 346),
	array('Cambodia', 'Coast', 'No', 3, 1637, 481, 1637, 481),
	array('Capetown', 'Coast', 'Yes', 2, 1067, 823, 1067, 823),
	array('Caribbean', 'Sea', 'No', 0, 437, 456, 438, 456),
	array('Celebes', 'Coast', 'No', 0, 1745, 589, 1746, 590),
	array('Chad', 'Land', 'No', 3, 1016, 456, 1017, 456),
	array('Chile', 'Coast', 'Yes', 0, 455, 847, 456, 847),
	array('Choco', 'Coast', 'No', 12, 391, 534, 391, 534),
	array('Chugoku', 'Coast', 'No', 9, 1783, 298, 1784, 298),
	array('Chungking', 'Land', 'Yes', 8, 1568, 321, 1568, 321),
	array('Clyde', 'Coast', 'No', 2, 898, 131, 899, 132),
	array('Constantinople', 'Coast', 'Yes', 7, 1101, 258, 1101, 258),
	array('Cordoba', 'Land', 'Yes', 11, 483, 820, 484, 821),
	array('Costa Rica', 'Coast', 'No', 0, 340, 492, 340, 492),
	array('Cuba', 'Coast', 'Yes', 0, 396, 407, 396, 407),
	array('Cyrenacia', 'Coast', 'No', 5, 1062, 327, 1062, 327),
	array('Dar es Salaam', 'Coast', 'Yes', 4, 1169, 626, 1170, 627),
	array('Denmark', 'Coast', 'Yes', 0, 987, 139, 984, 135),
	array('Urumtsi', 'Land', 'Yes', 8, 1456, 250, 1457, 251),
	array('Duala', 'Coast', 'Yes', 4, 1004, 537, 1004, 537),
	array('Dutch New Guinea', 'Coast', 'Yes', 0, 1864, 601, 1864, 601),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 1108, 308, 1108, 309),
	array('East China Sea', 'Sea', 'No', 0, 1748, 352, 1748, 353),
	array('East Indian Ocean', 'Sea', 'No', 0, 1524, 681, 1524, 681),
	array('East Pacific Ocean', 'Sea', 'No', 0, 67, 356, 68, 356),
	array('Ecuador', 'Coast', 'Yes', 0, 381, 585, 382, 585),
	array('Edinburgh', 'Coast', 'Yes', 2, 909, 134, 908, 135),
	array('English Channel', 'Sea', 'No', 0, 915, 183, 916, 184),
	array('Equatorial Atlantic Ocean', 'Sea', 'No', 0, 727, 530, 727, 531),
	array('Fairbanks', 'Coast', 'Yes', 14, 125, 89, 125, 90),
	array('Finland', 'Coast', 'No', 6, 1070, 90, 1071, 91),
	array('Fortaleza', 'Coast', 'Yes', 10, 609, 609, 610, 609),
	array('French Guiana', 'Coast', 'No', 3, 553, 537, 554, 538),
	array('Friedrich-Wilhelmshafen', 'Coast', 'Yes', 4, 1901, 608, 1902, 609),
	array('Galicia', 'Land', 'No', 1, 1066, 185, 1067, 185),
	array('Gascony', 'Coast', 'No', 3, 924, 221, 925, 222),
	array('Gobi Desert', 'Land', 'No', 8, 1598, 259, 1599, 260),
	array('Namaqualand', 'Coast', 'No', 4, 1033, 774, 1033, 775),
	array('Greece', 'Coast', 'Yes', 0, 1062, 264, 1063, 265),
	array('Guadalajara', 'Coast', 'Yes', 13, 219, 398, 219, 399),
	array('Guatemala', 'Coast', 'Yes', 0, 306, 451, 306, 451),
	array('Gulf of Alaska', 'Sea', 'No', 0, 90, 192, 91, 193),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 1039, 104, 1040, 105),
	array('Gulf of Guinea', 'Sea', 'No', 0, 924, 572, 924, 573),
	array('Gulf of Honduras', 'Sea', 'No', 0, 338, 426, 339, 426),
	array('Gulf of Lyon', 'Sea', 'No', 0, 958, 248, 959, 249),
	array('Gulf of Mexico', 'Sea', 'No', 0, 318, 375, 318, 376),
	array('Gulf of Panama', 'Sea', 'No', 0, 350, 541, 350, 541),
	array('Gulf of Persia', 'Sea', 'No', 0, 1261, 362, 1262, 362),
	array('Gulf of Tehuantepec', 'Sea', 'No', 0, 269, 461, 269, 461),
	array('Hamgyong', 'Coast', 'No', 9, 1733, 254, 1731, 250),
	array('Hanoi', 'Coast', 'Yes', 3, 1619, 415, 1620, 415),
	array('Helgoland Bight', 'Sea', 'No', 0, 966, 148, 967, 149),
	array('Haiti', 'Coast', 'Yes', 0, 434, 420, 435, 421),
	array('Holland', 'Coast', 'Yes', 0, 956, 168, 957, 168),
	array('Honduras', 'Coast', 'No', 0, 325, 459, 325, 460),
	array('Honolulu', 'Coast', 'Yes', 14, 2175, 418, 2175, 418),
	array('Hyderabad', 'Coast', 'No', 2, 1451, 422, 1452, 422),
	array('Ionian Sea', 'Sea', 'No', 0, 1032, 299, 1033, 300),
	array('Irish Sea', 'Sea', 'No', 0, 889, 170, 889, 171),
	array('Irkutsk', 'Land', 'Yes', 6, 1539, 144, 1540, 145),
	array('Ivory Coast', 'Coast', 'No', 3, 878, 515, 878, 516),
	array('Java', 'Coast', 'Yes', 0, 1660, 626, 1660, 627),
	array('Gulf of Siam', 'Sea', 'No', 0, 1651, 578, 1652, 578),
	array('Borneo', 'Coast', 'Yes', 0, 1697, 581, 1697, 581),
	array('Kamchatka', 'Coast', 'No', 6, 1826, 91, 1827, 91),
	array('Kiel', 'Coast', 'Yes', 4, 978, 164, 978, 164),
	array('Kwangtung', 'Coast', 'No', 8, 1644, 373, 1644, 374),
	array('Lagos', 'Coast', 'Yes', 2, 962, 509, 962, 509),
	array('Liberia', 'Coast', 'Yes', 0, 853, 522, 853, 523),
	array('Libreville', 'Coast', 'Yes', 3, 1000, 587, 1000, 587),
	array('Liverpool', 'Coast', 'Yes', 2, 910, 151, 910, 152),
	array('Livonia', 'Coast', 'No', 6, 1063, 135, 1063, 136),
	array('London', 'Coast', 'Yes', 2, 927, 168, 927, 169),
	array('Los Angeles', 'Coast', 'Yes', 14, 169, 284, 169, 284),
	array('Madras', 'Coast', 'Yes', 2, 1445, 478, 1445, 479),
	array('Malaya', 'Coast', 'No', 2, 1618, 543, 1619, 544),
	array('Manchuria', 'Coast', 'No', 8, 1687, 225, 1688, 225),
	array('Manila', 'Coast', 'Yes', 14, 1751, 482, 1739, 441),
	array('Mariana Trench', 'Sea', 'No', 0, 1856, 367, 1857, 367),
	array('Marseilles', 'Coast', 'Yes', 3, 953, 227, 953, 227),
	array('Mecca', 'Coast', 'Yes', 7, 1178, 379, 1178, 380),
	array('Melbourne', 'Coast', 'Yes', 2, 1813, 775, 1814, 775),
	array('Merida', 'Coast', 'Yes', 13, 317, 417, 317, 417),
	array('Mexico', 'Coast', 'Yes', 13, 250, 415, 250, 416),
	array('Miami', 'Coast', 'Yes', 14, 373, 321, 373, 322),
	array('Micronesia', 'Sea', 'No', 0, 1992, 493, 1993, 494),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 0, 741, 280, 741, 280),
	array('Midwest', 'Land', 'No', 14, 336, 237, 336, 237),
	array('Mogadishu', 'Coast', 'Yes', 5, 1238, 534, 1239, 534),
	array('Mongolia', 'Land', 'No', 8, 1522, 206, 1523, 206),
	array('Moscow', 'Land', 'Yes', 6, 1146, 150, 1146, 150),
	array('Mozambique', 'Coast', 'Yes', 0, 1152, 716, 1152, 717),
	array('Mozambique channel', 'Sea', 'No', 0, 1168, 788, 1169, 788),
	array('Munich', 'Land', 'Yes', 4, 990, 187, 990, 188),
	array('Nagasaki', 'Coast', 'Yes', 9, 1775, 318, 1778, 323),
	array('Naples', 'Coast', 'Yes', 5, 1020, 257, 1020, 257),
	array('Nazca Ridge', 'Sea', 'No', 0, 360, 684, 360, 685),
	array('New England', 'Coast', 'No', 14, 481, 232, 482, 232),
	array('Nicaragua', 'Coast', 'Yes', 0, 333, 471, 333, 472),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 697, 145, 697, 146),
	array('North Africa', 'Coast', 'No', 3, 897, 311, 897, 312),
	array('North Pacific Ocean', 'Sea', 'No', 0, 2045, 192, 2046, 193),
	array('North Sea', 'Sea', 'No', 0, 946, 136, 946, 136),
	array('North-West Territories', 'Coast', 'No', 2, 356, 79, 356, 79),
	array('Norway', 'Coast', 'Yes', 0, 987, 92, 987, 92),
	array('Norwegian Sea', 'Sea', 'No', 0, 914, 63, 915, 63),
	array('Oaxaca', 'Coast', 'No', 13, 282, 438, 283, 438),
	array('Oman', 'Coast', 'No', 0, 1310, 400, 1310, 401),
	array('Ontario', 'Land', 'No', 2, 430, 208, 430, 208),
	array('Pacific Northwest', 'Coast', 'No', 14, 198, 219, 199, 220),
	array('Pampas', 'Land', 'No', 11, 508, 781, 508, 781),
	array('Panama', 'Coast', 'Yes', 0, 363, 505, 363, 508),
	array('Pantanal', 'Land', 'No', 10, 555, 687, 555, 687),
	array('Papua', 'Coast', 'No', 2, 1897, 628, 1898, 629),
	array('Para', 'Coast', 'No', 10, 555, 591, 556, 591),
	array('Paraguay', 'Land', 'Yes', 0, 539, 759, 540, 759),
	array('Paris', 'Land', 'Yes', 3, 935, 201, 935, 202),
	array('Patagonia', 'Coast', 'No', 11, 500, 898, 501, 899),
	array('Peking', 'Coast', 'Yes', 8, 1649, 275, 1649, 275),
	array('Persia', 'Coast', 'Yes', 0, 1268, 323, 1268, 324),
	array('Peru', 'Coast', 'Yes', 0, 407, 657, 407, 658),
	array('Phillipine Sea', 'Sea', 'No', 0, 1815, 515, 1816, 515),
	array('Picardy', 'Coast', 'No', 3, 929, 186, 929, 187),
	array('Piedmont', 'Coast', 'No', 5, 973, 220, 974, 220),
	array('Polynesia', 'Sea', 'No', 0, 2099, 692, 2100, 692),
	array('Portugal', 'Coast', 'Yes', 0, 869, 260, 870, 260),
	array('Prussia', 'Coast', 'No', 4, 1038, 154, 1038, 154),
	array('Quebec', 'Coast', 'Yes', 2, 494, 176, 494, 177),
	array('Recife', 'Coast', 'Yes', 10, 644, 648, 644, 649),
	array('Red Sea', 'Sea', 'No', 0, 1175, 413, 1176, 414),
	array('Rhodesia', 'Land', 'No', 2, 1105, 685, 1105, 686),
	array('Rio de Janeiro', 'Coast', 'Yes', 10, 614, 730, 614, 730),
	array('Rio de la Plata', 'Sea', 'No', 0, 616, 820, 616, 820),
	array('Rio Grande', 'Coast', 'No', 13, 247, 375, 247, 375),
	array('Santa Cruz', 'Coast', 'Yes', 11, 506, 953, 506, 954),
	array('Rumania', 'Coast', 'Yes', 0, 1089, 221, 1090, 221),
	array('Rome', 'Coast', 'Yes', 5, 1002, 247, 1002, 247),
	array('Ruhr', 'Land', 'No', 4, 967, 183, 967, 183),
	array('Samarkand', 'Land', 'Yes', 6, 1297, 262, 1297, 263),
	array('Santa Catarina', 'Coast', 'No', 10, 571, 788, 572, 789),
	array('Sapporo', 'Coast', 'Yes', 9, 1810, 232, 1811, 232),
	array('Sarawak', 'Coast', 'No', 2, 1697, 547, 1698, 547),
	array('Sargasso Sea', 'Sea', 'No', 0, 478, 342, 478, 343),
	array('Saskatchewan', 'Land', 'No', 2, 299, 156, 299, 157),
	array('Sea of Japan', 'Sea', 'No', 0, 1769, 262, 1769, 262),
	array('Sea of Okhotsk', 'Sea', 'No', 0, 1790, 154, 1790, 155),
	array('Seoul', 'Coast', 'Yes', 9, 1743, 288, 1744, 289),
	array('Serbia', 'Land', 'Yes', 0, 1054, 237, 1055, 237),
	array('Sevastopol', 'Coast', 'Yes', 6, 1128, 207, 1131, 200),
	array('Seychelles', 'Sea', 'No', 0, 1234, 624, 1234, 624),
	array('Shanghai', 'Coast', 'Yes', 8, 1692, 332, 1692, 332),
	array('Siam', 'Coast', 'Yes', 0, 1597, 453, 1598, 454),
	array('Siberia', 'Land', 'No', 6, 1344, 113, 1344, 114),
	array('Sierra Leone', 'Coast', 'No', 2, 837, 503, 837, 503),
	array('Silesia', 'Land', 'No', 4, 1028, 176, 1028, 177),
	array('Skagerrak', 'Sea', 'No', 0, 987, 123, 988, 123),
	array('Skeleton coast', 'Sea', 'No', 0, 933, 736, 933, 736),
	array('Dahomny', 'Coast', 'No', 3, 924, 506, 924, 506),
	array('Smyrna', 'Coast', 'Yes', 7, 1127, 280, 1128, 280),
	array('Sonora', 'Coast', 'No', 13, 192, 347, 193, 347),
	array('South Atlantic Ocean', 'Sea', 'No', 0, 705, 906, 705, 906),
	array('South China Sea', 'Sea', 'No', 0, 1683, 456, 1684, 457),
	array('South Pacific Ocean', 'Sea', 'No', 0, 184, 583, 185, 584),
	array('Spain', 'Coast', 'Yes', 0, 906, 254, 907, 255),
	array('Spainish Sahara', 'Coast', 'No', 0, 829, 378, 829, 379),
	array('St Petersburg', 'Coast', 'Yes', 6, 1120, 107, 1121, 107),
	array('Sudan', 'Coast', 'No', 2, 1136, 448, 1136, 449),
	array('Sumatra', 'Coast', 'No', 0, 1615, 579, 1616, 579),
	array('Surinam', 'Coast', 'Yes', 0, 534, 538, 535, 539),
	array('Sweden', 'Coast', 'Yes', 0, 1013, 109, 1014, 110),
	array('Syria', 'Coast', 'No', 7, 1161, 303, 1162, 304),
	array('Texas', 'Coast', 'No', 14, 274, 326, 274, 326),
	array('Timor Sea', 'Sea', 'No', 0, 1789, 626, 1789, 626),
	array('Tohoku', 'Coast', 'No', 9, 1815, 271, 1816, 272),
	array('Tokyo', 'Coast', 'Yes', 9, 1813, 294, 1813, 294),
	array('Trieste', 'Coast', 'Yes', 1, 1024, 224, 1025, 224),
	array('Tripoli', 'Coast', 'Yes', 5, 1015, 328, 1016, 328),
	array('Tunis', 'Coast', 'Yes', 3, 981, 293, 982, 294),
	array('Turkestan', 'Land', 'No', 6, 1343, 205, 1343, 205),
	array('Tuscany', 'Coast', 'No', 5, 992, 233, 992, 233),
	array('Tyrolia', 'Land', 'No', 1, 995, 206, 996, 207),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 994, 265, 995, 266),
	array('Ukraine', 'Land', 'No', 6, 1101, 185, 1101, 186),
	array('Vancouver', 'Coast', 'Yes', 2, 197, 171, 197, 171),
	array('Venezuela', 'Coast', 'Yes', 0, 463, 505, 463, 505),
	array('Venice', 'Coast', 'Yes', 5, 996, 222, 996, 222),
	array('Vienna', 'Land', 'Yes', 1, 1033, 196, 1033, 196),
	array('Vladivostok', 'Coast', 'Yes', 6, 1747, 187, 1748, 188),
	array('Wales', 'Coast', 'No', 2, 912, 170, 912, 170),
	array('Warsaw', 'Land', 'Yes', 6, 1050, 171, 1050, 172),
	array('Washington', 'Coast', 'Yes', 14, 442, 252, 442, 253),
	array('Western Mediterranean', 'Sea', 'No', 0, 940, 275, 941, 276),
	array('West Africa', 'Coast', 'No', 3, 820, 460, 821, 461),
	array('West Indian Ocean', 'Sea', 'No', 0, 1349, 705, 1349, 705),
	array('Windhoek', 'Coast', 'Yes', 4, 1025, 730, 1026, 730),
	array('Ubangi-Shari', 'Land', 'No', 3, 1064, 527, 1064, 528),
	array('Uruguay', 'Coast', 'No', 0, 554, 829, 555, 829),
	array('Yakutskaya', 'Land', 'No', 6, 1611, 91, 1612, 92),
	array('Yellow Sea', 'Sea', 'No', 0, 1714, 288, 1714, 288),
	array('Yemen', 'Coast', 'No', 7, 1215, 438, 1215, 439),
	array('Yorkshire', 'Coast', 'No', 2, 921, 156, 922, 156),
	array('Bulgaria (East Coast)', 'Coast', 'No', 0, 1094, 237, 1095, 237),
	array('Bulgaria (South Coast)', 'Coast', 'No', 0, 1080, 250, 1081, 250),
	array('Costa Rica (East Coast)', 'Coast', 'No', 0, 346, 491, 346, 492),
	array('Costa Rica (West Coast)', 'Coast', 'No', 0, 340, 497, 340, 498),
	array('Guatemala (North Coast)', 'Coast', 'No', 0, 314, 441, 315, 441),
	array('Guatemala (South Coast)', 'Coast', 'No', 0, 292, 459, 293, 460),
	array('Honduras (North Coast)', 'Coast', 'No', 0, 337, 452, 338, 453),
	array('Honduras (South Coast)', 'Coast', 'No', 0, 313, 465, 313, 465),
	array('Hyderabad (East Coast)', 'Coast', 'No', 0, 1479, 429, 1479, 429),
	array('Hyderabad (West Coast)', 'Coast', 'No', 0, 1424, 442, 1424, 442),
	array('Mexico (East Coast)', 'Coast', 'No', 13, 258, 407, 258, 407),
	array('Mexico (South Coast)', 'Coast', 'No', 13, 240, 437, 241, 437),
	array('Nicaragua (East Coast)', 'Coast', 'No', 0, 345, 469, 345, 469),
	array('Nicaragua (West Coast)', 'Coast', 'No', 0, 329, 481, 330, 482),
	array('Oaxaca (North Coast)', 'Coast', 'No', 0, 286, 433, 286, 433),
	array('Oaxaca (South Coast)', 'Coast', 'No', 0, 269, 443, 269, 443),
	array('Siam (East Coast)', 'Coast', 'No', 0, 1607, 470, 1607, 470),
	array('Siam (West Coast)', 'Coast', 'No', 0, 1590, 503, 1590, 504),
	array('Spain (North Coast)', 'Coast', 'No', 0, 892, 238, 892, 239),
	array('Spain (South Coast)', 'Coast', 'No', 0, 903, 273, 904, 274),
	array('St Petersburg (North Coast)', 'Coast', 'No', 6, 1155, 76, 1155, 76),
	array('St Petersburg (South Coast)', 'Coast', 'No', 6, 1089, 115, 1089, 115)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Abyssinia','Asmara','No','Yes'),
	array('Abyssinia','East Africa','No','Yes'),
	array('Abyssinia','Somaliland','No','Yes'),
	array('Abyssinia','Mogadishu','No','Yes'),
	array('Abyssinia','Sudan','No','Yes'),
	array('Accra','Bamako','No','Yes'),
	array('Accra','Gulf of Guinea','Yes','No'),
	array('Accra','Ivory Coast','Yes','Yes'),
	array('Accra','Dahomny','Yes','Yes'),
	array('Aden','Arabia','No','Yes'),
	array('Aden','Arabian Sea','Yes','No'),
	array('Aden','Oman','Yes','Yes'),
	array('Aden','Yemen','Yes','Yes'),
	array('Adriatic Sea','Albania','Yes','No'),
	array('Adriatic Sea','Apulia','Yes','No'),
	array('Adriatic Sea','Ionian Sea','Yes','No'),
	array('Adriatic Sea','Trieste','Yes','No'),
	array('Adriatic Sea','Venice','Yes','No'),
	array('Aegean Sea','Constantinople','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean','Yes','No'),
	array('Aegean Sea','Greece','Yes','No'),
	array('Aegean Sea','Ionian Sea','Yes','No'),
	array('Aegean Sea','Smyrna','Yes','No'),
	array('Aegean Sea','Bulgaria (South Coast)','Yes','No'),
	array('Afghanistan','Bengal','No','Yes'),
	array('Afghanistan','Bombay','No','Yes'),
	array('Afghanistan','Urumtsi','No','Yes'),
	array('Afghanistan','Persia','No','Yes'),
	array('Afghanistan','Samarkand','No','Yes'),
	array('Afghanistan','Turkestan','No','Yes'),
	array('Albania','Greece','Yes','Yes'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Albania','Serbia','No','Yes'),
	array('Albania','Trieste','Yes','Yes'),
	array('Amazon','Bogota','No','Yes'),
	array('Amazon','Bolivia','No','Yes'),
	array('Amazon','British Guiana','No','Yes'),
	array('Amazon','Pantanal','No','Yes'),
	array('Amazon','Para','No','Yes'),
	array('Amazon','Peru','No','Yes'),
	array('Amazon','Surinam','No','Yes'),
	array('Amazon','Venezuela','No','Yes'),
	array('Angola','Belgian Congo','Yes','Yes'),
	array('Angola','Rhodesia','No','Yes'),
	array('Angola','Skeleton coast','Yes','No'),
	array('Angola','Windhoek','Yes','Yes'),
	array('Ankara','Armenia','Yes','Yes'),
	array('Ankara','Black Sea','Yes','No'),
	array('Ankara','Constantinople','Yes','Yes'),
	array('Ankara','Smyrna','No','Yes'),
	array('Antananarivo','Mozambique channel','Yes','No'),
	array('Antananarivo','Seychelles','Yes','No'),
	array('Antananarivo','West Indian Ocean','Yes','No'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','Naples','Yes','Yes'),
	array('Apulia','Rome','No','Yes'),
	array('Apulia','Venice','Yes','Yes'),
	array('Arabia','Baghdad','Yes','Yes'),
	array('Arabia','Gulf of Persia','Yes','No'),
	array('Arabia','Mecca','No','Yes'),
	array('Arabia','Oman','Yes','Yes'),
	array('Arabia','Syria','No','Yes'),
	array('Arabia','Yemen','No','Yes'),
	array('Arabian Sea','Bay of Bengal','Yes','No'),
	array('Arabian Sea','Bombay','Yes','No'),
	array('Arabian Sea','Somaliland','Yes','No'),
	array('Arabian Sea','East Indian Ocean','Yes','No'),
	array('Arabian Sea','Gulf of Persia','Yes','No'),
	array('Arabian Sea','Madras','Yes','No'),
	array('Arabian Sea','Mogadishu','Yes','No'),
	array('Arabian Sea','Oman','Yes','No'),
	array('Arabian Sea','Persia','Yes','No'),
	array('Arabian Sea','Red Sea','Yes','No'),
	array('Arabian Sea','Seychelles','Yes','No'),
	array('Arabian Sea','West Indian Ocean','Yes','No'),
	array('Arabian Sea','Yemen','Yes','No'),
	array('Arabian Sea','Hyderabad (West Coast)','Yes','No'),
	array('Armenia','Astrakhan','No','Yes'),
	array('Armenia','Baghdad','No','Yes'),
	array('Armenia','Black Sea','Yes','No'),
	array('Armenia','Persia','No','Yes'),
	array('Armenia','Sevastopol','Yes','Yes'),
	array('Armenia','Smyrna','No','Yes'),
	array('Armenia','Syria','No','Yes'),
	array('Asmara','Somaliland','Yes','Yes'),
	array('Asmara','Red Sea','Yes','No'),
	array('Asmara','Sudan','Yes','Yes'),
	array('Astrakhan','Moscow','No','Yes'),
	array('Astrakhan','Persia','No','Yes'),
	array('Astrakhan','Samarkand','No','Yes'),
	array('Astrakhan','Sevastopol','No','Yes'),
	array('Astrakhan','Siberia','No','Yes'),
	array('Astrakhan','Turkestan','No','Yes'),
	array('Baghdad','Gulf of Persia','Yes','No'),
	array('Baghdad','Persia','Yes','Yes'),
	array('Baghdad','Syria','No','Yes'),
	array('Baltic Sea','Berlin','Yes','No'),
	array('Baltic Sea','Denmark','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Baltic Sea','Kiel','Yes','No'),
	array('Baltic Sea','Livonia','Yes','No'),
	array('Baltic Sea','Prussia','Yes','No'),
	array('Baltic Sea','Sweden','Yes','No'),
	array('Bamako','Chad','No','Yes'),
	array('Bamako','Ivory Coast','No','Yes'),
	array('Bamako','Dahomny','No','Yes'),
	array('Bamako','West Africa','No','Yes'),
	array('Barents Sea','Norway','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Barents Sea','St Petersburg (North Coast)','Yes','No'),
	array('Barranquilla','Bogota','No','Yes'),
	array('Barranquilla','Caribbean','Yes','No'),
	array('Barranquilla','Choco','No','Yes'),
	array('Barranquilla','Panama','Yes','Yes'),
	array('Barranquilla','Venezuela','Yes','Yes'),
	array('Bay of Bengal','Bengal','Yes','No'),
	array('Bay of Bengal','Burma','Yes','No'),
	array('Bay of Bengal','East Indian Ocean','Yes','No'),
	array('Bay of Bengal','Java','Yes','No'),
	array('Bay of Bengal','Gulf of Siam','Yes','No'),
	array('Bay of Bengal','Madras','Yes','No'),
	array('Bay of Bengal','Malaya','Yes','No'),
	array('Bay of Bengal','Sumatra','Yes','No'),
	array('Bay of Bengal','Hyderabad (East Coast)','Yes','No'),
	array('Bay of Bengal','Siam (West Coast)','Yes','No'),
	array('Bechuanaland','Capetown','No','Yes'),
	array('Bechuanaland','Namaqualand','No','Yes'),
	array('Bechuanaland','Mozambique','No','Yes'),
	array('Bechuanaland','Rhodesia','No','Yes'),
	array('Bechuanaland','Windhoek','No','Yes'),
	array('Belgian Congo','East Africa','No','Yes'),
	array('Belgian Congo','Dar es Salaam','No','Yes'),
	array('Belgian Congo','Duala','No','Yes'),
	array('Belgian Congo','Libreville','Yes','Yes'),
	array('Belgian Congo','Rhodesia','No','Yes'),
	array('Belgian Congo','Skeleton coast','Yes','No'),
	array('Belgian Congo','Sudan','No','Yes'),
	array('Belgian Congo','Ubangi-Shari','No','Yes'),
	array('Belgium','Burgundy','No','Yes'),
	array('Belgium','English Channel','Yes','No'),
	array('Belgium','Holland','Yes','Yes'),
	array('Belgium','North Sea','Yes','No'),
	array('Belgium','Picardy','Yes','Yes'),
	array('Belgium','Ruhr','No','Yes'),
	array('Bengal','Bombay','No','Yes'),
	array('Bengal','Burma','Yes','Yes'),
	array('Bengal','Chungking','No','Yes'),
	array('Bengal','Urumtsi','No','Yes'),
	array('Bengal','Hyderabad','No','Yes'),
	array('Bengal','Hyderabad (East Coast)','Yes','No'),
	array('Berlin','Kiel','Yes','Yes'),
	array('Berlin','Munich','No','Yes'),
	array('Berlin','Prussia','Yes','Yes'),
	array('Berlin','Silesia','No','Yes'),
	array('Black Sea','Constantinople','Yes','No'),
	array('Black Sea','Rumania','Yes','No'),
	array('Black Sea','Sevastopol','Yes','No'),
	array('Black Sea','Bulgaria (East Coast)','Yes','No'),
	array('Bogota','Choco','Yes','Yes'),
	array('Bogota','Ecuador','Yes','Yes'),
	array('Bogota','Gulf of Panama','Yes','No'),
	array('Bogota','Peru','No','Yes'),
	array('Bogota','Venezuela','No','Yes'),
	array('Bohemia','Galicia','No','Yes'),
	array('Bohemia','Munich','No','Yes'),
	array('Bohemia','Silesia','No','Yes'),
	array('Bohemia','Tyrolia','No','Yes'),
	array('Bohemia','Vienna','No','Yes'),
	array('Bolivia','Chile','No','Yes'),
	array('Bolivia','Pampas','No','Yes'),
	array('Bolivia','Pantanal','No','Yes'),
	array('Bolivia','Paraguay','No','Yes'),
	array('Bolivia','Peru','No','Yes'),
	array('Bombay','Hyderabad','No','Yes'),
	array('Bombay','Persia','Yes','Yes'),
	array('Bombay','Hyderabad (West Coast)','Yes','No'),
	array('Brest','English Channel','Yes','No'),
	array('Brest','Gascony','Yes','Yes'),
	array('Brest','Mid-Atlantic Ocean','Yes','No'),
	array('Brest','Paris','No','Yes'),
	array('Brest','Picardy','Yes','Yes'),
	array('East Africa','Dar es Salaam','Yes','Yes'),
	array('East Africa','Mogadishu','Yes','Yes'),
	array('East Africa','Seychelles','Yes','Yes'),
	array('East Africa','Sudan','No','Yes'),
	array('British Guiana','Caribbean','Yes','No'),
	array('British Guiana','Surinam','Yes','Yes'),
	array('British Guiana','Venezuela','Yes','Yes'),
	array('Somaliland','Mogadishu','Yes','Yes'),
	array('Somaliland','Red Sea','Yes','No'),
	array('Budapest','Galicia','No','Yes'),
	array('Budapest','Rumania','No','Yes'),
	array('Budapest','Serbia','No','Yes'),
	array('Budapest','Trieste','No','Yes'),
	array('Budapest','Vienna','No','Yes'),
	array('Buenos Aires','Cordoba','No','Yes'),
	array('Buenos Aires','Pampas','No','Yes'),
	array('Buenos Aires','Patagonia','Yes','Yes'),
	array('Buenos Aires','Rio de la Plata','Yes','No'),
	array('Buenos Aires','South Atlantic Ocean','Yes','No'),
	array('Buenos Aires','Uruguay','Yes','Yes'),
	array('Bulgaria','Constantinople','No','Yes'),
	array('Bulgaria','Greece','No','Yes'),
	array('Bulgaria','Rumania','No','Yes'),
	array('Bulgaria','Serbia','No','Yes'),
	array('Burgundy','Gascony','No','Yes'),
	array('Burgundy','Marseilles','No','Yes'),
	array('Burgundy','Munich','No','Yes'),
	array('Burgundy','Paris','No','Yes'),
	array('Burgundy','Picardy','No','Yes'),
	array('Burgundy','Ruhr','No','Yes'),
	array('Burma','Chungking','No','Yes'),
	array('Burma','Hanoi','No','Yes'),
	array('Burma','Kwangtung','No','Yes'),
	array('Burma','Siam','No','Yes'),
	array('Burma','Siam (West Coast)','Yes','No'),
	array('Cairo','Cyrenacia','Yes','Yes'),
	array('Cairo','Eastern Mediterranean','Yes','No'),
	array('Cairo','Mecca','Yes','Yes'),
	array('Cairo','Red Sea','Yes','No'),
	array('Cairo','Sudan','Yes','Yes'),
	array('Cairo','Syria','Yes','Yes'),
	array('Cambodia','Hanoi','Yes','Yes'),
	array('Cambodia','Gulf of Siam','Yes','No'),
	array('Cambodia','Siam','No','Yes'),
	array('Cambodia','South China Sea','Yes','No'),
	array('Cambodia','Siam (East Coast)','Yes','No'),
	array('Capetown','Namaqualand','Yes','Yes'),
	array('Capetown','Mozambique','Yes','Yes'),
	array('Capetown','Mozambique channel','Yes','No'),
	array('Capetown','Skeleton coast','Yes','No'),
	array('Caribbean','Cuba','Yes','No'),
	array('Caribbean','Equatorial Atlantic Ocean','Yes','No'),
	array('Caribbean','Gulf of Honduras','Yes','No'),
	array('Caribbean','Haiti','Yes','No'),
	array('Caribbean','Panama','Yes','No'),
	array('Caribbean','Sargasso Sea','Yes','No'),
	array('Caribbean','Surinam','Yes','No'),
	array('Caribbean','Venezuela','Yes','No'),
	array('Caribbean','Costa Rica (East Coast)','Yes','No'),
	array('Caribbean','Honduras (North Coast)','Yes','No'),
	array('Caribbean','Nicaragua (East Coast)','Yes','No'),
	array('Celebes','Borneo','Yes','Yes'),
	array('Celebes','Phillipine Sea','Yes','No'),
	array('Celebes','Timor Sea','Yes','No'),
	array('Chad','Duala','No','Yes'),
	array('Chad','Lagos','No','Yes'),
	array('Chad','Dahomny','No','Yes'),
	array('Chad','Sudan','No','Yes'),
	array('Chad','Ubangi-Shari','No','Yes'),
	array('Chile','Cordoba','No','Yes'),
	array('Chile','Nazca Ridge','Yes','No'),
	array('Chile','Pampas','No','Yes'),
	array('Chile','Patagonia','No','Yes'),
	array('Chile','Peru','Yes','Yes'),
	array('Chile','Santa Cruz','Yes','Yes'),
	array('Chile','South Atlantic Ocean','Yes','No'),
	array('Chile','South Pacific Ocean','Yes','No'),
	array('Choco','Gulf of Panama','Yes','No'),
	array('Choco','Panama','Yes','Yes'),
	array('Chugoku','Nagasaki','Yes','Yes'),
	array('Chugoku','Sea of Japan','Yes','No'),
	array('Chugoku','Tohoku','Yes','Yes'),
	array('Chugoku','Tokyo','Yes','Yes'),
	array('Chungking','Urumtsi','No','Yes'),
	array('Chungking','Gobi Desert','No','Yes'),
	array('Chungking','Kwangtung','No','Yes'),
	array('Chungking','Peking','No','Yes'),
	array('Chungking','Shanghai','No','Yes'),
	array('Clyde','Edinburgh','Yes','Yes'),
	array('Clyde','Liverpool','Yes','Yes'),
	array('Clyde','North Atlantic Ocean','Yes','No'),
	array('Clyde','Norwegian Sea','Yes','No'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Bulgaria (East Coast)','Yes','No'),
	array('Constantinople','Bulgaria (South Coast)','Yes','No'),
	array('Cordoba','Pampas','No','Yes'),
	array('Cordoba','Patagonia','No','Yes'),
	array('Costa Rica','Nicaragua','No','Yes'),
	array('Costa Rica','Panama','No','Yes'),
	array('Cuba','Gulf of Honduras','Yes','No'),
	array('Cuba','Gulf of Mexico','Yes','No'),
	array('Cuba','Haiti','Yes','Yes'),
	array('Cuba','Miami','Yes','Yes'),
	array('Cuba','Sargasso Sea','Yes','No'),
	array('Cyrenacia','Eastern Mediterranean','Yes','No'),
	array('Cyrenacia','Ionian Sea','Yes','No'),
	array('Cyrenacia','Tripoli','Yes','Yes'),
	array('Dar es Salaam','Mozambique','Yes','Yes'),
	array('Dar es Salaam','Rhodesia','No','Yes'),
	array('Dar es Salaam','Seychelles','Yes','No'),
	array('Denmark','Helgoland Bight','Yes','No'),
	array('Denmark','Kiel','Yes','Yes'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Denmark','Sweden','Yes','Yes'),
	array('Urumtsi','Gobi Desert','No','Yes'),
	array('Urumtsi','Mongolia','No','Yes'),
	array('Urumtsi','Turkestan','No','Yes'),
	array('Duala','Gulf of Guinea','Yes','No'),
	array('Duala','Lagos','Yes','Yes'),
	array('Duala','Libreville','Yes','Yes'),
	array('Duala','Ubangi-Shari','No','Yes'),
	array('Dutch New Guinea','Friedrich-Wilhelmshafen','Yes','Yes'),
	array('Dutch New Guinea','Micronesia','Yes','No'),
	array('Dutch New Guinea','Papua','Yes','Yes'),
	array('Dutch New Guinea','Phillipine Sea','Yes','No'),
	array('Dutch New Guinea','Timor Sea','Yes','No'),
	array('Eastern Mediterranean','Ionian Sea','Yes','No'),
	array('Eastern Mediterranean','Smyrna','Yes','No'),
	array('Eastern Mediterranean','Syria','Yes','No'),
	array('East China Sea','Manila','Yes','No'),
	array('East China Sea','Mariana Trench','Yes','No'),
	array('East China Sea','Nagasaki','Yes','No'),
	array('East China Sea','Phillipine Sea','Yes','No'),
	array('East China Sea','Sea of Japan','Yes','No'),
	array('East China Sea','Seoul','Yes','No'),
	array('East China Sea','Shanghai','Yes','No'),
	array('East China Sea','South China Sea','Yes','No'),
	array('East China Sea','Yellow Sea','Yes','No'),
	array('East Indian Ocean','Java','Yes','No'),
	array('East Indian Ocean','Melbourne','Yes','No'),
	array('East Indian Ocean','Polynesia','Yes','No'),
	array('East Indian Ocean','Timor Sea','Yes','No'),
	array('East Indian Ocean','West Indian Ocean','Yes','No'),
	array('East Pacific Ocean','Gulf of Alaska','Yes','No'),
	array('East Pacific Ocean','Honolulu','Yes','No'),
	array('East Pacific Ocean','Los Angeles','Yes','No'),
	array('East Pacific Ocean','Micronesia','Yes','No'),
	array('East Pacific Ocean','North Pacific Ocean','Yes','No'),
	array('East Pacific Ocean','Polynesia','Yes','No'),
	array('East Pacific Ocean','Sonora','Yes','No'),
	array('East Pacific Ocean','South Pacific Ocean','Yes','No'),
	array('Ecuador','Gulf of Panama','Yes','No'),
	array('Ecuador','Nazca Ridge','Yes','No'),
	array('Ecuador','Peru','Yes','Yes'),
	array('Edinburgh','Liverpool','No','Yes'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edinburgh','Yorkshire','Yes','Yes'),
	array('English Channel','Irish Sea','Yes','No'),
	array('English Channel','London','Yes','No'),
	array('English Channel','Mid-Atlantic Ocean','Yes','No'),
	array('English Channel','North Sea','Yes','No'),
	array('English Channel','Picardy','Yes','No'),
	array('English Channel','Wales','Yes','No'),
	array('Equatorial Atlantic Ocean','Fortaleza','Yes','No'),
	array('Equatorial Atlantic Ocean','French Guiana','Yes','No'),
	array('Equatorial Atlantic Ocean','Gulf of Guinea','Yes','No'),
	array('Equatorial Atlantic Ocean','Liberia','Yes','No'),
	array('Equatorial Atlantic Ocean','Mid-Atlantic Ocean','Yes','No'),
	array('Equatorial Atlantic Ocean','Para','Yes','No'),
	array('Equatorial Atlantic Ocean','Recife','Yes','No'),
	array('Equatorial Atlantic Ocean','Rio de Janeiro','Yes','No'),
	array('Equatorial Atlantic Ocean','Rio de la Plata','Yes','No'),
	array('Equatorial Atlantic Ocean','Sargasso Sea','Yes','No'),
	array('Equatorial Atlantic Ocean','Sierra Leone','Yes','No'),
	array('Equatorial Atlantic Ocean','Skeleton coast','Yes','No'),
	array('Equatorial Atlantic Ocean','South Atlantic Ocean','Yes','No'),
	array('Equatorial Atlantic Ocean','Spainish Sahara','Yes','No'),
	array('Equatorial Atlantic Ocean','Surinam','Yes','No'),
	array('Equatorial Atlantic Ocean','West Africa','Yes','No'),
	array('Fairbanks','Gulf of Alaska','Yes','No'),
	array('Fairbanks','North Pacific Ocean','Yes','No'),
	array('Fairbanks','North-West Territories','No','Yes'),
	array('Fairbanks','Vancouver','Yes','Yes'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Finland','Norway','No','Yes'),
	array('Finland','St Petersburg','No','Yes'),
	array('Finland','Sweden','Yes','Yes'),
	array('Finland','St Petersburg (South Coast)','Yes','No'),
	array('Fortaleza','Pantanal','No','Yes'),
	array('Fortaleza','Para','Yes','Yes'),
	array('Fortaleza','Recife','Yes','Yes'),
	array('French Guiana','Para','Yes','Yes'),
	array('French Guiana','Surinam','Yes','Yes'),
	array('Friedrich-Wilhelmshafen','Micronesia','Yes','No'),
	array('Friedrich-Wilhelmshafen','Papua','Yes','Yes'),
	array('Friedrich-Wilhelmshafen','Polynesia','Yes','No'),
	array('Galicia','Rumania','No','Yes'),
	array('Galicia','Silesia','No','Yes'),
	array('Galicia','Ukraine','No','Yes'),
	array('Galicia','Vienna','No','Yes'),
	array('Galicia','Warsaw','No','Yes'),
	array('Gascony','Marseilles','No','Yes'),
	array('Gascony','Mid-Atlantic Ocean','Yes','No'),
	array('Gascony','Paris','No','Yes'),
	array('Gascony','Spain','No','Yes'),
	array('Gascony','Spain (North Coast)','Yes','No'),
	array('Gobi Desert','Manchuria','No','Yes'),
	array('Gobi Desert','Mongolia','No','Yes'),
	array('Gobi Desert','Peking','No','Yes'),
	array('Namaqualand','Skeleton coast','Yes','No'),
	array('Namaqualand','Windhoek','Yes','Yes'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greece','Serbia','No','Yes'),
	array('Greece','Bulgaria (South Coast)','Yes','No'),
	array('Guadalajara','Mexico','No','Yes'),
	array('Guadalajara','Rio Grande','No','Yes'),
	array('Guadalajara','Sonora','Yes','Yes'),
	array('Guadalajara','South Pacific Ocean','Yes','No'),
	array('Guadalajara','Mexico (South Coast)','Yes','No'),
	array('Guatemala','Honduras','No','Yes'),
	array('Guatemala','Merida','No','Yes'),
	array('Guatemala','Oaxaca','No','Yes'),
	array('Gulf of Alaska','Los Angeles','Yes','No'),
	array('Gulf of Alaska','North Pacific Ocean','Yes','No'),
	array('Gulf of Alaska','Pacific Northwest','Yes','No'),
	array('Gulf of Alaska','Vancouver','Yes','No'),
	array('Gulf of Bothnia','Livonia','Yes','No'),
	array('Gulf of Bothnia','Sweden','Yes','No'),
	array('Gulf of Bothnia','St Petersburg (South Coast)','Yes','No'),
	array('Gulf of Guinea','Ivory Coast','Yes','No'),
	array('Gulf of Guinea','Lagos','Yes','No'),
	array('Gulf of Guinea','Liberia','Yes','No'),
	array('Gulf of Guinea','Libreville','Yes','No'),
	array('Gulf of Guinea','Skeleton coast','Yes','No'),
	array('Gulf of Guinea','Dahomny','Yes','No'),
	array('Gulf of Honduras','Gulf of Mexico','Yes','No'),
	array('Gulf of Honduras','Merida','Yes','No'),
	array('Gulf of Honduras','Guatemala (North Coast)','Yes','No'),
	array('Gulf of Honduras','Honduras (North Coast)','Yes','No'),
	array('Gulf of Lyon','Marseilles','Yes','No'),
	array('Gulf of Lyon','Piedmont','Yes','No'),
	array('Gulf of Lyon','Tuscany','Yes','No'),
	array('Gulf of Lyon','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lyon','Western Mediterranean','Yes','No'),
	array('Gulf of Lyon','Spain (South Coast)','Yes','No'),
	array('Gulf of Mexico','Merida','Yes','No'),
	array('Gulf of Mexico','Miami','Yes','No'),
	array('Gulf of Mexico','Rio Grande','Yes','No'),
	array('Gulf of Mexico','Texas','Yes','No'),
	array('Gulf of Mexico','Mexico (East Coast)','Yes','No'),
	array('Gulf of Mexico','Oaxaca (North Coast)','Yes','No'),
	array('Gulf of Panama','Nazca Ridge','Yes','No'),
	array('Gulf of Panama','Panama','Yes','No'),
	array('Gulf of Panama','South Pacific Ocean','Yes','No'),
	array('Gulf of Panama','Costa Rica (West Coast)','Yes','No'),
	array('Gulf of Persia','Oman','Yes','No'),
	array('Gulf of Persia','Persia','Yes','No'),
	array('Gulf of Tehuantepec','South Pacific Ocean','Yes','No'),
	array('Gulf of Tehuantepec','Guatemala (South Coast)','Yes','No'),
	array('Gulf of Tehuantepec','Honduras (South Coast)','Yes','No'),
	array('Gulf of Tehuantepec','Mexico (South Coast)','Yes','No'),
	array('Gulf of Tehuantepec','Oaxaca (South Coast)','Yes','No'),
	array('Hamgyong','Manchuria','No','Yes'),
	array('Hamgyong','Sea of Japan','Yes','No'),
	array('Hamgyong','Seoul','Yes','Yes'),
	array('Hamgyong','Vladivostok','Yes','Yes'),
	array('Hanoi','Kwangtung','Yes','Yes'),
	array('Hanoi','Siam','No','Yes'),
	array('Hanoi','South China Sea','Yes','No'),
	array('Helgoland Bight','Holland','Yes','No'),
	array('Helgoland Bight','Kiel','Yes','No'),
	array('Helgoland Bight','North Sea','Yes','No'),
	array('Haiti','Sargasso Sea','Yes','No'),
	array('Holland','Kiel','Yes','Yes'),
	array('Holland','North Sea','Yes','No'),
	array('Holland','Ruhr','No','Yes'),
	array('Honduras','Nicaragua','No','Yes'),
	array('Honolulu','Micronesia','Yes','No'),
	array('Honolulu','North Pacific Ocean','Yes','No'),
	array('Hyderabad','Madras','No','Yes'),
	array('Ionian Sea','Naples','Yes','No'),
	array('Ionian Sea','Tripoli','Yes','No'),
	array('Ionian Sea','Tunis','Yes','No'),
	array('Ionian Sea','Tyrrhenian Sea','Yes','No'),
	array('Irish Sea','Liverpool','Yes','No'),
	array('Irish Sea','Mid-Atlantic Ocean','Yes','No'),
	array('Irish Sea','North Atlantic Ocean','Yes','No'),
	array('Irish Sea','Wales','Yes','No'),
	array('Irkutsk','Manchuria','No','Yes'),
	array('Irkutsk','Mongolia','No','Yes'),
	array('Irkutsk','Siberia','No','Yes'),
	array('Irkutsk','Vladivostok','No','Yes'),
	array('Irkutsk','Yakutskaya','No','Yes'),
	array('Ivory Coast','Liberia','Yes','Yes'),
	array('Ivory Coast','West Africa','No','Yes'),
	array('Java','Gulf of Siam','Yes','No'),
	array('Java','Sumatra','Yes','Yes'),
	array('Java','Timor Sea','Yes','No'),
	array('Gulf of Siam','Borneo','Yes','No'),
	array('Gulf of Siam','Malaya','Yes','No'),
	array('Gulf of Siam','South China Sea','Yes','No'),
	array('Gulf of Siam','Sumatra','Yes','No'),
	array('Gulf of Siam','Timor Sea','Yes','No'),
	array('Gulf of Siam','Siam (East Coast)','Yes','No'),
	array('Borneo','Phillipine Sea','Yes','No'),
	array('Borneo','Sarawak','Yes','Yes'),
	array('Borneo','South China Sea','Yes','No'),
	array('Borneo','Timor Sea','Yes','No'),
	array('Kamchatka','North Pacific Ocean','Yes','No'),
	array('Kamchatka','Sea of Okhotsk','Yes','No'),
	array('Kamchatka','Vladivostok','Yes','Yes'),
	array('Kamchatka','Yakutskaya','No','Yes'),
	array('Kiel','Munich','No','Yes'),
	array('Kiel','Ruhr','No','Yes'),
	array('Kwangtung','Shanghai','Yes','Yes'),
	array('Kwangtung','South China Sea','Yes','No'),
	array('Lagos','Dahomny','Yes','Yes'),
	array('Liberia','Sierra Leone','Yes','Yes'),
	array('Liberia','West Africa','No','Yes'),
	array('Libreville','Skeleton coast','Yes','No'),
	array('Liverpool','North Atlantic Ocean','Yes','No'),
	array('Liverpool','Wales','Yes','Yes'),
	array('Liverpool','Yorkshire','No','Yes'),
	array('Livonia','Moscow','No','Yes'),
	array('Livonia','Prussia','Yes','Yes'),
	array('Livonia','St Petersburg','No','Yes'),
	array('Livonia','Warsaw','No','Yes'),
	array('Livonia','St Petersburg (South Coast)','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('London','Wales','Yes','Yes'),
	array('London','Yorkshire','Yes','Yes'),
	array('Los Angeles','Midwest','No','Yes'),
	array('Los Angeles','Pacific Northwest','Yes','Yes'),
	array('Los Angeles','Sonora','Yes','Yes'),
	array('Los Angeles','Texas','No','Yes'),
	array('Madras','Hyderabad (East Coast)','Yes','No'),
	array('Madras','Hyderabad (West Coast)','Yes','No'),
	array('Malaya','Siam','No','Yes'),
	array('Malaya','Siam (East Coast)','Yes','No'),
	array('Malaya','Siam (West Coast)','Yes','No'),
	array('Manchuria','Mongolia','No','Yes'),
	array('Manchuria','Peking','Yes','Yes'),
	array('Manchuria','Seoul','Yes','Yes'),
	array('Manchuria','Vladivostok','No','Yes'),
	array('Manchuria','Yellow Sea','Yes','No'),
	array('Manila','Phillipine Sea','Yes','No'),
	array('Manila','Sarawak','Yes','Yes'),
	array('Manila','South China Sea','Yes','No'),
	array('Mariana Trench','Micronesia','Yes','No'),
	array('Mariana Trench','Nagasaki','Yes','No'),
	array('Mariana Trench','North Pacific Ocean','Yes','No'),
	array('Mariana Trench','Phillipine Sea','Yes','No'),
	array('Mariana Trench','Sapporo','Yes','No'),
	array('Mariana Trench','Tohoku','Yes','No'),
	array('Mariana Trench','Tokyo','Yes','No'),
	array('Marseilles','Piedmont','Yes','Yes'),
	array('Marseilles','Spain','No','Yes'),
	array('Marseilles','Spain (South Coast)','Yes','No'),
	array('Mecca','Red Sea','Yes','No'),
	array('Mecca','Syria','No','Yes'),
	array('Mecca','Yemen','Yes','Yes'),
	array('Melbourne','Polynesia','Yes','No'),
	array('Melbourne','Timor Sea','Yes','No'),
	array('Merida','Oaxaca','No','Yes'),
	array('Merida','Guatemala (North Coast)','Yes','No'),
	array('Merida','Oaxaca (North Coast)','Yes','No'),
	array('Mexico','Oaxaca','No','Yes'),
	array('Mexico','Rio Grande','No','Yes'),
	array('Miami','Midwest','No','Yes'),
	array('Miami','Sargasso Sea','Yes','No'),
	array('Miami','Texas','Yes','Yes'),
	array('Miami','Washington','Yes','Yes'),
	array('Micronesia','North Pacific Ocean','Yes','No'),
	array('Micronesia','Phillipine Sea','Yes','No'),
	array('Micronesia','Polynesia','Yes','No'),
	array('Mid-Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','North Africa','Yes','No'),
	array('Mid-Atlantic Ocean','Portugal','Yes','No'),
	array('Mid-Atlantic Ocean','Sargasso Sea','Yes','No'),
	array('Mid-Atlantic Ocean','Spainish Sahara','Yes','No'),
	array('Mid-Atlantic Ocean','Western Mediterranean','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (North Coast)','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (South Coast)','Yes','No'),
	array('Midwest','Ontario','No','Yes'),
	array('Midwest','Pacific Northwest','No','Yes'),
	array('Midwest','Saskatchewan','No','Yes'),
	array('Midwest','Texas','No','Yes'),
	array('Midwest','Washington','No','Yes'),
	array('Mogadishu','Seychelles','Yes','No'),
	array('Mongolia','Siberia','No','Yes'),
	array('Mongolia','Turkestan','No','Yes'),
	array('Moscow','Sevastopol','No','Yes'),
	array('Moscow','Siberia','No','Yes'),
	array('Moscow','St Petersburg','No','Yes'),
	array('Moscow','Ukraine','No','Yes'),
	array('Moscow','Warsaw','No','Yes'),
	array('Mozambique','Mozambique channel','Yes','No'),
	array('Mozambique','Rhodesia','No','Yes'),
	array('Mozambique','Seychelles','Yes','No'),
	array('Mozambique channel','Seychelles','Yes','No'),
	array('Mozambique channel','Skeleton coast','Yes','No'),
	array('Mozambique channel','South Atlantic Ocean','Yes','No'),
	array('Mozambique channel','West Indian Ocean','Yes','No'),
	array('Munich','Ruhr','No','Yes'),
	array('Munich','Silesia','No','Yes'),
	array('Munich','Tyrolia','No','Yes'),
	array('Nagasaki','Sea of Japan','Yes','No'),
	array('Nagasaki','Tokyo','Yes','Yes'),
	array('Naples','Rome','Yes','Yes'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Nazca Ridge','Peru','Yes','No'),
	array('Nazca Ridge','South Pacific Ocean','Yes','No'),
	array('New England','North Atlantic Ocean','Yes','No'),
	array('New England','Ontario','No','Yes'),
	array('New England','Quebec','Yes','Yes'),
	array('New England','Washington','Yes','Yes'),
	array('North Atlantic Ocean','North-West Territories','Yes','No'),
	array('North Atlantic Ocean','Norwegian Sea','Yes','No'),
	array('North Atlantic Ocean','Quebec','Yes','No'),
	array('North Atlantic Ocean','Sargasso Sea','Yes','No'),
	array('North Atlantic Ocean','Washington','Yes','No'),
	array('North Africa','Spainish Sahara','Yes','Yes'),
	array('North Africa','Tunis','Yes','Yes'),
	array('North Africa','Western Mediterranean','Yes','No'),
	array('North Pacific Ocean','Sapporo','Yes','No'),
	array('North Pacific Ocean','Sea of Okhotsk','Yes','No'),
	array('North Sea','Norway','Yes','No'),
	array('North Sea','Norwegian Sea','Yes','No'),
	array('North Sea','Skagerrak','Yes','No'),
	array('North Sea','Yorkshire','Yes','No'),
	array('North-West Territories','Quebec','Yes','Yes'),
	array('North-West Territories','Saskatchewan','No','Yes'),
	array('North-West Territories','Vancouver','No','Yes'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','Skagerrak','Yes','No'),
	array('Norway','St Petersburg','No','Yes'),
	array('Norway','Sweden','Yes','Yes'),
	array('Norway','St Petersburg (North Coast)','Yes','No'),
	array('Ontario','Quebec','No','Yes'),
	array('Ontario','Saskatchewan','No','Yes'),
	array('Ontario','Washington','No','Yes'),
	array('Pacific Northwest','Saskatchewan','No','Yes'),
	array('Pacific Northwest','Vancouver','Yes','Yes'),
	array('Pampas','Paraguay','No','Yes'),
	array('Pampas','Santa Catarina','No','Yes'),
	array('Pampas','Uruguay','No','Yes'),
	array('Panama','Costa Rica (East Coast)','Yes','No'),
	array('Panama','Costa Rica (West Coast)','Yes','No'),
	array('Pantanal','Para','No','Yes'),
	array('Pantanal','Paraguay','No','Yes'),
	array('Pantanal','Recife','No','Yes'),
	array('Pantanal','Rio de Janeiro','No','Yes'),
	array('Papua','Polynesia','Yes','No'),
	array('Papua','Timor Sea','Yes','No'),
	array('Para','Surinam','No','Yes'),
	array('Paraguay','Rio de Janeiro','No','Yes'),
	array('Paraguay','Santa Catarina','No','Yes'),
	array('Paris','Picardy','No','Yes'),
	array('Patagonia','Santa Cruz','Yes','Yes'),
	array('Patagonia','South Atlantic Ocean','Yes','No'),
	array('Peking','Shanghai','Yes','Yes'),
	array('Peking','Yellow Sea','Yes','No'),
	array('Persia','Samarkand','No','Yes'),
	array('Phillipine Sea','Sarawak','Yes','No'),
	array('Phillipine Sea','Timor Sea','Yes','No'),
	array('Piedmont','Tuscany','Yes','Yes'),
	array('Piedmont','Tyrolia','No','Yes'),
	array('Piedmont','Venice','No','Yes'),
	array('Polynesia','South Pacific Ocean','Yes','No'),
	array('Polynesia','Timor Sea','Yes','No'),
	array('Portugal','Spain','No','Yes'),
	array('Portugal','Spain (North Coast)','Yes','No'),
	array('Portugal','Spain (South Coast)','Yes','No'),
	array('Prussia','Silesia','No','Yes'),
	array('Prussia','Warsaw','No','Yes'),
	array('Quebec','Saskatchewan','No','Yes'),
	array('Recife','Rio de Janeiro','Yes','Yes'),
	array('Red Sea','Sudan','Yes','No'),
	array('Red Sea','Yemen','Yes','No'),
	array('Rhodesia','Windhoek','No','Yes'),
	array('Rio de Janeiro','Rio de la Plata','Yes','No'),
	array('Rio de Janeiro','Santa Catarina','Yes','Yes'),
	array('Rio de la Plata','Santa Catarina','Yes','No'),
	array('Rio de la Plata','South Atlantic Ocean','Yes','No'),
	array('Rio de la Plata','Uruguay','Yes','No'),
	array('Rio Grande','Sonora','No','Yes'),
	array('Rio Grande','Texas','Yes','Yes'),
	array('Rio Grande','Mexico (East Coast)','Yes','No'),
	array('Santa Cruz','South Atlantic Ocean','Yes','No'),
	array('Rumania','Serbia','No','Yes'),
	array('Rumania','Sevastopol','Yes','Yes'),
	array('Rumania','Ukraine','No','Yes'),
	array('Rumania','Bulgaria (East Coast)','Yes','No'),
	array('Rome','Tuscany','Yes','Yes'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Rome','Venice','No','Yes'),
	array('Samarkand','Turkestan','No','Yes'),
	array('Santa Catarina','Uruguay','Yes','Yes'),
	array('Sapporo','Sea of Japan','Yes','No'),
	array('Sapporo','Sea of Okhotsk','Yes','No'),
	array('Sapporo','Tohoku','Yes','Yes'),
	array('Sarawak','South China Sea','Yes','No'),
	array('Sargasso Sea','Washington','Yes','No'),
	array('Saskatchewan','Vancouver','No','Yes'),
	array('Sea of Japan','Sea of Okhotsk','Yes','No'),
	array('Sea of Japan','Seoul','Yes','No'),
	array('Sea of Japan','Tohoku','Yes','No'),
	array('Sea of Japan','Vladivostok','Yes','No'),
	array('Sea of Okhotsk','Vladivostok','Yes','No'),
	array('Seoul','Yellow Sea','Yes','No'),
	array('Serbia','Trieste','No','Yes'),
	array('Sevastopol','Ukraine','No','Yes'),
	array('Seychelles','West Indian Ocean','Yes','No'),
	array('Shanghai','South China Sea','Yes','No'),
	array('Shanghai','Yellow Sea','Yes','No'),
	array('Siberia','St Petersburg','No','Yes'),
	array('Siberia','Turkestan','No','Yes'),
	array('Siberia','Yakutskaya','No','Yes'),
	array('Sierra Leone','West Africa','Yes','Yes'),
	array('Silesia','Warsaw','No','Yes'),
	array('Skagerrak','Sweden','Yes','No'),
	array('Skeleton coast','South Atlantic Ocean','Yes','No'),
	array('Skeleton coast','Windhoek','Yes','No'),
	array('Smyrna','Syria','Yes','Yes'),
	array('Sonora','South Pacific Ocean','Yes','No'),
	array('Sonora','Texas','No','Yes'),
	array('South Atlantic Ocean','South Pacific Ocean','Yes','No'),
	array('South Atlantic Ocean','West Indian Ocean','Yes','No'),
	array('South Pacific Ocean','Costa Rica (West Coast)','Yes','No'),
	array('South Pacific Ocean','Honduras (South Coast)','Yes','No'),
	array('South Pacific Ocean','Mexico (South Coast)','Yes','No'),
	array('South Pacific Ocean','Nicaragua (West Coast)','Yes','No'),
	array('Spainish Sahara','West Africa','Yes','Yes'),
	array('Sudan','Ubangi-Shari','No','Yes'),
	array('Tohoku','Tokyo','Yes','Yes'),
	array('Trieste','Tyrolia','No','Yes'),
	array('Trieste','Venice','Yes','Yes'),
	array('Trieste','Vienna','No','Yes'),
	array('Tripoli','Tunis','Yes','Yes'),
	array('Tunis','Tyrrhenian Sea','Yes','No'),
	array('Tunis','Western Mediterranean','Yes','No'),
	array('Tuscany','Tyrrhenian Sea','Yes','No'),
	array('Tuscany','Venice','No','Yes'),
	array('Tyrolia','Venice','No','Yes'),
	array('Tyrolia','Vienna','No','Yes'),
	array('Tyrrhenian Sea','Western Mediterranean','Yes','No'),
	array('Ukraine','Warsaw','No','Yes'),
	array('Vladivostok','Yakutskaya','No','Yes'),
	array('Wales','Yorkshire','No','Yes'),
	array('Western Mediterranean','Spain (South Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool

// Just create the database as usual:
InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

// Copy the smallmap-sample to the cache-directory to avoid a screwed variantpage (there is no smallmap available)
if (!file_exists('variants/'.$this->name.'/cache/sampleMap.png'))
	copy ('variants/'.$this->name.'/resources/sampleMap.png','variants/'.$this->name.'/cache/sampleMap.png');

?>