<?php
// This is file installs the map data for the FirstCrusade variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Iceland', 'Coast', 'No', 0, 380, 115, 157, 52),
	array('Edinburgh', 'Coast', 'Yes', 0, 398, 480, 187, 167),
	array('Ireland', 'Coast', 'Yes', 0, 305, 533, 138, 189),
	array('Oxfordshire', 'Coast', 'No', 2, 407, 550, 174, 212),
	array('York', 'Coast', 'Yes', 2, 431, 513, 187, 218),
	array('Wales', 'Coast', 'No', 0, 367, 569, 158, 218),
	array('Canterbury', 'Coast', 'Yes', 2, 332, 631, 142, 246),
	array('London', 'Coast', 'Yes', 2, 463, 595, 177, 239),
	array('Norway', 'Coast', 'Yes', 0, 750, 273, 326, 99),
	array('Finnmark', 'Coast', 'No', 0, 841, 131, 408, 39),
	array('Finland', 'Coast', 'No', 0, 930, 320, 392, 125),
	array('Sweden', 'Coast', 'Yes', 0, 762, 370, 318, 163),
	array('Novgorod', 'Coast', 'Yes', 6, 1089, 300, 458, 126),
	array('Novgorod (South Coast)', 'Coast', 'No', 6, 990, 430, 420, 147),
	array('Novgorod (North Coast)', 'Coast', 'No', 6, 1131, 127, 481, 46),
	array('Mordvinia', 'Land', 'No', 0, 1415, 412, 603, 165),
	array('Smolensk', 'Land', 'Yes', 6, 1149, 481, 499, 154),
	array('Estonia', 'Coast', 'No', 0, 904, 449, 393, 180),
	array('Livonia', 'Land', 'No', 6, 1035, 479, 438, 180),
	array('Denmark', 'Coast', 'Yes', 0, 629, 551, 268, 215),
	array('Lithuania', 'Coast', 'No', 0, 931, 545, 383, 197),
	array('Minsk', 'Land', 'Yes', 6, 994, 562, 413, 239),
	array('Pinsk', 'Land', 'No', 6, 924, 688, 395, 274),
	array('Kief', 'Coast', 'Yes', 6, 967, 779, 436, 263),
	array('Khazaria', 'Land', 'No', 0, 1321, 707, 535, 258),
	array('Cumeria', 'Coast', 'No', 0, 1093, 746, 507, 276),
	array('Crimea', 'Coast', 'No', 0, 1191, 779, 493, 304),
	array('Cherson', 'Coast', 'Yes', 5, 1181, 860, 508, 331),
	array('Tmutarakan', 'Coast', 'Yes', 0, 1292, 815, 540, 317),
	array('Tiflis', 'Land', 'Yes', 0, 1368, 964, 611, 360),
	array('Chaldia', 'Coast', 'No', 4, 1243, 1023, 519, 398),
	array('Nicaea', 'Coast', 'Yes', 4, 1166, 993, 468, 399),
	array('Patzinakia', 'Coast', 'No', 0, 956, 909, 433, 327),
	array('Hungary', 'Land', 'Yes', 0, 874, 860, 353, 335),
	array('Poland', 'Land', 'Yes', 0, 830, 709, 361, 282),
	array('Pomerania', 'Coast', 'No', 0, 736, 620, 316, 241),
	array('Saxony', 'Land', 'No', 1, 687, 676, 292, 270),
	array('Bremen', 'Coast', 'Yes', 1, 589, 602, 250, 234),
	array('Utrecht', 'Coast', 'Yes', 0, 561, 609, 228, 238),
	array('Lower Lorraine', 'Land', 'No', 1, 575, 661, 245, 255),
	array('Upper Lorraine', 'Land', 'No', 1, 555, 768, 225, 278),
	array('Flanders', 'Coast', 'Yes', 3, 482, 660, 206, 256),
	array('Haemimon', 'Coast', 'No', 5, 1014, 934, 434, 361),
	array('Nissa', 'Land', 'Yes', 5, 884, 937, 395, 373),
	array('Constantinople', 'Coast', 'Yes', 5, 1009, 991, 433, 382),
	array('Iconium', 'Coast', 'Yes', 4, 1165, 1127, 499, 444),
	array('Marash', 'Coast', 'No', 0, 1234, 1102, 524, 435),
	array('Azerbijan', 'Land', 'No', 4, 1386, 1132, 618, 445),
	array('Arabia', 'Land', 'No', 0, 1365, 1274, 579, 537),
	array('Antioch', 'Coast', 'Yes', 4, 1293, 1206, 551, 464),
	array('Jerusalem', 'Coast', 'Yes', 4, 1258, 1245, 546, 487),
	array('Sinai', 'Coast', 'No', 0, 1233, 1387, 528, 516),
	array('Cairo', 'Coast', 'Yes', 0, 1099, 1398, 420, 540),
	array('Barca', 'Coast', 'No', 7, 855, 1379, 366, 514),
	array('Cyprus', 'Coast', 'Yes', 0, 1190, 1192, 504, 462),
	array('Crete', 'Coast', 'Yes', 0, 954, 1215, 399, 472),
	array('Athens', 'Coast', 'Yes', 5, 880, 1092, 378, 446),
	array('Macedonia', 'Coast', 'No', 5, 893, 1048, 385, 401),
	array('Dyrrhachium', 'Coast', 'No', 5, 849, 1050, 361, 408),
	array('Servia', 'Coast', 'Yes', 0, 841, 980, 353, 381),
	array('Croatia', 'Land', 'No', 0, 746, 915, 318, 355),
	array('Venice', 'Coast', 'Yes', 0, 648, 884, 279, 334),
	array('Tyrolia', 'Land', 'No', 1, 720, 846, 310, 326),
	array('Bohemia', 'Land', 'No', 1, 779, 747, 310, 275),
	array('Nuremberg', 'Land', 'Yes', 1, 637, 711, 270, 290),
	array('Vienna', 'Land', 'Yes', 1, 720, 767, 322, 301),
	array('Swabia', 'Land', 'No', 1, 599, 798, 252, 311),
	array('Champagne', 'Land', 'No', 3, 484, 796, 206, 311),
	array('Clermont', 'Coast', 'Yes', 3, 384, 822, 181, 328),
	array('Paris', 'Land', 'Yes', 3, 453, 747, 201, 285),
	array('Normandy', 'Coast', 'No', 2, 396, 727, 185, 269),
	array('Brittany', 'Coast', 'No', 3, 370, 752, 156, 291),
	array('Toulouse', 'Coast', 'Yes', 3, 426, 890, 171, 336),
	array('Toulouse (West Coast)', 'Coast', 'No', 3, 346, 858, 152, 321),
	array('Toulouse (East Coast)', 'Coast', 'No', 3, 446, 896, 176, 351),
	array('Castille and Leon', 'Coast', 'Yes', 0, 180, 882, 93, 334),
	array('Navarre', 'Coast', 'No', 0, 300, 870, 131, 339),
	array('Aragon', 'Land', 'No', 0, 357, 905, 161, 353),
	array('Barcelona', 'Coast', 'Yes', 0, 398, 954, 170, 370),
	array('Cordova', 'Coast', 'Yes', 7, 264, 999, 86, 385),
	array('Portugal', 'Coast', 'No', 7, 137, 986, 54, 364),
	array('Fez', 'Coast', 'Yes', 7, 105, 1165, 89, 443),
	array('Algeria', 'Coast', 'No', 7, 440, 1180, 190, 457),
	array('West Sahara', 'Land', 'No', 7, 219, 1272, 67, 520),
	array('Tunis', 'Coast', 'Yes', 7, 541, 1206, 248, 468),
	array('Tripoli', 'Coast', 'Yes', 7, 619, 1349, 229, 502),
	array('East Sahara', 'Land', 'No', 7, 654, 1430, 275, 553),
	array('Lombardy', 'Land', 'No', 1, 614, 868, 263, 337),
	array('Genoa', 'Coast', 'Yes', 1, 568, 857, 241, 335),
	array('Piedmont', 'Coast', 'No', 1, 540, 879, 231, 339),
	array('Burgundy', 'Coast', 'Yes', 0, 500, 843, 217, 329),
	array('Pisa', 'Coast', 'Yes', 0, 610, 909, 258, 352),
	array('Ancona', 'Coast', 'No', 1, 651, 924, 278, 360),
	array('Rome', 'Coast', 'Yes', 0, 643, 966, 275, 380),
	array('Naples', 'Coast', 'Yes', 2, 734, 1051, 318, 420),
	array('Sicily', 'Coast', 'Yes', 0, 652, 1125, 280, 436),
	array('Apulia', 'Coast', 'No', 2, 730, 1000, 314, 392),
	array('Samos', 'Coast', 'No', 4, 1052, 1121, 457, 436),
	array('Barents Sea', 'Sea', 'No', 0, 962, 28, 491, 14),
	array('Norwegian Sea', 'Sea', 'No', 0, 560, 211, 227, 94),
	array('North Atlantic', 'Sea', 'No', 0, 156, 348, 71, 162),
	array('North Sea', 'Sea', 'No', 0, 512, 526, 215, 211),
	array('Bay of Biscay', 'Sea', 'No', 0, 240, 758, 116, 306),
	array('Mid Atlantic', 'Sea', 'No', 0, 47, 1013, 23, 392),
	array('West Mediterranean', 'Sea', 'No', 0, 357, 1078, 146, 420),
	array('Irish Sea', 'Sea', 'No', 0, 287, 620, 127, 224),
	array('English Channel', 'Sea', 'No', 0, 415, 669, 155, 264),
	array('Heligoland Bight', 'Sea', 'No', 0, 554, 578, 238, 222),
	array('Skagerrak', 'Sea', 'No', 0, 679, 495, 272, 180),
	array('Baltic Sea', 'Sea', 'No', 0, 776, 556, 325, 217),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 839, 391, 360, 154),
	array('Gulf of Lion', 'Sea', 'No', 0, 462, 939, 161, 391),
	array('Ligurian Sea', 'Sea', 'No', 0, 544, 933, 254, 373),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 621, 1084, 252, 429),
	array('Maltese Sea', 'Sea', 'No', 0, 635, 1238, 274, 486),
	array('Ionian Sea', 'Sea', 'No', 0, 821, 1178, 363, 463),
	array('Aegean Sea', 'Sea', 'No', 0, 971, 1182, 412, 426),
	array('Sea of Marmara', 'Sea', 'No', 0, 1071, 996, 449, 377),
	array('Black Sea', 'Sea', 'No', 0, 1214, 916, 529, 358),
	array('Cilician Sea', 'Sea', 'No', 0, 1080, 1197, 482, 454),
	array('Libyan Sea', 'Sea', 'No', 0, 760, 1297, 326, 512),
	array('Adriatic Sea', 'Sea', 'No', 0, 705, 961, 286, 352),
	array('East Mediterranean', 'Sea', 'No', 0, 1184, 1264, 502, 496),
	array('Finland (North Coast)', 'Coast', 'No', 0, 979, 204, 432, 88),
	array('Finland (South Coast)', 'Coast', 'No', 0, 892, 372, 377, 144),
	array('Crimea (West Coast)', 'Coast', 'No', 0, 1119, 828, 482, 332),
	array('Crimea (East Coast)', 'Coast', 'No', 0, 1189, 794, 507, 310),
	array('Hamburg', 'Coast', 'Yes', 1, 650, 629, 282, 230),
	array('Hamburg (East Coast)', 'Coast', 'No', 1, 701, 591, 301, 233),
	array('Hamburg (West Coast)', 'Coast', 'No', 1, 639, 587, 270, 229),
	array('Corsica', 'Coast', 'No', 0, 573, 979, 244, 371),
	array('Sardinia', 'Coast', 'Yes', 0, 566, 1056, 241, 413),
	array('Trebizond', 'Coast', 'Yes', 0, 1340, 957, 552, 376),
	array('Mercia', 'Coast', 'No', 7, 332, 972, 133, 387)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Iceland','Norwegian Sea','Yes','No'),
	array('Iceland','North Atlantic','Yes','No'),
	array('Edinburgh','Oxfordshire','Yes','Yes'),
	array('Edinburgh','York','Yes','Yes'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edinburgh','North Atlantic','Yes','No'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Edinburgh','Irish Sea','Yes','No'),
	array('Ireland','North Atlantic','Yes','No'),
	array('Ireland','Bay of Biscay','Yes','No'),
	array('Ireland','Irish Sea','Yes','No'),
	array('Oxfordshire','York','No','Yes'),
	array('Oxfordshire','Wales','Yes','Yes'),
	array('Oxfordshire','Canterbury','No','Yes'),
	array('Oxfordshire','London','No','Yes'),
	array('Oxfordshire','Irish Sea','Yes','No'),
	array('York','London','Yes','Yes'),
	array('York','North Sea','Yes','No'),
	array('Wales','Canterbury','Yes','Yes'),
	array('Wales','Irish Sea','Yes','No'),
	array('Canterbury','London','Yes','Yes'),
	array('Canterbury','North Sea','Yes','No'),
	array('Canterbury','Irish Sea','Yes','No'),
	array('Canterbury','English Channel','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('Norway','Finnmark','Yes','Yes'),
	array('Norway','Sweden','No','Yes'),
	array('Norway','Denmark','Yes','Yes'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Skagerrak','Yes','No'),
	array('Finnmark','Finland','No','Yes'),
	array('Finnmark','Sweden','No','Yes'),
	array('Finnmark','Barents Sea','Yes','No'),
	array('Finnmark','Norwegian Sea','Yes','No'),
	array('Finnmark','Finland (North Coast)','Yes','No'),
	array('Finland','Sweden','No','Yes'),
	array('Finland','Novgorod','No','Yes'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Sweden','Finland (South Coast)','Yes','No'),
	array('Novgorod','Smolensk','No','Yes'),
	array('Novgorod','Estonia','No','Yes'),
	array('Novgorod','Livonia','No','Yes'),
	array('Novgorod (South Coast)','Estonia','Yes','No'),
	array('Novgorod (South Coast)','Gulf of Bothnia','Yes','No'),
	array('Novgorod (South Coast)','Finland (South Coast)','Yes','No'),
	array('Novgorod (North Coast)','Barents Sea','Yes','No'),
	array('Novgorod (North Coast)','Finland (North Coast)','Yes','No'),
	array('Mordvinia','Smolensk','No','Yes'),
	array('Mordvinia','Khazaria','No','Yes'),
	array('Smolensk','Livonia','No','Yes'),
	array('Smolensk','Minsk','No','Yes'),
	array('Smolensk','Kief','No','Yes'),
	array('Smolensk','Khazaria','No','Yes'),
	array('Estonia','Livonia','No','Yes'),
	array('Estonia','Lithuania','Yes','Yes'),
	array('Estonia','Gulf of Bothnia','Yes','No'),
	array('Livonia','Lithuania','No','Yes'),
	array('Livonia','Minsk','No','Yes'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Heligoland Bight','Yes','No'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Denmark','Hamburg','No','Yes'),
	array('Denmark','Hamburg (East Coast)','Yes','No'),
	array('Denmark','Hamburg (West Coast)','Yes','No'),
	array('Lithuania','Minsk','No','Yes'),
	array('Lithuania','Pinsk','No','Yes'),
	array('Lithuania','Poland','No','Yes'),
	array('Lithuania','Pomerania','Yes','Yes'),
	array('Lithuania','Baltic Sea','Yes','No'),
	array('Lithuania','Gulf of Bothnia','Yes','No'),
	array('Minsk','Pinsk','No','Yes'),
	array('Minsk','Kief','No','Yes'),
	array('Pinsk','Kief','No','Yes'),
	array('Pinsk','Hungary','No','Yes'),
	array('Pinsk','Poland','No','Yes'),
	array('Kief','Khazaria','No','Yes'),
	array('Kief','Cumeria','Yes','Yes'),
	array('Kief','Patzinakia','Yes','Yes'),
	array('Kief','Hungary','No','Yes'),
	array('Khazaria','Cumeria','No','Yes'),
	array('Khazaria','Crimea','No','Yes'),
	array('Khazaria','Tmutarakan','No','Yes'),
	array('Khazaria','Tiflis','No','Yes'),
	array('Khazaria','Azerbijan','No','Yes'),
	array('Cumeria','Crimea','No','Yes'),
	array('Cumeria','Patzinakia','Yes','Yes'),
	array('Cumeria','Crimea (West Coast)','Yes','No'),
	array('Crimea','Cherson','No','Yes'),
	array('Crimea','Tmutarakan','No','Yes'),
	array('Crimea','Patzinakia','No','Yes'),
	array('Cherson','Black Sea','Yes','No'),
	array('Cherson','Crimea (West Coast)','Yes','No'),
	array('Cherson','Crimea (East Coast)','Yes','No'),
	array('Tmutarakan','Tiflis','No','Yes'),
	array('Tmutarakan','Black Sea','Yes','No'),
	array('Tmutarakan','Crimea (East Coast)','Yes','No'),
	array('Tmutarakan','Trebizond','Yes','Yes'),
	array('Tiflis','Azerbijan','No','Yes'),
	array('Tiflis','Trebizond','No','Yes'),
	array('Chaldia','Nicaea','Yes','Yes'),
	array('Chaldia','Iconium','No','Yes'),
	array('Chaldia','Marash','No','Yes'),
	array('Chaldia','Azerbijan','No','Yes'),
	array('Chaldia','Black Sea','Yes','No'),
	array('Chaldia','Trebizond','Yes','Yes'),
	array('Nicaea','Iconium','No','Yes'),
	array('Nicaea','Samos','Yes','Yes'),
	array('Nicaea','Sea of Marmara','Yes','No'),
	array('Nicaea','Black Sea','Yes','No'),
	array('Patzinakia','Hungary','No','Yes'),
	array('Patzinakia','Haemimon','Yes','Yes'),
	array('Patzinakia','Nissa','No','Yes'),
	array('Patzinakia','Black Sea','Yes','No'),
	array('Patzinakia','Crimea (West Coast)','Yes','No'),
	array('Hungary','Poland','No','Yes'),
	array('Hungary','Nissa','No','Yes'),
	array('Hungary','Croatia','No','Yes'),
	array('Hungary','Tyrolia','No','Yes'),
	array('Hungary','Bohemia','No','Yes'),
	array('Hungary','Vienna','No','Yes'),
	array('Poland','Pomerania','No','Yes'),
	array('Poland','Saxony','No','Yes'),
	array('Poland','Bohemia','No','Yes'),
	array('Pomerania','Saxony','No','Yes'),
	array('Pomerania','Baltic Sea','Yes','No'),
	array('Pomerania','Hamburg','No','Yes'),
	array('Pomerania','Hamburg (East Coast)','Yes','No'),
	array('Saxony','Lower Lorraine','No','Yes'),
	array('Saxony','Bohemia','No','Yes'),
	array('Saxony','Nuremberg','No','Yes'),
	array('Saxony','Hamburg','No','Yes'),
	array('Bremen','Utrecht','Yes','Yes'),
	array('Bremen','Lower Lorraine','No','Yes'),
	array('Bremen','Heligoland Bight','Yes','No'),
	array('Bremen','Hamburg','No','Yes'),
	array('Bremen','Hamburg (West Coast)','Yes','No'),
	array('Utrecht','Lower Lorraine','No','Yes'),
	array('Utrecht','Upper Lorraine','No','Yes'),
	array('Utrecht','Flanders','Yes','Yes'),
	array('Utrecht','North Sea','Yes','No'),
	array('Utrecht','Heligoland Bight','Yes','No'),
	array('Lower Lorraine','Upper Lorraine','No','Yes'),
	array('Lower Lorraine','Nuremberg','No','Yes'),
	array('Lower Lorraine','Hamburg','No','Yes'),
	array('Upper Lorraine','Flanders','No','Yes'),
	array('Upper Lorraine','Nuremberg','No','Yes'),
	array('Upper Lorraine','Swabia','No','Yes'),
	array('Upper Lorraine','Champagne','No','Yes'),
	array('Upper Lorraine','Burgundy','No','Yes'),
	array('Flanders','Champagne','No','Yes'),
	array('Flanders','Paris','No','Yes'),
	array('Flanders','Normandy','Yes','Yes'),
	array('Flanders','North Sea','Yes','No'),
	array('Flanders','English Channel','Yes','No'),
	array('Haemimon','Nissa','No','Yes'),
	array('Haemimon','Constantinople','Yes','Yes'),
	array('Haemimon','Macedonia','No','Yes'),
	array('Haemimon','Black Sea','Yes','No'),
	array('Nissa','Macedonia','No','Yes'),
	array('Nissa','Dyrrhachium','No','Yes'),
	array('Nissa','Servia','No','Yes'),
	array('Nissa','Croatia','No','Yes'),
	array('Constantinople','Macedonia','Yes','Yes'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Constantinople','Sea of Marmara','Yes','No'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Iconium','Marash','Yes','Yes'),
	array('Iconium','Samos','Yes','Yes'),
	array('Iconium','Cilician Sea','Yes','No'),
	array('Marash','Azerbijan','No','Yes'),
	array('Marash','Antioch','Yes','Yes'),
	array('Marash','Cilician Sea','Yes','No'),
	array('Azerbijan','Arabia','No','Yes'),
	array('Azerbijan','Antioch','No','Yes'),
	array('Azerbijan','Trebizond','No','Yes'),
	array('Arabia','Antioch','No','Yes'),
	array('Arabia','Jerusalem','No','Yes'),
	array('Arabia','Sinai','No','Yes'),
	array('Antioch','Jerusalem','Yes','Yes'),
	array('Antioch','Cilician Sea','Yes','No'),
	array('Jerusalem','Sinai','Yes','Yes'),
	array('Jerusalem','Cilician Sea','Yes','No'),
	array('Jerusalem','East Mediterranean','Yes','No'),
	array('Sinai','Cairo','Yes','Yes'),
	array('Sinai','East Mediterranean','Yes','No'),
	array('Cairo','Barca','Yes','Yes'),
	array('Cairo','East Sahara','No','Yes'),
	array('Cairo','Libyan Sea','Yes','No'),
	array('Cairo','East Mediterranean','Yes','No'),
	array('Barca','Tripoli','Yes','Yes'),
	array('Barca','East Sahara','No','Yes'),
	array('Barca','Libyan Sea','Yes','No'),
	array('Cyprus','Cilician Sea','Yes','No'),
	array('Cyprus','East Mediterranean','Yes','No'),
	array('Crete','Ionian Sea','Yes','No'),
	array('Crete','Aegean Sea','Yes','No'),
	array('Crete','Libyan Sea','Yes','No'),
	array('Crete','East Mediterranean','Yes','No'),
	array('Athens','Macedonia','Yes','Yes'),
	array('Athens','Dyrrhachium','Yes','Yes'),
	array('Athens','Ionian Sea','Yes','No'),
	array('Athens','Aegean Sea','Yes','No'),
	array('Macedonia','Dyrrhachium','No','Yes'),
	array('Macedonia','Aegean Sea','Yes','No'),
	array('Dyrrhachium','Servia','Yes','Yes'),
	array('Dyrrhachium','Ionian Sea','Yes','No'),
	array('Dyrrhachium','Adriatic Sea','Yes','No'),
	array('Servia','Croatia','No','Yes'),
	array('Servia','Venice','Yes','Yes'),
	array('Servia','Adriatic Sea','Yes','No'),
	array('Croatia','Venice','No','Yes'),
	array('Croatia','Tyrolia','No','Yes'),
	array('Venice','Tyrolia','No','Yes'),
	array('Venice','Lombardy','No','Yes'),
	array('Venice','Ancona','Yes','Yes'),
	array('Venice','Adriatic Sea','Yes','No'),
	array('Tyrolia','Nuremberg','No','Yes'),
	array('Tyrolia','Vienna','No','Yes'),
	array('Tyrolia','Swabia','No','Yes'),
	array('Tyrolia','Lombardy','No','Yes'),
	array('Bohemia','Nuremberg','No','Yes'),
	array('Bohemia','Vienna','No','Yes'),
	array('Nuremberg','Vienna','No','Yes'),
	array('Nuremberg','Swabia','No','Yes'),
	array('Swabia','Lombardy','No','Yes'),
	array('Swabia','Burgundy','No','Yes'),
	array('Champagne','Clermont','No','Yes'),
	array('Champagne','Paris','No','Yes'),
	array('Champagne','Burgundy','No','Yes'),
	array('Clermont','Paris','No','Yes'),
	array('Clermont','Brittany','Yes','Yes'),
	array('Clermont','Toulouse','No','Yes'),
	array('Clermont','Toulouse (West Coast)','Yes','No'),
	array('Clermont','Burgundy','No','Yes'),
	array('Clermont','Bay of Biscay','Yes','No'),
	array('Paris','Normandy','No','Yes'),
	array('Paris','Brittany','No','Yes'),
	array('Normandy','Brittany','Yes','Yes'),
	array('Normandy','English Channel','Yes','No'),
	array('Brittany','Bay of Biscay','Yes','No'),
	array('Brittany','English Channel','Yes','No'),
	array('Toulouse','Navarre','No','Yes'),
	array('Toulouse','Aragon','No','Yes'),
	array('Toulouse','Barcelona','No','Yes'),
	array('Toulouse','Burgundy','No','Yes'),
	array('Toulouse (West Coast)','Navarre','Yes','No'),
	array('Toulouse (West Coast)','Bay of Biscay','Yes','No'),
	array('Toulouse (East Coast)','Barcelona','Yes','No'),
	array('Toulouse (East Coast)','Burgundy','Yes','No'),
	array('Toulouse (East Coast)','Gulf of Lion','Yes','No'),
	array('Castille and Leon','Navarre','Yes','Yes'),
	array('Castille and Leon','Cordova','No','Yes'),
	array('Castille and Leon','Portugal','Yes','Yes'),
	array('Castille and Leon','Bay of Biscay','Yes','No'),
	array('Castille and Leon','Mercia','No','Yes'),
	array('Navarre','Aragon','No','Yes'),
	array('Navarre','Bay of Biscay','Yes','No'),
	array('Navarre','Mercia','No','Yes'),
	array('Aragon','Barcelona','No','Yes'),
	array('Aragon','Mercia','No','Yes'),
	array('Barcelona','Gulf of Lion','Yes','No'),
	array('Barcelona','Mercia','Yes','Yes'),
	array('Cordova','Portugal','Yes','Yes'),
	array('Cordova','Mid Atlantic','Yes','No'),
	array('Cordova','West Mediterranean','Yes','No'),
	array('Cordova','Gulf of Lion','Yes','No'),
	array('Cordova','Mercia','Yes','Yes'),
	array('Portugal','Bay of Biscay','Yes','No'),
	array('Portugal','Mid Atlantic','Yes','No'),
	array('Fez','Algeria','Yes','Yes'),
	array('Fez','West Sahara','No','Yes'),
	array('Fez','Mid Atlantic','Yes','No'),
	array('Fez','West Mediterranean','Yes','No'),
	array('Algeria','West Sahara','No','Yes'),
	array('Algeria','Tunis','Yes','Yes'),
	array('Algeria','Tripoli','No','Yes'),
	array('Algeria','West Mediterranean','Yes','No'),
	array('West Sahara','Tripoli','No','Yes'),
	array('West Sahara','East Sahara','No','Yes'),
	array('Tunis','Tripoli','Yes','Yes'),
	array('Tunis','West Mediterranean','Yes','No'),
	array('Tunis','Tyrrhenian Sea','Yes','No'),
	array('Tunis','Maltese Sea','Yes','No'),
	array('Tripoli','East Sahara','No','Yes'),
	array('Tripoli','Maltese Sea','Yes','No'),
	array('Tripoli','Libyan Sea','Yes','No'),
	array('Lombardy','Genoa','No','Yes'),
	array('Lombardy','Pisa','No','Yes'),
	array('Lombardy','Ancona','No','Yes'),
	array('Genoa','Piedmont','Yes','Yes'),
	array('Genoa','Pisa','Yes','Yes'),
	array('Genoa','Ligurian Sea','Yes','No'),
	array('Piedmont','Burgundy','Yes','Yes'),
	array('Piedmont','Ligurian Sea','Yes','No'),
	array('Burgundy','Gulf of Lion','Yes','No'),
	array('Burgundy','Ligurian Sea','Yes','No'),
	array('Pisa','Ancona','No','Yes'),
	array('Pisa','Rome','Yes','Yes'),
	array('Pisa','Ligurian Sea','Yes','No'),
	array('Ancona','Rome','No','Yes'),
	array('Ancona','Naples','No','Yes'),
	array('Ancona','Apulia','Yes','Yes'),
	array('Ancona','Adriatic Sea','Yes','No'),
	array('Rome','Naples','Yes','Yes'),
	array('Rome','Ligurian Sea','Yes','No'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Naples','Apulia','Yes','Yes'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Sicily','Tyrrhenian Sea','Yes','No'),
	array('Sicily','Maltese Sea','Yes','No'),
	array('Sicily','Ionian Sea','Yes','No'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Samos','Aegean Sea','Yes','No'),
	array('Samos','Sea of Marmara','Yes','No'),
	array('Samos','Cilician Sea','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Barents Sea','Finland (North Coast)','Yes','No'),
	array('Norwegian Sea','North Atlantic','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('North Atlantic','Bay of Biscay','Yes','No'),
	array('North Atlantic','Irish Sea','Yes','No'),
	array('North Sea','English Channel','Yes','No'),
	array('North Sea','Heligoland Bight','Yes','No'),
	array('North Sea','Skagerrak','Yes','No'),
	array('Bay of Biscay','Mid Atlantic','Yes','No'),
	array('Bay of Biscay','Irish Sea','Yes','No'),
	array('Bay of Biscay','English Channel','Yes','No'),
	array('Mid Atlantic','West Mediterranean','Yes','No'),
	array('West Mediterranean','Gulf of Lion','Yes','No'),
	array('West Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('West Mediterranean','Sardinia','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('Heligoland Bight','Hamburg (West Coast)','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Baltic Sea','Hamburg (East Coast)','Yes','No'),
	array('Gulf of Bothnia','Finland (South Coast)','Yes','No'),
	array('Gulf of Lion','Ligurian Sea','Yes','No'),
	array('Gulf of Lion','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lion','Corsica','Yes','No'),
	array('Gulf of Lion','Sardinia','Yes','No'),
	array('Gulf of Lion','Mercia','Yes','No'),
	array('Ligurian Sea','Tyrrhenian Sea','Yes','No'),
	array('Ligurian Sea','Corsica','Yes','No'),
	array('Tyrrhenian Sea','Maltese Sea','Yes','No'),
	array('Tyrrhenian Sea','Ionian Sea','Yes','No'),
	array('Tyrrhenian Sea','Corsica','Yes','No'),
	array('Tyrrhenian Sea','Sardinia','Yes','No'),
	array('Maltese Sea','Ionian Sea','Yes','No'),
	array('Maltese Sea','Libyan Sea','Yes','No'),
	array('Ionian Sea','Aegean Sea','Yes','No'),
	array('Ionian Sea','Libyan Sea','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Aegean Sea','Sea of Marmara','Yes','No'),
	array('Aegean Sea','Cilician Sea','Yes','No'),
	array('Aegean Sea','East Mediterranean','Yes','No'),
	array('Sea of Marmara','Black Sea','Yes','No'),
	array('Black Sea','Crimea (West Coast)','Yes','No'),
	array('Black Sea','Crimea (East Coast)','Yes','No'),
	array('Black Sea','Trebizond','Yes','No'),
	array('Cilician Sea','East Mediterranean','Yes','No'),
	array('Libyan Sea','East Mediterranean','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
