<?php
// This is file installs the map data for the Chromatic variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Ice Sea', 'Sea', 'No', 0, 400, 81, 214, 36),
	array('Sea of Cherries', 'Sea', 'No', 0, 343, 243, 172, 100),
	array('Garnet', 'Coast', 'Yes', 0, 236, 151, 120, 73),
	array('Carnation Sea', 'Sea', 'No', 0, 203, 372, 102, 182),
	array('Bay of Roses', 'Sea', 'No', 0, 390, 353, 195, 180),
	array('Ghost', 'Coast', 'Yes', 4, 457, 371, 229, 184),
	array('Snow', 'Coast', 'No', 4, 515, 196, 246, 66),
	array('Alabaster', 'Coast', 'Yes', 4, 564, 107, 284, 53),
	array('Ivory', 'Coast', 'Yes', 4, 559, 245, 279, 120),
	array('Chalk', 'Coast', 'No', 4, 554, 303, 277, 162),
	array('Sea of Lead', 'Sea', 'No', 0, 588, 171, 338, 101),
	array('Silver', 'Coast', 'Yes', 0, 771, 115, 382, 88),
	array('Sea of Mercury', 'Sea', 'No', 0, 781, 253, 399, 183),
	array('Sea of Night', 'Sea', 'No', 0, 938, 297, 469, 143),
	array('Sea of Platinum', 'Sea', 'No', 0, 729, 403, 366, 200),
	array('Paper', 'Coast', 'No', 0, 610, 415, 309, 203),
	array('Jet', 'Coast', 'Yes', 3, 678, 417, 338, 207),
	array('Coal', 'Coast', 'No', 3, 881, 392, 441, 191),
	array('Obsidian', 'Coast', 'Yes', 3, 958, 424, 442, 209),
	array('Sea of Umber', 'Sea', 'No', 0, 899, 474, 406, 260),
	array('Ebony', 'Coast', 'Yes', 3, 829, 454, 413, 228),
	array('Raven', 'Coast', 'No', 3, 762, 471, 380, 234),
	array('Ink', 'Coast', 'No', 0, 640, 490, 335, 281),
	array('Crystal', 'Land', 'Yes', 0, 539, 571, 268, 284),
	array('Bronze', 'Coast', 'Yes', 0, 1010, 659, 507, 330),
	array('Gulf of Hazel', 'Sea', 'No', 0, 717, 686, 362, 341),
	array('Sepiatic Sea', 'Sea', 'No', 0, 858, 660, 393, 367),
	array('Sea of Butter', 'Sea', 'No', 0, 883, 857, 440, 430),
	array('Sunshine', 'Coast', 'Yes', 2, 693, 637, 347, 320),
	array('Lemon', 'Coast', 'No', 2, 755, 797, 378, 398),
	array('Topaz', 'Coast', 'Yes', 2, 780, 873, 390, 435),
	array('Gold', 'Coast', 'Yes', 2, 706, 796, 349, 396),
	array('Sulphur', 'Coast', 'No', 2, 644, 709, 327, 371),
	array('Saffron', 'Coast', 'No', 0, 546, 682, 274, 336),
	array('Malachite', 'Coast', 'Yes', 0, 575, 1016, 286, 479),
	array('Sea of Cyan', 'Sea', 'No', 0, 707, 870, 358, 434),
	array('Bay of Emeralds', 'Sea', 'No', 0, 447, 756, 267, 399),
	array('Forest Sea', 'Sea', 'No', 0, 518, 900, 263, 444),
	array('Cobalt', 'Coast', 'Yes', 1, 494, 723, 248, 360),
	array('Cerulean', 'Coast', 'No', 1, 360, 823, 171, 444),
	array('Aquatic Sea', 'Sea', 'No', 0, 332, 965, 167, 480),
	array('Sapphire', 'Coast', 'Yes', 1, 267, 868, 169, 396),
	array('Royal', 'Coast', 'Yes', 1, 351, 773, 184, 371),
	array('Azure', 'Coast', 'No', 1, 402, 688, 202, 341),
	array('Indigo Sea', 'Sea', 'No', 0, 273, 795, 140, 398),
	array('Gulf of Mauve', 'Sea', 'No', 0, 317, 628, 153, 257),
	array('Cold', 'Coast', 'No', 0, 402, 586, 240, 320),
	array('Magenta', 'Coast', 'Yes', 0, 146, 696, 49, 376),
	array('Violet Sea', 'Sea', 'No', 0, 199, 629, 115, 257),
	array('Sea of Lava', 'Sea', 'No', 0, 64, 476, 39, 214),
	array('Ruby', 'Coast', 'Yes', 5, 350, 556, 176, 274),
	array('Maroon', 'Coast', 'No', 5, 146, 452, 85, 223),
	array('Vermillion', 'Coast', 'Yes', 5, 143, 371, 74, 198),
	array('Crimson', 'Coast', 'Yes', 5, 294, 444, 137, 205),
	array('Fire Engine', 'Coast', 'No', 5, 368, 460, 181, 227),
	array('Hot', 'Coast', 'No', 0, 443, 439, 223, 216)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Ice Sea','Sea of Cherries','Yes','No'),
	array('Ice Sea','Garnet','Yes','No'),
	array('Ice Sea','Snow','Yes','No'),
	array('Ice Sea','Alabaster','Yes','No'),
	array('Ice Sea','Sea of Lead','Yes','No'),
	array('Ice Sea','Silver','Yes','No'),
	array('Sea of Cherries','Garnet','Yes','No'),
	array('Sea of Cherries','Carnation Sea','Yes','No'),
	array('Sea of Cherries','Bay of Roses','Yes','No'),
	array('Sea of Cherries','Ghost','Yes','No'),
	array('Sea of Cherries','Snow','Yes','No'),
	array('Garnet','Carnation Sea','Yes','No'),
	array('Garnet','Sea of Lava','Yes','No'),
	array('Carnation Sea','Bay of Roses','Yes','No'),
	array('Carnation Sea','Sea of Lava','Yes','No'),
	array('Carnation Sea','Vermillion','Yes','No'),
	array('Carnation Sea','Crimson','Yes','No'),
	array('Carnation Sea','Fire Engine','Yes','No'),
	array('Bay of Roses','Ghost','Yes','No'),
	array('Bay of Roses','Fire Engine','Yes','No'),
	array('Bay of Roses','Hot','Yes','No'),
	array('Ghost','Snow','Yes','Yes'),
	array('Ghost','Ivory','No','Yes'),
	array('Ghost','Chalk','No','Yes'),
	array('Ghost','Paper','No','Yes'),
	array('Ghost','Hot','Yes','Yes'),
	array('Snow','Alabaster','Yes','Yes'),
	array('Snow','Ivory','No','Yes'),
	array('Alabaster','Ivory','Yes','Yes'),
	array('Alabaster','Sea of Lead','Yes','No'),
	array('Ivory','Chalk','Yes','Yes'),
	array('Ivory','Sea of Lead','Yes','No'),
	array('Chalk','Sea of Lead','Yes','No'),
	array('Chalk','Sea of Platinum','Yes','No'),
	array('Chalk','Paper','Yes','Yes'),
	array('Sea of Lead','Silver','Yes','No'),
	array('Sea of Lead','Sea of Mercury','Yes','No'),
	array('Sea of Lead','Sea of Platinum','Yes','No'),
	array('Silver','Sea of Mercury','Yes','No'),
	array('Silver','Sea of Night','Yes','No'),
	array('Sea of Mercury','Sea of Night','Yes','No'),
	array('Sea of Mercury','Sea of Platinum','Yes','No'),
	array('Sea of Mercury','Jet','Yes','No'),
	array('Sea of Mercury','Coal','Yes','No'),
	array('Sea of Night','Coal','Yes','No'),
	array('Sea of Night','Obsidian','Yes','No'),
	array('Sea of Night','Sea of Umber','Yes','No'),
	array('Sea of Night','Bronze','Yes','No'),
	array('Sea of Platinum','Paper','Yes','No'),
	array('Sea of Platinum','Jet','Yes','No'),
	array('Paper','Jet','Yes','Yes'),
	array('Paper','Ink','No','Yes'),
	array('Paper','Crystal','No','Yes'),
	array('Paper','Hot','No','Yes'),
	array('Jet','Coal','Yes','Yes'),
	array('Jet','Ebony','No','Yes'),
	array('Jet','Raven','No','Yes'),
	array('Jet','Ink','No','Yes'),
	array('Coal','Obsidian','Yes','Yes'),
	array('Coal','Ebony','No','Yes'),
	array('Obsidian','Sea of Umber','Yes','No'),
	array('Obsidian','Ebony','Yes','Yes'),
	array('Sea of Umber','Ebony','Yes','No'),
	array('Sea of Umber','Raven','Yes','No'),
	array('Sea of Umber','Bronze','Yes','No'),
	array('Sea of Umber','Gulf of Hazel','Yes','No'),
	array('Sea of Umber','Sepiatic Sea','Yes','No'),
	array('Ebony','Raven','Yes','Yes'),
	array('Raven','Ink','Yes','Yes'),
	array('Raven','Gulf of Hazel','Yes','No'),
	array('Ink','Crystal','No','Yes'),
	array('Ink','Gulf of Hazel','Yes','No'),
	array('Ink','Sunshine','Yes','Yes'),
	array('Ink','Saffron','No','Yes'),
	array('Crystal','Saffron','No','Yes'),
	array('Crystal','Cold','No','Yes'),
	array('Crystal','Hot','No','Yes'),
	array('Bronze','Sepiatic Sea','Yes','No'),
	array('Bronze','Sea of Butter','Yes','No'),
	array('Gulf of Hazel','Sepiatic Sea','Yes','No'),
	array('Gulf of Hazel','Sunshine','Yes','No'),
	array('Sepiatic Sea','Sea of Butter','Yes','No'),
	array('Sepiatic Sea','Sunshine','Yes','No'),
	array('Sepiatic Sea','Lemon','Yes','No'),
	array('Sea of Butter','Lemon','Yes','No'),
	array('Sea of Butter','Topaz','Yes','No'),
	array('Sea of Butter','Malachite','Yes','No'),
	array('Sea of Butter','Sea of Cyan','Yes','No'),
	array('Sunshine','Lemon','Yes','Yes'),
	array('Sunshine','Gold','No','Yes'),
	array('Sunshine','Sulphur','No','Yes'),
	array('Sunshine','Saffron','No','Yes'),
	array('Lemon','Topaz','Yes','Yes'),
	array('Lemon','Gold','No','Yes'),
	array('Topaz','Gold','Yes','Yes'),
	array('Topaz','Sea of Cyan','Yes','No'),
	array('Gold','Sulphur','Yes','Yes'),
	array('Gold','Sea of Cyan','Yes','No'),
	array('Sulphur','Saffron','Yes','Yes'),
	array('Sulphur','Sea of Cyan','Yes','No'),
	array('Sulphur','Bay of Emeralds','Yes','No'),
	array('Saffron','Bay of Emeralds','Yes','No'),
	array('Saffron','Cobalt','Yes','Yes'),
	array('Saffron','Cold','No','Yes'),
	array('Malachite','Sea of Cyan','Yes','No'),
	array('Malachite','Forest Sea','Yes','No'),
	array('Malachite','Aquatic Sea','Yes','No'),
	array('Sea of Cyan','Bay of Emeralds','Yes','No'),
	array('Sea of Cyan','Forest Sea','Yes','No'),
	array('Bay of Emeralds','Forest Sea','Yes','No'),
	array('Bay of Emeralds','Cobalt','Yes','No'),
	array('Forest Sea','Cobalt','Yes','No'),
	array('Forest Sea','Cerulean','Yes','No'),
	array('Forest Sea','Aquatic Sea','Yes','No'),
	array('Cobalt','Cerulean','Yes','Yes'),
	array('Cobalt','Royal','No','Yes'),
	array('Cobalt','Azure','No','Yes'),
	array('Cobalt','Cold','No','Yes'),
	array('Cerulean','Aquatic Sea','Yes','No'),
	array('Cerulean','Sapphire','Yes','Yes'),
	array('Cerulean','Royal','No','Yes'),
	array('Aquatic Sea','Sapphire','Yes','No'),
	array('Aquatic Sea','Indigo Sea','Yes','No'),
	array('Aquatic Sea','Magenta','Yes','No'),
	array('Sapphire','Royal','Yes','Yes'),
	array('Sapphire','Indigo Sea','Yes','No'),
	array('Royal','Azure','Yes','Yes'),
	array('Royal','Indigo Sea','Yes','No'),
	array('Azure','Indigo Sea','Yes','No'),
	array('Azure','Gulf of Mauve','Yes','No'),
	array('Azure','Cold','Yes','Yes'),
	array('Indigo Sea','Gulf of Mauve','Yes','No'),
	array('Indigo Sea','Magenta','Yes','No'),
	array('Indigo Sea','Violet Sea','Yes','No'),
	array('Gulf of Mauve','Cold','Yes','No'),
	array('Gulf of Mauve','Violet Sea','Yes','No'),
	array('Gulf of Mauve','Ruby','Yes','No'),
	array('Cold','Ruby','Yes','Yes'),
	array('Cold','Hot','No','Yes'),
	array('Magenta','Violet Sea','Yes','No'),
	array('Magenta','Sea of Lava','Yes','No'),
	array('Violet Sea','Sea of Lava','Yes','No'),
	array('Violet Sea','Ruby','Yes','No'),
	array('Violet Sea','Maroon','Yes','No'),
	array('Sea of Lava','Maroon','Yes','No'),
	array('Sea of Lava','Vermillion','Yes','No'),
	array('Ruby','Maroon','Yes','Yes'),
	array('Ruby','Crimson','No','Yes'),
	array('Ruby','Fire Engine','No','Yes'),
	array('Ruby','Hot','No','Yes'),
	array('Maroon','Vermillion','Yes','Yes'),
	array('Maroon','Crimson','No','Yes'),
	array('Vermillion','Crimson','Yes','Yes'),
	array('Crimson','Fire Engine','Yes','Yes'),
	array('Fire Engine','Hot','Yes','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
