<?php
/*
    Copyright (C) 2004-2009 Kestas J. Kuliukas

	This file is part of webDiplomacy.

    webDiplomacy is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    webDiplomacy is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with webDiplomacy.  If not, see <http://www.gnu.org/licenses/>.
 */

defined('IN_CODE') or die('This script can not be run by itself.');

/**
 * Installs Classic map data
 */

require_once("variants/install.php");

InstallTerritory::$Territories=array();
new InstallTerritory('Clyde', 'Coast', 'No', 1, 299, 336, 160, 109);
new InstallTerritory('Edingburgh', 'Coast', 'Yes', 1, 346, 347, 175, 112);
new InstallTerritory('Liverpool', 'Coast', 'Yes', 1, 315, 413, 170, 144);
new InstallTerritory('Yorkshire', 'Coast', 'No', 1, 355, 440, 184, 150);
new InstallTerritory('Wales', 'Coast', 'No', 1, 294, 473, 154, 169);
new InstallTerritory('London', 'Coast', 'Yes', 1, 361, 481, 186, 175);
new InstallTerritory('Portugal', 'Coast', 'Yes', 0, 91, 718, 60, 305);
new InstallTerritory('Spanien', 'Coast', 'Yes', 0, 177, 794, 100, 324);
new InstallTerritory('Nord Afrika', 'Coast', 'No', 0, 181, 949, 118, 386);
new InstallTerritory('Tunis', 'Coast', 'Yes', 0, 434, 961, 212, 390);
new InstallTerritory('Neapel', 'Coast', 'Yes', 3, 570, 864, 298, 362);
new InstallTerritory('Rom', 'Coast', 'Yes', 3, 522, 808, 272, 332);
new InstallTerritory('Toskana', 'Coast', 'No', 3, 485, 767, 256, 309);
new InstallTerritory('Piemont', 'Coast', 'No', 3, 441, 694, 228, 279);
new InstallTerritory('Venedig', 'Coast', 'Yes', 3, 501, 717, 261, 289);
new InstallTerritory('Apulien', 'Coast', 'No', 3, 591, 825, 305, 343);
new InstallTerritory('Griechenland', 'Coast', 'Yes', 0, 678, 863, 358, 359);
new InstallTerritory('Albanien', 'Coast', 'No', 0, 640, 827, 344, 337);
new InstallTerritory('Serbien', 'Land', 'Yes', 0, 667, 776, 354, 315);
new InstallTerritory('Bulgarien', 'Coast', 'Yes', 0, 740, 776, 396, 311);
new InstallTerritory('Rum&auml;nien', 'Coast', 'Yes', 0, 717, 724, 422, 289);
new InstallTerritory('Konstantinopel', 'Coast', 'Yes', 6, 821, 852, 441, 341);
new InstallTerritory('Smyrna', 'Coast', 'Yes', 6, 899, 895, 480, 360);
new InstallTerritory('Ankara', 'Coast', 'Yes', 6, 986, 816, 498, 325);
new InstallTerritory('Armenien', 'Coast', 'No', 6, 1073, 785, 572, 323);
new InstallTerritory('Syrien', 'Coast', 'No', 6, 1045, 938, 559, 381);
new InstallTerritory('Sewastopol', 'Coast', 'Yes', 7, 923, 595, 500, 244);
new InstallTerritory('Ukraine', 'Land', 'No', 7, 779, 579, 418, 223);
new InstallTerritory('Warschau', 'Land', 'Yes', 7, 683, 547, 354, 212);
new InstallTerritory('Livland', 'Coast', 'No', 7, 719, 430, 374, 168);
new InstallTerritory('Moskau', 'Land', 'Yes', 7, 830, 465, 490, 155);
new InstallTerritory('St. Petersburg', 'Coast', 'Yes', 7, 837, 309, 445, 104);
new InstallTerritory('Finnland', 'Coast', 'No', 7, 702, 263, 367, 109);
new InstallTerritory('Schweden', 'Coast', 'Yes', 0, 587, 274, 313, 87);
new InstallTerritory('Norwegen', 'Coast', 'Yes', 0, 518, 270, 271, 100);
new InstallTerritory('D&auml;nemark', 'Coast', 'Yes', 0, 501, 422, 264, 156);
new InstallTerritory('Kiel', 'Coast', 'Yes', 4, 485, 516, 256, 200);
new InstallTerritory('Berlin', 'Coast', 'Yes', 4, 551, 477, 292, 193);
new InstallTerritory('Preu&szlig;en', 'Coast', 'No', 4, 621, 481, 329, 192);
new InstallTerritory('Schlesien', 'Land', 'No', 4, 589, 545, 304, 217);
new InstallTerritory('M&uuml;nchen', 'Land', 'Yes', 4, 489, 581, 248, 232);
new InstallTerritory('Ruhr', 'Land', 'No', 4, 448, 545, 234, 214);
new InstallTerritory('Holland', 'Coast', 'Yes', 0, 440, 488, 234, 186);
new InstallTerritory('Belgien', 'Coast', 'Yes', 0, 410, 551, 215, 205);
new InstallTerritory('Pikardie', 'Coast', 'No', 2, 359, 559, 189, 214);
new InstallTerritory('Brest', 'Coast', 'Yes', 2, 291, 583, 146, 223);
new InstallTerritory('Paris', 'Land', 'Yes', 2, 336, 620, 179, 238);
new InstallTerritory('Burgund', 'Land', 'No', 2, 404, 626, 206, 248);
new InstallTerritory('Marsaille', 'Coast', 'Yes', 2, 390, 689, 183, 286);
new InstallTerritory('Gascogne', 'Coast', 'No', 2, 301, 679, 150, 274);
new InstallTerritory('Barentssee', 'Sea', 'No', 0, 836, 33, 420, 20);
new InstallTerritory('Nordmeer', 'Sea', 'No', 0, 452, 109, 268, 35);
new InstallTerritory('Nordsee', 'Sea', 'No', 0, 414, 378, 216, 136);
new InstallTerritory('Skagerak', 'Sea', 'No', 0, 516, 363, 279, 133);
new InstallTerritory('Helgonlaender Bucht', 'Sea', 'No', 0, 460, 447, 250, 167);
new InstallTerritory('Ostsee', 'Sea', 'No', 0, 621, 434, 338, 175);
new InstallTerritory('Bottn. Meerbusen', 'Sea', 'No', 0, 653, 348, 362, 131);
new InstallTerritory('Nord-Atlantik', 'Sea', 'No', 0, 153, 237, 78, 87);
new InstallTerritory('Irische See', 'Sea', 'No', 0, 218, 478, 110, 178);
new InstallTerritory('Kanal', 'Sea', 'No', 0, 273, 527, 153, 198);
new InstallTerritory('Mittel-Atlantik', 'Sea', 'No', 0, 106, 581, 81, 247);
new InstallTerritory('westl. Mittelmeer', 'Sea', 'No', 0, 327, 858, 186, 363);
new InstallTerritory('Golf von Lyon', 'Sea', 'No', 0, 366, 774, 205, 323);
new InstallTerritory('Tyrrhnisches Meer', 'Sea', 'No', 0, 488, 849, 250, 348);
new InstallTerritory('Ionisches Meer', 'Sea', 'No', 0, 602, 947, 325, 384);
new InstallTerritory('Adriatisches Meer', 'Sea', 'No', 0, 564, 773, 311, 319);
new InstallTerritory('&Auml;g&auml;isches Meer', 'Sea', 'No', 0, 740, 863, 400, 378);
new InstallTerritory('oestl. Mittelmeer', 'Sea', 'No', 0, 860, 972, 454, 391);
new InstallTerritory('Schwarzes Meer', 'Sea', 'No', 0, 905, 743, 469, 300);
new InstallTerritory('Tirol', 'Land', 'No', 5, 538, 641, 273, 260);
new InstallTerritory('B&ouml;hmen', 'Land', 'No', 5, 562, 590, 292, 232);
new InstallTerritory('Wien', 'Land', 'Yes', 5, 602, 627, 319, 246);
new InstallTerritory('Triest', 'Coast', 'Yes', 5, 593, 730, 311, 291);
new InstallTerritory('Budapest', 'Land', 'Yes', 5, 681, 668, 354, 271);
new InstallTerritory('Galizien', 'Land', 'No', 5, 718, 610, 365, 237);
new InstallTerritory('Spanien (North Coast)', 'Coast', 'No', 0, 193, 685, 94, 277);
new InstallTerritory('Spanien (South Coast)', 'Coast', 'No', 0, 191, 832, 106, 345);
new InstallTerritory('St. Petersburg (North Coast)', 'Coast', 'No', 7, 828, 111, 448, 59);
new InstallTerritory('St. Petersburg (South Coast)', 'Coast', 'No', 7, 780, 355, 398, 133);
new InstallTerritory('Bulgarien (North Coast)', 'Coast', 'No', 0, 785, 762, 420, 304);
new InstallTerritory('Bulgarien (South Coast)', 'Coast', 'No', 0, 749, 815, 397, 329);
InstallTerritory::$Territories['Edingburgh']->addBorder(InstallTerritory::$Territories['Clyde'], 'Yes', 'Yes');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['Clyde'], 'Yes', 'Yes');
InstallTerritory::$Territories['Nordmeer']->addBorder(InstallTerritory::$Territories['Clyde'], 'Yes', 'No');
InstallTerritory::$Territories['Nord-Atlantik']->addBorder(InstallTerritory::$Territories['Clyde'], 'Yes', 'No');
InstallTerritory::$Territories['Clyde']->addBorder(InstallTerritory::$Territories['Edingburgh'], 'Yes', 'Yes');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['Edingburgh'], 'No', 'Yes');
InstallTerritory::$Territories['Yorkshire']->addBorder(InstallTerritory::$Territories['Edingburgh'], 'Yes', 'Yes');
InstallTerritory::$Territories['Nordmeer']->addBorder(InstallTerritory::$Territories['Edingburgh'], 'Yes', 'No');
InstallTerritory::$Territories['Nordsee']->addBorder(InstallTerritory::$Territories['Edingburgh'], 'Yes', 'No');
InstallTerritory::$Territories['Clyde']->addBorder(InstallTerritory::$Territories['Liverpool'], 'Yes', 'Yes');
InstallTerritory::$Territories['Edingburgh']->addBorder(InstallTerritory::$Territories['Liverpool'], 'No', 'Yes');
InstallTerritory::$Territories['Yorkshire']->addBorder(InstallTerritory::$Territories['Liverpool'], 'No', 'Yes');
InstallTerritory::$Territories['Wales']->addBorder(InstallTerritory::$Territories['Liverpool'], 'Yes', 'Yes');
InstallTerritory::$Territories['Nord-Atlantik']->addBorder(InstallTerritory::$Territories['Liverpool'], 'Yes', 'No');
InstallTerritory::$Territories['Irische See']->addBorder(InstallTerritory::$Territories['Liverpool'], 'Yes', 'No');
InstallTerritory::$Territories['Edingburgh']->addBorder(InstallTerritory::$Territories['Yorkshire'], 'Yes', 'Yes');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['Yorkshire'], 'No', 'Yes');
InstallTerritory::$Territories['Wales']->addBorder(InstallTerritory::$Territories['Yorkshire'], 'No', 'Yes');
InstallTerritory::$Territories['London']->addBorder(InstallTerritory::$Territories['Yorkshire'], 'Yes', 'Yes');
InstallTerritory::$Territories['Nordsee']->addBorder(InstallTerritory::$Territories['Yorkshire'], 'Yes', 'No');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['Wales'], 'Yes', 'Yes');
InstallTerritory::$Territories['Yorkshire']->addBorder(InstallTerritory::$Territories['Wales'], 'No', 'Yes');
InstallTerritory::$Territories['London']->addBorder(InstallTerritory::$Territories['Wales'], 'Yes', 'Yes');
InstallTerritory::$Territories['Irische See']->addBorder(InstallTerritory::$Territories['Wales'], 'Yes', 'No');
InstallTerritory::$Territories['Kanal']->addBorder(InstallTerritory::$Territories['Wales'], 'Yes', 'No');
InstallTerritory::$Territories['Yorkshire']->addBorder(InstallTerritory::$Territories['London'], 'Yes', 'Yes');
InstallTerritory::$Territories['Wales']->addBorder(InstallTerritory::$Territories['London'], 'Yes', 'Yes');
InstallTerritory::$Territories['Nordsee']->addBorder(InstallTerritory::$Territories['London'], 'Yes', 'No');
InstallTerritory::$Territories['Kanal']->addBorder(InstallTerritory::$Territories['London'], 'Yes', 'No');
InstallTerritory::$Territories['Spanien']->addBorder(InstallTerritory::$Territories['Portugal'], 'No', 'Yes');
InstallTerritory::$Territories['Mittel-Atlantik']->addBorder(InstallTerritory::$Territories['Portugal'], 'Yes', 'No');
InstallTerritory::$Territories['Spanien (North Coast)']->addBorder(InstallTerritory::$Territories['Portugal'], 'Yes', 'No');
InstallTerritory::$Territories['Spanien (South Coast)']->addBorder(InstallTerritory::$Territories['Portugal'], 'Yes', 'No');
InstallTerritory::$Territories['Portugal']->addBorder(InstallTerritory::$Territories['Spanien'], 'No', 'Yes');
InstallTerritory::$Territories['Marsaille']->addBorder(InstallTerritory::$Territories['Spanien'], 'No', 'Yes');
InstallTerritory::$Territories['Gascogne']->addBorder(InstallTerritory::$Territories['Spanien'], 'No', 'Yes');
InstallTerritory::$Territories['Tunis']->addBorder(InstallTerritory::$Territories['Nord Afrika'], 'Yes', 'Yes');
InstallTerritory::$Territories['Mittel-Atlantik']->addBorder(InstallTerritory::$Territories['Nord Afrika'], 'Yes', 'No');
InstallTerritory::$Territories['westl. Mittelmeer']->addBorder(InstallTerritory::$Territories['Nord Afrika'], 'Yes', 'No');
InstallTerritory::$Territories['Nord Afrika']->addBorder(InstallTerritory::$Territories['Tunis'], 'Yes', 'Yes');
InstallTerritory::$Territories['westl. Mittelmeer']->addBorder(InstallTerritory::$Territories['Tunis'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrrhnisches Meer']->addBorder(InstallTerritory::$Territories['Tunis'], 'Yes', 'No');
InstallTerritory::$Territories['Ionisches Meer']->addBorder(InstallTerritory::$Territories['Tunis'], 'Yes', 'No');
InstallTerritory::$Territories['Rom']->addBorder(InstallTerritory::$Territories['Neapel'], 'Yes', 'Yes');
InstallTerritory::$Territories['Apulien']->addBorder(InstallTerritory::$Territories['Neapel'], 'Yes', 'Yes');
InstallTerritory::$Territories['Tyrrhnisches Meer']->addBorder(InstallTerritory::$Territories['Neapel'], 'Yes', 'No');
InstallTerritory::$Territories['Ionisches Meer']->addBorder(InstallTerritory::$Territories['Neapel'], 'Yes', 'No');
InstallTerritory::$Territories['Neapel']->addBorder(InstallTerritory::$Territories['Rom'], 'Yes', 'Yes');
InstallTerritory::$Territories['Toskana']->addBorder(InstallTerritory::$Territories['Rom'], 'Yes', 'Yes');
InstallTerritory::$Territories['Venedig']->addBorder(InstallTerritory::$Territories['Rom'], 'No', 'Yes');
InstallTerritory::$Territories['Apulien']->addBorder(InstallTerritory::$Territories['Rom'], 'No', 'Yes');
InstallTerritory::$Territories['Tyrrhnisches Meer']->addBorder(InstallTerritory::$Territories['Rom'], 'Yes', 'No');
InstallTerritory::$Territories['Rom']->addBorder(InstallTerritory::$Territories['Toskana'], 'Yes', 'Yes');
InstallTerritory::$Territories['Piemont']->addBorder(InstallTerritory::$Territories['Toskana'], 'Yes', 'Yes');
InstallTerritory::$Territories['Venedig']->addBorder(InstallTerritory::$Territories['Toskana'], 'No', 'Yes');
InstallTerritory::$Territories['Golf von Lyon']->addBorder(InstallTerritory::$Territories['Toskana'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrrhnisches Meer']->addBorder(InstallTerritory::$Territories['Toskana'], 'Yes', 'No');
InstallTerritory::$Territories['Toskana']->addBorder(InstallTerritory::$Territories['Piemont'], 'Yes', 'Yes');
InstallTerritory::$Territories['Venedig']->addBorder(InstallTerritory::$Territories['Piemont'], 'No', 'Yes');
InstallTerritory::$Territories['Marsaille']->addBorder(InstallTerritory::$Territories['Piemont'], 'Yes', 'Yes');
InstallTerritory::$Territories['Golf von Lyon']->addBorder(InstallTerritory::$Territories['Piemont'], 'Yes', 'No');
InstallTerritory::$Territories['Tirol']->addBorder(InstallTerritory::$Territories['Piemont'], 'No', 'Yes');
InstallTerritory::$Territories['Rom']->addBorder(InstallTerritory::$Territories['Venedig'], 'No', 'Yes');
InstallTerritory::$Territories['Toskana']->addBorder(InstallTerritory::$Territories['Venedig'], 'No', 'Yes');
InstallTerritory::$Territories['Piemont']->addBorder(InstallTerritory::$Territories['Venedig'], 'No', 'Yes');
InstallTerritory::$Territories['Apulien']->addBorder(InstallTerritory::$Territories['Venedig'], 'Yes', 'Yes');
InstallTerritory::$Territories['Adriatisches Meer']->addBorder(InstallTerritory::$Territories['Venedig'], 'Yes', 'No');
InstallTerritory::$Territories['Tirol']->addBorder(InstallTerritory::$Territories['Venedig'], 'No', 'Yes');
InstallTerritory::$Territories['Triest']->addBorder(InstallTerritory::$Territories['Venedig'], 'Yes', 'Yes');
InstallTerritory::$Territories['Neapel']->addBorder(InstallTerritory::$Territories['Apulien'], 'Yes', 'Yes');
InstallTerritory::$Territories['Rom']->addBorder(InstallTerritory::$Territories['Apulien'], 'No', 'Yes');
InstallTerritory::$Territories['Venedig']->addBorder(InstallTerritory::$Territories['Apulien'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ionisches Meer']->addBorder(InstallTerritory::$Territories['Apulien'], 'Yes', 'No');
InstallTerritory::$Territories['Adriatisches Meer']->addBorder(InstallTerritory::$Territories['Apulien'], 'Yes', 'No');
InstallTerritory::$Territories['Albanien']->addBorder(InstallTerritory::$Territories['Griechenland'], 'Yes', 'Yes');
InstallTerritory::$Territories['Serbien']->addBorder(InstallTerritory::$Territories['Griechenland'], 'No', 'Yes');
InstallTerritory::$Territories['Bulgarien']->addBorder(InstallTerritory::$Territories['Griechenland'], 'No', 'Yes');
InstallTerritory::$Territories['Ionisches Meer']->addBorder(InstallTerritory::$Territories['Griechenland'], 'Yes', 'No');
InstallTerritory::$Territories['&Auml;g&auml;isches Meer']->addBorder(InstallTerritory::$Territories['Griechenland'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgarien (South Coast)']->addBorder(InstallTerritory::$Territories['Griechenland'], 'Yes', 'No');
InstallTerritory::$Territories['Griechenland']->addBorder(InstallTerritory::$Territories['Albanien'], 'Yes', 'Yes');
InstallTerritory::$Territories['Serbien']->addBorder(InstallTerritory::$Territories['Albanien'], 'No', 'Yes');
InstallTerritory::$Territories['Ionisches Meer']->addBorder(InstallTerritory::$Territories['Albanien'], 'Yes', 'No');
InstallTerritory::$Territories['Adriatisches Meer']->addBorder(InstallTerritory::$Territories['Albanien'], 'Yes', 'No');
InstallTerritory::$Territories['Triest']->addBorder(InstallTerritory::$Territories['Albanien'], 'Yes', 'Yes');
InstallTerritory::$Territories['Griechenland']->addBorder(InstallTerritory::$Territories['Serbien'], 'No', 'Yes');
InstallTerritory::$Territories['Albanien']->addBorder(InstallTerritory::$Territories['Serbien'], 'No', 'Yes');
InstallTerritory::$Territories['Bulgarien']->addBorder(InstallTerritory::$Territories['Serbien'], 'No', 'Yes');
InstallTerritory::$Territories['Rum&auml;nien']->addBorder(InstallTerritory::$Territories['Serbien'], 'No', 'Yes');
InstallTerritory::$Territories['Triest']->addBorder(InstallTerritory::$Territories['Serbien'], 'No', 'Yes');
InstallTerritory::$Territories['Budapest']->addBorder(InstallTerritory::$Territories['Serbien'], 'No', 'Yes');
InstallTerritory::$Territories['Griechenland']->addBorder(InstallTerritory::$Territories['Bulgarien'], 'No', 'Yes');
InstallTerritory::$Territories['Serbien']->addBorder(InstallTerritory::$Territories['Bulgarien'], 'No', 'Yes');
InstallTerritory::$Territories['Rum&auml;nien']->addBorder(InstallTerritory::$Territories['Bulgarien'], 'No', 'Yes');
InstallTerritory::$Territories['Konstantinopel']->addBorder(InstallTerritory::$Territories['Bulgarien'], 'No', 'Yes');
InstallTerritory::$Territories['Serbien']->addBorder(InstallTerritory::$Territories['Rum&auml;nien'], 'No', 'Yes');
InstallTerritory::$Territories['Bulgarien']->addBorder(InstallTerritory::$Territories['Rum&auml;nien'], 'No', 'Yes');
InstallTerritory::$Territories['Sewastopol']->addBorder(InstallTerritory::$Territories['Rum&auml;nien'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ukraine']->addBorder(InstallTerritory::$Territories['Rum&auml;nien'], 'No', 'Yes');
InstallTerritory::$Territories['Schwarzes Meer']->addBorder(InstallTerritory::$Territories['Rum&auml;nien'], 'Yes', 'No');
InstallTerritory::$Territories['Budapest']->addBorder(InstallTerritory::$Territories['Rum&auml;nien'], 'No', 'Yes');
InstallTerritory::$Territories['Galizien']->addBorder(InstallTerritory::$Territories['Rum&auml;nien'], 'No', 'Yes');
InstallTerritory::$Territories['Bulgarien (North Coast)']->addBorder(InstallTerritory::$Territories['Rum&auml;nien'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgarien']->addBorder(InstallTerritory::$Territories['Konstantinopel'], 'No', 'Yes');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['Konstantinopel'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ankara']->addBorder(InstallTerritory::$Territories['Konstantinopel'], 'Yes', 'Yes');
InstallTerritory::$Territories['&Auml;g&auml;isches Meer']->addBorder(InstallTerritory::$Territories['Konstantinopel'], 'Yes', 'No');
InstallTerritory::$Territories['Schwarzes Meer']->addBorder(InstallTerritory::$Territories['Konstantinopel'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgarien (North Coast)']->addBorder(InstallTerritory::$Territories['Konstantinopel'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgarien (South Coast)']->addBorder(InstallTerritory::$Territories['Konstantinopel'], 'Yes', 'No');
InstallTerritory::$Territories['Konstantinopel']->addBorder(InstallTerritory::$Territories['Smyrna'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ankara']->addBorder(InstallTerritory::$Territories['Smyrna'], 'No', 'Yes');
InstallTerritory::$Territories['Armenien']->addBorder(InstallTerritory::$Territories['Smyrna'], 'No', 'Yes');
InstallTerritory::$Territories['Syrien']->addBorder(InstallTerritory::$Territories['Smyrna'], 'Yes', 'Yes');
InstallTerritory::$Territories['&Auml;g&auml;isches Meer']->addBorder(InstallTerritory::$Territories['Smyrna'], 'Yes', 'No');
InstallTerritory::$Territories['oestl. Mittelmeer']->addBorder(InstallTerritory::$Territories['Smyrna'], 'Yes', 'No');
InstallTerritory::$Territories['Konstantinopel']->addBorder(InstallTerritory::$Territories['Ankara'], 'Yes', 'Yes');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['Ankara'], 'No', 'Yes');
InstallTerritory::$Territories['Armenien']->addBorder(InstallTerritory::$Territories['Ankara'], 'Yes', 'Yes');
InstallTerritory::$Territories['Schwarzes Meer']->addBorder(InstallTerritory::$Territories['Ankara'], 'Yes', 'No');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['Armenien'], 'No', 'Yes');
InstallTerritory::$Territories['Ankara']->addBorder(InstallTerritory::$Territories['Armenien'], 'Yes', 'Yes');
InstallTerritory::$Territories['Syrien']->addBorder(InstallTerritory::$Territories['Armenien'], 'No', 'Yes');
InstallTerritory::$Territories['Sewastopol']->addBorder(InstallTerritory::$Territories['Armenien'], 'Yes', 'Yes');
InstallTerritory::$Territories['Schwarzes Meer']->addBorder(InstallTerritory::$Territories['Armenien'], 'Yes', 'No');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['Syrien'], 'Yes', 'Yes');
InstallTerritory::$Territories['Armenien']->addBorder(InstallTerritory::$Territories['Syrien'], 'No', 'Yes');
InstallTerritory::$Territories['oestl. Mittelmeer']->addBorder(InstallTerritory::$Territories['Syrien'], 'Yes', 'No');
InstallTerritory::$Territories['Rum&auml;nien']->addBorder(InstallTerritory::$Territories['Sewastopol'], 'Yes', 'Yes');
InstallTerritory::$Territories['Armenien']->addBorder(InstallTerritory::$Territories['Sewastopol'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ukraine']->addBorder(InstallTerritory::$Territories['Sewastopol'], 'No', 'Yes');
InstallTerritory::$Territories['Moskau']->addBorder(InstallTerritory::$Territories['Sewastopol'], 'No', 'Yes');
InstallTerritory::$Territories['Schwarzes Meer']->addBorder(InstallTerritory::$Territories['Sewastopol'], 'Yes', 'No');
InstallTerritory::$Territories['Rum&auml;nien']->addBorder(InstallTerritory::$Territories['Ukraine'], 'No', 'Yes');
InstallTerritory::$Territories['Sewastopol']->addBorder(InstallTerritory::$Territories['Ukraine'], 'No', 'Yes');
InstallTerritory::$Territories['Warschau']->addBorder(InstallTerritory::$Territories['Ukraine'], 'No', 'Yes');
InstallTerritory::$Territories['Moskau']->addBorder(InstallTerritory::$Territories['Ukraine'], 'No', 'Yes');
InstallTerritory::$Territories['Galizien']->addBorder(InstallTerritory::$Territories['Ukraine'], 'No', 'Yes');
InstallTerritory::$Territories['Ukraine']->addBorder(InstallTerritory::$Territories['Warschau'], 'No', 'Yes');
InstallTerritory::$Territories['Livland']->addBorder(InstallTerritory::$Territories['Warschau'], 'No', 'Yes');
InstallTerritory::$Territories['Moskau']->addBorder(InstallTerritory::$Territories['Warschau'], 'No', 'Yes');
InstallTerritory::$Territories['Preu&szlig;en']->addBorder(InstallTerritory::$Territories['Warschau'], 'No', 'Yes');
InstallTerritory::$Territories['Schlesien']->addBorder(InstallTerritory::$Territories['Warschau'], 'No', 'Yes');
InstallTerritory::$Territories['Galizien']->addBorder(InstallTerritory::$Territories['Warschau'], 'No', 'Yes');
InstallTerritory::$Territories['Warschau']->addBorder(InstallTerritory::$Territories['Livland'], 'No', 'Yes');
InstallTerritory::$Territories['Moskau']->addBorder(InstallTerritory::$Territories['Livland'], 'No', 'Yes');
InstallTerritory::$Territories['St. Petersburg']->addBorder(InstallTerritory::$Territories['Livland'], 'No', 'Yes');
InstallTerritory::$Territories['Preu&szlig;en']->addBorder(InstallTerritory::$Territories['Livland'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ostsee']->addBorder(InstallTerritory::$Territories['Livland'], 'Yes', 'No');
InstallTerritory::$Territories['Bottn. Meerbusen']->addBorder(InstallTerritory::$Territories['Livland'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg (South Coast)']->addBorder(InstallTerritory::$Territories['Livland'], 'Yes', 'No');
InstallTerritory::$Territories['Sewastopol']->addBorder(InstallTerritory::$Territories['Moskau'], 'No', 'Yes');
InstallTerritory::$Territories['Ukraine']->addBorder(InstallTerritory::$Territories['Moskau'], 'No', 'Yes');
InstallTerritory::$Territories['Warschau']->addBorder(InstallTerritory::$Territories['Moskau'], 'No', 'Yes');
InstallTerritory::$Territories['Livland']->addBorder(InstallTerritory::$Territories['Moskau'], 'No', 'Yes');
InstallTerritory::$Territories['St. Petersburg']->addBorder(InstallTerritory::$Territories['Moskau'], 'No', 'Yes');
InstallTerritory::$Territories['Livland']->addBorder(InstallTerritory::$Territories['St. Petersburg'], 'No', 'Yes');
InstallTerritory::$Territories['Moskau']->addBorder(InstallTerritory::$Territories['St. Petersburg'], 'No', 'Yes');
InstallTerritory::$Territories['Finnland']->addBorder(InstallTerritory::$Territories['St. Petersburg'], 'No', 'Yes');
InstallTerritory::$Territories['Norwegen']->addBorder(InstallTerritory::$Territories['St. Petersburg'], 'No', 'Yes');
InstallTerritory::$Territories['St. Petersburg']->addBorder(InstallTerritory::$Territories['Finnland'], 'No', 'Yes');
InstallTerritory::$Territories['Schweden']->addBorder(InstallTerritory::$Territories['Finnland'], 'Yes', 'Yes');
InstallTerritory::$Territories['Norwegen']->addBorder(InstallTerritory::$Territories['Finnland'], 'No', 'Yes');
InstallTerritory::$Territories['Bottn. Meerbusen']->addBorder(InstallTerritory::$Territories['Finnland'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg (South Coast)']->addBorder(InstallTerritory::$Territories['Finnland'], 'Yes', 'No');
InstallTerritory::$Territories['Finnland']->addBorder(InstallTerritory::$Territories['Schweden'], 'Yes', 'Yes');
InstallTerritory::$Territories['Norwegen']->addBorder(InstallTerritory::$Territories['Schweden'], 'Yes', 'Yes');
InstallTerritory::$Territories['D&auml;nemark']->addBorder(InstallTerritory::$Territories['Schweden'], 'Yes', 'Yes');
InstallTerritory::$Territories['Skagerak']->addBorder(InstallTerritory::$Territories['Schweden'], 'Yes', 'No');
InstallTerritory::$Territories['Ostsee']->addBorder(InstallTerritory::$Territories['Schweden'], 'Yes', 'No');
InstallTerritory::$Territories['Bottn. Meerbusen']->addBorder(InstallTerritory::$Territories['Schweden'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg']->addBorder(InstallTerritory::$Territories['Norwegen'], 'No', 'Yes');
InstallTerritory::$Territories['Finnland']->addBorder(InstallTerritory::$Territories['Norwegen'], 'No', 'Yes');
InstallTerritory::$Territories['Schweden']->addBorder(InstallTerritory::$Territories['Norwegen'], 'Yes', 'Yes');
InstallTerritory::$Territories['Barentssee']->addBorder(InstallTerritory::$Territories['Norwegen'], 'Yes', 'No');
InstallTerritory::$Territories['Nordmeer']->addBorder(InstallTerritory::$Territories['Norwegen'], 'Yes', 'No');
InstallTerritory::$Territories['Nordsee']->addBorder(InstallTerritory::$Territories['Norwegen'], 'Yes', 'No');
InstallTerritory::$Territories['Skagerak']->addBorder(InstallTerritory::$Territories['Norwegen'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg (North Coast)']->addBorder(InstallTerritory::$Territories['Norwegen'], 'Yes', 'No');
InstallTerritory::$Territories['Schweden']->addBorder(InstallTerritory::$Territories['D&auml;nemark'], 'Yes', 'Yes');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['D&auml;nemark'], 'Yes', 'Yes');
InstallTerritory::$Territories['Nordsee']->addBorder(InstallTerritory::$Territories['D&auml;nemark'], 'Yes', 'No');
InstallTerritory::$Territories['Skagerak']->addBorder(InstallTerritory::$Territories['D&auml;nemark'], 'Yes', 'No');
InstallTerritory::$Territories['Helgonlaender Bucht']->addBorder(InstallTerritory::$Territories['D&auml;nemark'], 'Yes', 'No');
InstallTerritory::$Territories['Ostsee']->addBorder(InstallTerritory::$Territories['D&auml;nemark'], 'Yes', 'No');
InstallTerritory::$Territories['D&auml;nemark']->addBorder(InstallTerritory::$Territories['Kiel'], 'Yes', 'Yes');
InstallTerritory::$Territories['Berlin']->addBorder(InstallTerritory::$Territories['Kiel'], 'Yes', 'Yes');
InstallTerritory::$Territories['M&uuml;nchen']->addBorder(InstallTerritory::$Territories['Kiel'], 'No', 'Yes');
InstallTerritory::$Territories['Ruhr']->addBorder(InstallTerritory::$Territories['Kiel'], 'No', 'Yes');
InstallTerritory::$Territories['Holland']->addBorder(InstallTerritory::$Territories['Kiel'], 'Yes', 'Yes');
InstallTerritory::$Territories['Helgonlaender Bucht']->addBorder(InstallTerritory::$Territories['Kiel'], 'Yes', 'No');
InstallTerritory::$Territories['Ostsee']->addBorder(InstallTerritory::$Territories['Kiel'], 'Yes', 'No');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Berlin'], 'Yes', 'Yes');
InstallTerritory::$Territories['Preu&szlig;en']->addBorder(InstallTerritory::$Territories['Berlin'], 'Yes', 'Yes');
InstallTerritory::$Territories['Schlesien']->addBorder(InstallTerritory::$Territories['Berlin'], 'No', 'Yes');
InstallTerritory::$Territories['M&uuml;nchen']->addBorder(InstallTerritory::$Territories['Berlin'], 'No', 'Yes');
InstallTerritory::$Territories['Ostsee']->addBorder(InstallTerritory::$Territories['Berlin'], 'Yes', 'No');
InstallTerritory::$Territories['Warschau']->addBorder(InstallTerritory::$Territories['Preu&szlig;en'], 'No', 'Yes');
InstallTerritory::$Territories['Livland']->addBorder(InstallTerritory::$Territories['Preu&szlig;en'], 'Yes', 'Yes');
InstallTerritory::$Territories['Berlin']->addBorder(InstallTerritory::$Territories['Preu&szlig;en'], 'Yes', 'Yes');
InstallTerritory::$Territories['Schlesien']->addBorder(InstallTerritory::$Territories['Preu&szlig;en'], 'No', 'Yes');
InstallTerritory::$Territories['Ostsee']->addBorder(InstallTerritory::$Territories['Preu&szlig;en'], 'Yes', 'No');
InstallTerritory::$Territories['Warschau']->addBorder(InstallTerritory::$Territories['Schlesien'], 'No', 'Yes');
InstallTerritory::$Territories['Berlin']->addBorder(InstallTerritory::$Territories['Schlesien'], 'No', 'Yes');
InstallTerritory::$Territories['Preu&szlig;en']->addBorder(InstallTerritory::$Territories['Schlesien'], 'No', 'Yes');
InstallTerritory::$Territories['M&uuml;nchen']->addBorder(InstallTerritory::$Territories['Schlesien'], 'No', 'Yes');
InstallTerritory::$Territories['B&ouml;hmen']->addBorder(InstallTerritory::$Territories['Schlesien'], 'No', 'Yes');
InstallTerritory::$Territories['Galizien']->addBorder(InstallTerritory::$Territories['Schlesien'], 'No', 'Yes');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['M&uuml;nchen'], 'No', 'Yes');
InstallTerritory::$Territories['Berlin']->addBorder(InstallTerritory::$Territories['M&uuml;nchen'], 'No', 'Yes');
InstallTerritory::$Territories['Schlesien']->addBorder(InstallTerritory::$Territories['M&uuml;nchen'], 'No', 'Yes');
InstallTerritory::$Territories['Ruhr']->addBorder(InstallTerritory::$Territories['M&uuml;nchen'], 'No', 'Yes');
InstallTerritory::$Territories['Burgund']->addBorder(InstallTerritory::$Territories['M&uuml;nchen'], 'No', 'Yes');
InstallTerritory::$Territories['Tirol']->addBorder(InstallTerritory::$Territories['M&uuml;nchen'], 'No', 'Yes');
InstallTerritory::$Territories['B&ouml;hmen']->addBorder(InstallTerritory::$Territories['M&uuml;nchen'], 'No', 'Yes');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Ruhr'], 'No', 'Yes');
InstallTerritory::$Territories['M&uuml;nchen']->addBorder(InstallTerritory::$Territories['Ruhr'], 'No', 'Yes');
InstallTerritory::$Territories['Holland']->addBorder(InstallTerritory::$Territories['Ruhr'], 'No', 'Yes');
InstallTerritory::$Territories['Belgien']->addBorder(InstallTerritory::$Territories['Ruhr'], 'No', 'Yes');
InstallTerritory::$Territories['Burgund']->addBorder(InstallTerritory::$Territories['Ruhr'], 'No', 'Yes');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Holland'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ruhr']->addBorder(InstallTerritory::$Territories['Holland'], 'No', 'Yes');
InstallTerritory::$Territories['Belgien']->addBorder(InstallTerritory::$Territories['Holland'], 'Yes', 'Yes');
InstallTerritory::$Territories['Nordsee']->addBorder(InstallTerritory::$Territories['Holland'], 'Yes', 'No');
InstallTerritory::$Territories['Helgonlaender Bucht']->addBorder(InstallTerritory::$Territories['Holland'], 'Yes', 'No');
InstallTerritory::$Territories['Ruhr']->addBorder(InstallTerritory::$Territories['Belgien'], 'No', 'Yes');
InstallTerritory::$Territories['Holland']->addBorder(InstallTerritory::$Territories['Belgien'], 'Yes', 'Yes');
InstallTerritory::$Territories['Pikardie']->addBorder(InstallTerritory::$Territories['Belgien'], 'Yes', 'Yes');
InstallTerritory::$Territories['Burgund']->addBorder(InstallTerritory::$Territories['Belgien'], 'No', 'Yes');
InstallTerritory::$Territories['Nordsee']->addBorder(InstallTerritory::$Territories['Belgien'], 'Yes', 'No');
InstallTerritory::$Territories['Kanal']->addBorder(InstallTerritory::$Territories['Belgien'], 'Yes', 'No');
InstallTerritory::$Territories['Belgien']->addBorder(InstallTerritory::$Territories['Pikardie'], 'Yes', 'Yes');
InstallTerritory::$Territories['Brest']->addBorder(InstallTerritory::$Territories['Pikardie'], 'Yes', 'Yes');
InstallTerritory::$Territories['Paris']->addBorder(InstallTerritory::$Territories['Pikardie'], 'No', 'Yes');
InstallTerritory::$Territories['Burgund']->addBorder(InstallTerritory::$Territories['Pikardie'], 'No', 'Yes');
InstallTerritory::$Territories['Kanal']->addBorder(InstallTerritory::$Territories['Pikardie'], 'Yes', 'No');
InstallTerritory::$Territories['Pikardie']->addBorder(InstallTerritory::$Territories['Brest'], 'Yes', 'Yes');
InstallTerritory::$Territories['Paris']->addBorder(InstallTerritory::$Territories['Brest'], 'No', 'Yes');
InstallTerritory::$Territories['Gascogne']->addBorder(InstallTerritory::$Territories['Brest'], 'Yes', 'Yes');
InstallTerritory::$Territories['Kanal']->addBorder(InstallTerritory::$Territories['Brest'], 'Yes', 'No');
InstallTerritory::$Territories['Mittel-Atlantik']->addBorder(InstallTerritory::$Territories['Brest'], 'Yes', 'No');
InstallTerritory::$Territories['Pikardie']->addBorder(InstallTerritory::$Territories['Paris'], 'No', 'Yes');
InstallTerritory::$Territories['Brest']->addBorder(InstallTerritory::$Territories['Paris'], 'No', 'Yes');
InstallTerritory::$Territories['Burgund']->addBorder(InstallTerritory::$Territories['Paris'], 'No', 'Yes');
InstallTerritory::$Territories['Gascogne']->addBorder(InstallTerritory::$Territories['Paris'], 'No', 'Yes');
InstallTerritory::$Territories['M&uuml;nchen']->addBorder(InstallTerritory::$Territories['Burgund'], 'No', 'Yes');
InstallTerritory::$Territories['Ruhr']->addBorder(InstallTerritory::$Territories['Burgund'], 'No', 'Yes');
InstallTerritory::$Territories['Belgien']->addBorder(InstallTerritory::$Territories['Burgund'], 'No', 'Yes');
InstallTerritory::$Territories['Pikardie']->addBorder(InstallTerritory::$Territories['Burgund'], 'No', 'Yes');
InstallTerritory::$Territories['Paris']->addBorder(InstallTerritory::$Territories['Burgund'], 'No', 'Yes');
InstallTerritory::$Territories['Marsaille']->addBorder(InstallTerritory::$Territories['Burgund'], 'No', 'Yes');
InstallTerritory::$Territories['Gascogne']->addBorder(InstallTerritory::$Territories['Burgund'], 'No', 'Yes');
InstallTerritory::$Territories['Spanien']->addBorder(InstallTerritory::$Territories['Marsaille'], 'No', 'Yes');
InstallTerritory::$Territories['Piemont']->addBorder(InstallTerritory::$Territories['Marsaille'], 'Yes', 'Yes');
InstallTerritory::$Territories['Burgund']->addBorder(InstallTerritory::$Territories['Marsaille'], 'No', 'Yes');
InstallTerritory::$Territories['Gascogne']->addBorder(InstallTerritory::$Territories['Marsaille'], 'No', 'Yes');
InstallTerritory::$Territories['Golf von Lyon']->addBorder(InstallTerritory::$Territories['Marsaille'], 'Yes', 'No');
InstallTerritory::$Territories['Spanien (South Coast)']->addBorder(InstallTerritory::$Territories['Marsaille'], 'Yes', 'No');
InstallTerritory::$Territories['Spanien']->addBorder(InstallTerritory::$Territories['Gascogne'], 'No', 'Yes');
InstallTerritory::$Territories['Brest']->addBorder(InstallTerritory::$Territories['Gascogne'], 'Yes', 'Yes');
InstallTerritory::$Territories['Paris']->addBorder(InstallTerritory::$Territories['Gascogne'], 'No', 'Yes');
InstallTerritory::$Territories['Burgund']->addBorder(InstallTerritory::$Territories['Gascogne'], 'No', 'Yes');
InstallTerritory::$Territories['Marsaille']->addBorder(InstallTerritory::$Territories['Gascogne'], 'No', 'Yes');
InstallTerritory::$Territories['Mittel-Atlantik']->addBorder(InstallTerritory::$Territories['Gascogne'], 'Yes', 'No');
InstallTerritory::$Territories['Spanien (North Coast)']->addBorder(InstallTerritory::$Territories['Gascogne'], 'Yes', 'No');
InstallTerritory::$Territories['Norwegen']->addBorder(InstallTerritory::$Territories['Barentssee'], 'Yes', 'No');
InstallTerritory::$Territories['Nordmeer']->addBorder(InstallTerritory::$Territories['Barentssee'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg (North Coast)']->addBorder(InstallTerritory::$Territories['Barentssee'], 'Yes', 'No');
InstallTerritory::$Territories['Clyde']->addBorder(InstallTerritory::$Territories['Nordmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Edingburgh']->addBorder(InstallTerritory::$Territories['Nordmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Norwegen']->addBorder(InstallTerritory::$Territories['Nordmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Barentssee']->addBorder(InstallTerritory::$Territories['Nordmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Nordsee']->addBorder(InstallTerritory::$Territories['Nordmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Nord-Atlantik']->addBorder(InstallTerritory::$Territories['Nordmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Edingburgh']->addBorder(InstallTerritory::$Territories['Nordsee'], 'Yes', 'No');
InstallTerritory::$Territories['Yorkshire']->addBorder(InstallTerritory::$Territories['Nordsee'], 'Yes', 'No');
InstallTerritory::$Territories['London']->addBorder(InstallTerritory::$Territories['Nordsee'], 'Yes', 'No');
InstallTerritory::$Territories['Norwegen']->addBorder(InstallTerritory::$Territories['Nordsee'], 'Yes', 'No');
InstallTerritory::$Territories['D&auml;nemark']->addBorder(InstallTerritory::$Territories['Nordsee'], 'Yes', 'No');
InstallTerritory::$Territories['Holland']->addBorder(InstallTerritory::$Territories['Nordsee'], 'Yes', 'No');
InstallTerritory::$Territories['Belgien']->addBorder(InstallTerritory::$Territories['Nordsee'], 'Yes', 'No');
InstallTerritory::$Territories['Nordmeer']->addBorder(InstallTerritory::$Territories['Nordsee'], 'Yes', 'No');
InstallTerritory::$Territories['Skagerak']->addBorder(InstallTerritory::$Territories['Nordsee'], 'Yes', 'No');
InstallTerritory::$Territories['Helgonlaender Bucht']->addBorder(InstallTerritory::$Territories['Nordsee'], 'Yes', 'No');
InstallTerritory::$Territories['Kanal']->addBorder(InstallTerritory::$Territories['Nordsee'], 'Yes', 'No');
InstallTerritory::$Territories['Schweden']->addBorder(InstallTerritory::$Territories['Skagerak'], 'Yes', 'No');
InstallTerritory::$Territories['Norwegen']->addBorder(InstallTerritory::$Territories['Skagerak'], 'Yes', 'No');
InstallTerritory::$Territories['D&auml;nemark']->addBorder(InstallTerritory::$Territories['Skagerak'], 'Yes', 'No');
InstallTerritory::$Territories['Nordsee']->addBorder(InstallTerritory::$Territories['Skagerak'], 'Yes', 'No');
InstallTerritory::$Territories['D&auml;nemark']->addBorder(InstallTerritory::$Territories['Helgonlaender Bucht'], 'Yes', 'No');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Helgonlaender Bucht'], 'Yes', 'No');
InstallTerritory::$Territories['Holland']->addBorder(InstallTerritory::$Territories['Helgonlaender Bucht'], 'Yes', 'No');
InstallTerritory::$Territories['Nordsee']->addBorder(InstallTerritory::$Territories['Helgonlaender Bucht'], 'Yes', 'No');
InstallTerritory::$Territories['Livland']->addBorder(InstallTerritory::$Territories['Ostsee'], 'Yes', 'No');
InstallTerritory::$Territories['Schweden']->addBorder(InstallTerritory::$Territories['Ostsee'], 'Yes', 'No');
InstallTerritory::$Territories['D&auml;nemark']->addBorder(InstallTerritory::$Territories['Ostsee'], 'Yes', 'No');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Ostsee'], 'Yes', 'No');
InstallTerritory::$Territories['Berlin']->addBorder(InstallTerritory::$Territories['Ostsee'], 'Yes', 'No');
InstallTerritory::$Territories['Preu&szlig;en']->addBorder(InstallTerritory::$Territories['Ostsee'], 'Yes', 'No');
InstallTerritory::$Territories['Bottn. Meerbusen']->addBorder(InstallTerritory::$Territories['Ostsee'], 'Yes', 'No');
InstallTerritory::$Territories['Livland']->addBorder(InstallTerritory::$Territories['Bottn. Meerbusen'], 'Yes', 'No');
InstallTerritory::$Territories['Finnland']->addBorder(InstallTerritory::$Territories['Bottn. Meerbusen'], 'Yes', 'No');
InstallTerritory::$Territories['Schweden']->addBorder(InstallTerritory::$Territories['Bottn. Meerbusen'], 'Yes', 'No');
InstallTerritory::$Territories['Ostsee']->addBorder(InstallTerritory::$Territories['Bottn. Meerbusen'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg (South Coast)']->addBorder(InstallTerritory::$Territories['Bottn. Meerbusen'], 'Yes', 'No');
InstallTerritory::$Territories['Clyde']->addBorder(InstallTerritory::$Territories['Nord-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['Nord-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Nordmeer']->addBorder(InstallTerritory::$Territories['Nord-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Irische See']->addBorder(InstallTerritory::$Territories['Nord-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Mittel-Atlantik']->addBorder(InstallTerritory::$Territories['Nord-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['Irische See'], 'Yes', 'No');
InstallTerritory::$Territories['Wales']->addBorder(InstallTerritory::$Territories['Irische See'], 'Yes', 'No');
InstallTerritory::$Territories['Nord-Atlantik']->addBorder(InstallTerritory::$Territories['Irische See'], 'Yes', 'No');
InstallTerritory::$Territories['Kanal']->addBorder(InstallTerritory::$Territories['Irische See'], 'Yes', 'No');
InstallTerritory::$Territories['Mittel-Atlantik']->addBorder(InstallTerritory::$Territories['Irische See'], 'Yes', 'No');
InstallTerritory::$Territories['Wales']->addBorder(InstallTerritory::$Territories['Kanal'], 'Yes', 'No');
InstallTerritory::$Territories['London']->addBorder(InstallTerritory::$Territories['Kanal'], 'Yes', 'No');
InstallTerritory::$Territories['Belgien']->addBorder(InstallTerritory::$Territories['Kanal'], 'Yes', 'No');
InstallTerritory::$Territories['Pikardie']->addBorder(InstallTerritory::$Territories['Kanal'], 'Yes', 'No');
InstallTerritory::$Territories['Brest']->addBorder(InstallTerritory::$Territories['Kanal'], 'Yes', 'No');
InstallTerritory::$Territories['Nordsee']->addBorder(InstallTerritory::$Territories['Kanal'], 'Yes', 'No');
InstallTerritory::$Territories['Irische See']->addBorder(InstallTerritory::$Territories['Kanal'], 'Yes', 'No');
InstallTerritory::$Territories['Mittel-Atlantik']->addBorder(InstallTerritory::$Territories['Kanal'], 'Yes', 'No');
InstallTerritory::$Territories['Portugal']->addBorder(InstallTerritory::$Territories['Mittel-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Nord Afrika']->addBorder(InstallTerritory::$Territories['Mittel-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Brest']->addBorder(InstallTerritory::$Territories['Mittel-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Gascogne']->addBorder(InstallTerritory::$Territories['Mittel-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Nord-Atlantik']->addBorder(InstallTerritory::$Territories['Mittel-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Irische See']->addBorder(InstallTerritory::$Territories['Mittel-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Kanal']->addBorder(InstallTerritory::$Territories['Mittel-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['westl. Mittelmeer']->addBorder(InstallTerritory::$Territories['Mittel-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Spanien (North Coast)']->addBorder(InstallTerritory::$Territories['Mittel-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Spanien (South Coast)']->addBorder(InstallTerritory::$Territories['Mittel-Atlantik'], 'Yes', 'No');
InstallTerritory::$Territories['Nord Afrika']->addBorder(InstallTerritory::$Territories['westl. Mittelmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Tunis']->addBorder(InstallTerritory::$Territories['westl. Mittelmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Mittel-Atlantik']->addBorder(InstallTerritory::$Territories['westl. Mittelmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Golf von Lyon']->addBorder(InstallTerritory::$Territories['westl. Mittelmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrrhnisches Meer']->addBorder(InstallTerritory::$Territories['westl. Mittelmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Spanien (South Coast)']->addBorder(InstallTerritory::$Territories['westl. Mittelmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Toskana']->addBorder(InstallTerritory::$Territories['Golf von Lyon'], 'Yes', 'No');
InstallTerritory::$Territories['Piemont']->addBorder(InstallTerritory::$Territories['Golf von Lyon'], 'Yes', 'No');
InstallTerritory::$Territories['Marsaille']->addBorder(InstallTerritory::$Territories['Golf von Lyon'], 'Yes', 'No');
InstallTerritory::$Territories['westl. Mittelmeer']->addBorder(InstallTerritory::$Territories['Golf von Lyon'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrrhnisches Meer']->addBorder(InstallTerritory::$Territories['Golf von Lyon'], 'Yes', 'No');
InstallTerritory::$Territories['Spanien (South Coast)']->addBorder(InstallTerritory::$Territories['Golf von Lyon'], 'Yes', 'No');
InstallTerritory::$Territories['Tunis']->addBorder(InstallTerritory::$Territories['Tyrrhnisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Neapel']->addBorder(InstallTerritory::$Territories['Tyrrhnisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Rom']->addBorder(InstallTerritory::$Territories['Tyrrhnisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Toskana']->addBorder(InstallTerritory::$Territories['Tyrrhnisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['westl. Mittelmeer']->addBorder(InstallTerritory::$Territories['Tyrrhnisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Golf von Lyon']->addBorder(InstallTerritory::$Territories['Tyrrhnisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Ionisches Meer']->addBorder(InstallTerritory::$Territories['Tyrrhnisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Tunis']->addBorder(InstallTerritory::$Territories['Ionisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Neapel']->addBorder(InstallTerritory::$Territories['Ionisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Apulien']->addBorder(InstallTerritory::$Territories['Ionisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Griechenland']->addBorder(InstallTerritory::$Territories['Ionisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Albanien']->addBorder(InstallTerritory::$Territories['Ionisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrrhnisches Meer']->addBorder(InstallTerritory::$Territories['Ionisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Adriatisches Meer']->addBorder(InstallTerritory::$Territories['Ionisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['&Auml;g&auml;isches Meer']->addBorder(InstallTerritory::$Territories['Ionisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['oestl. Mittelmeer']->addBorder(InstallTerritory::$Territories['Ionisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Venedig']->addBorder(InstallTerritory::$Territories['Adriatisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Apulien']->addBorder(InstallTerritory::$Territories['Adriatisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Albanien']->addBorder(InstallTerritory::$Territories['Adriatisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Ionisches Meer']->addBorder(InstallTerritory::$Territories['Adriatisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Triest']->addBorder(InstallTerritory::$Territories['Adriatisches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Griechenland']->addBorder(InstallTerritory::$Territories['&Auml;g&auml;isches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Konstantinopel']->addBorder(InstallTerritory::$Territories['&Auml;g&auml;isches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['&Auml;g&auml;isches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Ionisches Meer']->addBorder(InstallTerritory::$Territories['&Auml;g&auml;isches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['oestl. Mittelmeer']->addBorder(InstallTerritory::$Territories['&Auml;g&auml;isches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgarien (South Coast)']->addBorder(InstallTerritory::$Territories['&Auml;g&auml;isches Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['oestl. Mittelmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Syrien']->addBorder(InstallTerritory::$Territories['oestl. Mittelmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Ionisches Meer']->addBorder(InstallTerritory::$Territories['oestl. Mittelmeer'], 'Yes', 'No');
InstallTerritory::$Territories['&Auml;g&auml;isches Meer']->addBorder(InstallTerritory::$Territories['oestl. Mittelmeer'], 'Yes', 'No');
InstallTerritory::$Territories['Rum&auml;nien']->addBorder(InstallTerritory::$Territories['Schwarzes Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Konstantinopel']->addBorder(InstallTerritory::$Territories['Schwarzes Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Ankara']->addBorder(InstallTerritory::$Territories['Schwarzes Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Armenien']->addBorder(InstallTerritory::$Territories['Schwarzes Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Sewastopol']->addBorder(InstallTerritory::$Territories['Schwarzes Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgarien (North Coast)']->addBorder(InstallTerritory::$Territories['Schwarzes Meer'], 'Yes', 'No');
InstallTerritory::$Territories['Piemont']->addBorder(InstallTerritory::$Territories['Tirol'], 'No', 'Yes');
InstallTerritory::$Territories['Venedig']->addBorder(InstallTerritory::$Territories['Tirol'], 'No', 'Yes');
InstallTerritory::$Territories['M&uuml;nchen']->addBorder(InstallTerritory::$Territories['Tirol'], 'No', 'Yes');
InstallTerritory::$Territories['B&ouml;hmen']->addBorder(InstallTerritory::$Territories['Tirol'], 'No', 'Yes');
InstallTerritory::$Territories['Wien']->addBorder(InstallTerritory::$Territories['Tirol'], 'No', 'Yes');
InstallTerritory::$Territories['Triest']->addBorder(InstallTerritory::$Territories['Tirol'], 'No', 'Yes');
InstallTerritory::$Territories['Schlesien']->addBorder(InstallTerritory::$Territories['B&ouml;hmen'], 'No', 'Yes');
InstallTerritory::$Territories['M&uuml;nchen']->addBorder(InstallTerritory::$Territories['B&ouml;hmen'], 'No', 'Yes');
InstallTerritory::$Territories['Tirol']->addBorder(InstallTerritory::$Territories['B&ouml;hmen'], 'No', 'Yes');
InstallTerritory::$Territories['Wien']->addBorder(InstallTerritory::$Territories['B&ouml;hmen'], 'No', 'Yes');
InstallTerritory::$Territories['Galizien']->addBorder(InstallTerritory::$Territories['B&ouml;hmen'], 'No', 'Yes');
InstallTerritory::$Territories['Tirol']->addBorder(InstallTerritory::$Territories['Wien'], 'No', 'Yes');
InstallTerritory::$Territories['B&ouml;hmen']->addBorder(InstallTerritory::$Territories['Wien'], 'No', 'Yes');
InstallTerritory::$Territories['Triest']->addBorder(InstallTerritory::$Territories['Wien'], 'No', 'Yes');
InstallTerritory::$Territories['Budapest']->addBorder(InstallTerritory::$Territories['Wien'], 'No', 'Yes');
InstallTerritory::$Territories['Galizien']->addBorder(InstallTerritory::$Territories['Wien'], 'No', 'Yes');
InstallTerritory::$Territories['Venedig']->addBorder(InstallTerritory::$Territories['Triest'], 'Yes', 'Yes');
InstallTerritory::$Territories['Albanien']->addBorder(InstallTerritory::$Territories['Triest'], 'Yes', 'Yes');
InstallTerritory::$Territories['Serbien']->addBorder(InstallTerritory::$Territories['Triest'], 'No', 'Yes');
InstallTerritory::$Territories['Adriatisches Meer']->addBorder(InstallTerritory::$Territories['Triest'], 'Yes', 'No');
InstallTerritory::$Territories['Tirol']->addBorder(InstallTerritory::$Territories['Triest'], 'No', 'Yes');
InstallTerritory::$Territories['Wien']->addBorder(InstallTerritory::$Territories['Triest'], 'No', 'Yes');
InstallTerritory::$Territories['Budapest']->addBorder(InstallTerritory::$Territories['Triest'], 'No', 'Yes');
InstallTerritory::$Territories['Serbien']->addBorder(InstallTerritory::$Territories['Budapest'], 'No', 'Yes');
InstallTerritory::$Territories['Rum&auml;nien']->addBorder(InstallTerritory::$Territories['Budapest'], 'No', 'Yes');
InstallTerritory::$Territories['Wien']->addBorder(InstallTerritory::$Territories['Budapest'], 'No', 'Yes');
InstallTerritory::$Territories['Triest']->addBorder(InstallTerritory::$Territories['Budapest'], 'No', 'Yes');
InstallTerritory::$Territories['Galizien']->addBorder(InstallTerritory::$Territories['Budapest'], 'No', 'Yes');
InstallTerritory::$Territories['Rum&auml;nien']->addBorder(InstallTerritory::$Territories['Galizien'], 'No', 'Yes');
InstallTerritory::$Territories['Ukraine']->addBorder(InstallTerritory::$Territories['Galizien'], 'No', 'Yes');
InstallTerritory::$Territories['Warschau']->addBorder(InstallTerritory::$Territories['Galizien'], 'No', 'Yes');
InstallTerritory::$Territories['Schlesien']->addBorder(InstallTerritory::$Territories['Galizien'], 'No', 'Yes');
InstallTerritory::$Territories['B&ouml;hmen']->addBorder(InstallTerritory::$Territories['Galizien'], 'No', 'Yes');
InstallTerritory::$Territories['Wien']->addBorder(InstallTerritory::$Territories['Galizien'], 'No', 'Yes');
InstallTerritory::$Territories['Budapest']->addBorder(InstallTerritory::$Territories['Galizien'], 'No', 'Yes');
InstallTerritory::$Territories['Portugal']->addBorder(InstallTerritory::$Territories['Spanien (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Gascogne']->addBorder(InstallTerritory::$Territories['Spanien (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Mittel-Atlantik']->addBorder(InstallTerritory::$Territories['Spanien (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Portugal']->addBorder(InstallTerritory::$Territories['Spanien (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Marsaille']->addBorder(InstallTerritory::$Territories['Spanien (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Mittel-Atlantik']->addBorder(InstallTerritory::$Territories['Spanien (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['westl. Mittelmeer']->addBorder(InstallTerritory::$Territories['Spanien (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Golf von Lyon']->addBorder(InstallTerritory::$Territories['Spanien (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Norwegen']->addBorder(InstallTerritory::$Territories['St. Petersburg (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Barentssee']->addBorder(InstallTerritory::$Territories['St. Petersburg (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Livland']->addBorder(InstallTerritory::$Territories['St. Petersburg (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Finnland']->addBorder(InstallTerritory::$Territories['St. Petersburg (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Bottn. Meerbusen']->addBorder(InstallTerritory::$Territories['St. Petersburg (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Rum&auml;nien']->addBorder(InstallTerritory::$Territories['Bulgarien (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Konstantinopel']->addBorder(InstallTerritory::$Territories['Bulgarien (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Schwarzes Meer']->addBorder(InstallTerritory::$Territories['Bulgarien (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Griechenland']->addBorder(InstallTerritory::$Territories['Bulgarien (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Konstantinopel']->addBorder(InstallTerritory::$Territories['Bulgarien (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['&Auml;g&auml;isches Meer']->addBorder(InstallTerritory::$Territories['Bulgarien (South Coast)'], 'Yes', 'No');

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

?>
