<?php
// This file will install the map data for the SouthAmerica8 variant

require_once("variants/install.php");
InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Buenos Aires', 'Coast', 'Yes', 425, 699, 253, 411, 'Argentinien'),
	array('Salta', 'Land', 'Yes', 312, 552, 183, 319, 'Argentinien'),
	array('Cordoba', 'Land', 'Yes', 315, 685, 188, 402, 'Argentinien'),
	array('Patagonien', 'Coast', 'Yes', 342, 871, 208, 507, 'Neutral'),
	array('San Miguel de Tucuman', 'Land', 'Yes', 345, 605, 184, 358, 'Neutral'),
	array('Corrientes', 'Coast', 'Yes', 402, 616, 244, 363, 'Neutral'),
	array('Bahia Blanca', 'Coast', 'No', 386, 765, 239, 436, 'Argentinien'),
	array('Rosario', 'Land', 'No', 366, 690, 218, 406, 'Argentinien'),
	array('Mendoza', 'Land', 'No', 315, 722, 187, 421, 'Argentinien'),
	array('Santa Fe', 'Coast', 'No', 380, 640, 242, 384, 'Argentinien'),
	array('Antofagasta', 'Coast', 'Yes', 252, 541, 147, 305, 'Bolivien'),
	array('La Paz', 'Land', 'Yes', 274, 460, 164, 254, 'Bolivien'),
	array('Santa Cruz', 'Land', 'Yes', 350, 457, 203, 248, 'Neutral'),
	array('Potosi', 'Land', 'Yes', 315, 485, 185, 284, 'Neutral'),
	array('Atacama', 'Coast', 'No', 243, 475, 145, 275, 'Bolivien'),
	array('Riberalta', 'Land', 'No', 280, 375, 167, 219, 'Bolivien'),
	array('Salvador', 'Coast', 'Yes', 620, 406, 382, 247, 'Brasilien'),
	array('Rio de Janeiro', 'Coast', 'Yes', 638, 484, 373, 291, 'Brasilien'),
	array('Sao Paulo', 'Coast', 'Yes', 555, 550, 325, 325, 'Brasilien'),
	array('Manaus', 'Coast', 'Yes', 383, 270, 227, 147, 'Brasilien'),
	array('Maranhao', 'Coast', 'Yes', 552, 226, 326, 137, 'Neutral'),
	array('Rio Grande do Sul', 'Coast', 'Yes', 523, 619, 308, 366, 'Neutral'),
	array('Parana', 'Coast', 'Yes', 504, 570, 298, 332, 'Neutral'),
	array('Aquiris Ureinwohner-Territorium', 'Land', 'Yes', 270, 328, 157, 196, 'Neutral'),
	array('Para', 'Coast', 'No', 466, 200, 278, 118, 'Brasilien'),
	array('Pernambuco', 'Coast', 'No', 641, 281, 383, 167, 'Brasilien'),
	array('Mato Grosso', 'Coast', 'No', 423, 335, 256, 210, 'Brasilien'),
	array('Amazonas', 'Coast', 'No', 281, 260, 168, 138, 'Brasilien'),
	array('Guapore', 'Coast', 'No', 317, 335, 189, 199, 'Brasilien'),
	array('Pantanal', 'Coast', 'No', 450, 490, 265, 282, 'Brasilien'),
	array('Rio Branco', 'Land', 'No', 344, 155, 204, 93, 'Brasilien'),
	array('Goias', 'Land', 'No', 515, 430, 302, 254, 'Brasilien'),
	array('Minas Gerais', 'Land', 'No', 572, 485, 342, 271, 'Brasilien'),
	array('Santiago de Chile', 'Coast', 'Yes', 266, 724, 157, 423, 'Chile'),
	array('Valparaiso', 'Coast', 'Yes', 265, 681, 153, 391, 'Chile'),
	array('Punta Arenas', 'Coast', 'Yes', 330, 940, 221, 558, 'Neutral'),
	array('Copiapo', 'Coast', 'No', 263, 576, 152, 345, 'Chile'),
	array('Arauncanian Ureinwohner-Territorium', 'Coast', 'No', 298, 883, 170, 483, 'Chile'),
	array('Cartagena', 'Coast', 'Yes', 147, 68, 92, 38, 'Kolumbien'),
	array('Cali', 'Coast', 'Yes', 125, 163, 70, 97, 'Kolumbien'),
	array('Bogota', 'Land', 'Yes', 195, 120, 110, 68, 'Kolumbien'),
	array('Panama', 'Coast', 'Yes', 80, 78, 43, 46, 'Neutral'),
	array('Panama (North Coast)', 'Coast', 'No', 82, 64, 63, 33, 'Neutral'),
	array('Panama (South Coast)', 'Coast', 'No', 94, 83, 51, 53, 'Neutral'),
	array('Medellin', 'Coast', 'No', 147, 128, 85, 65, 'Kolumbien'),
	array('Santa Marta', 'Coast', 'No', 182, 52, 107, 23, 'Kolumbien'),
	array('Popayan', 'Land', 'No', 199, 185, 116, 102, 'Kolumbien'),
	array('Llanos', 'Land', 'No', 233, 130, 140, 77, 'Kolumbien'),
	array('Concepcion', 'Land', 'Yes', 435, 530, 259, 313, 'Paraguay'),
	array('Formosa', 'Land', 'No', 375, 550, 238, 332, 'Paraguay'),
	array('Chaco', 'Land', 'No', 380, 500, 224, 294, 'Paraguay'),
	array('Asuncion', 'Coast', 'Yes', 454, 569, 271, 336, 'Paraguay'),
	array('Misiones', 'Coast', 'No', 455, 624, 277, 356, 'Paraguay'),
	array('Lima', 'Coast', 'Yes', 140, 348, 82, 206, 'Peru'),
	array('Trujillo', 'Coast', 'Yes', 113, 305, 67, 178, 'Peru'),
	array('Iquitos', 'Land', 'Yes', 165, 243, 98, 142, 'Neutral'),
	array('Arica', 'Coast', 'Yes', 222, 435, 134, 262, 'Neutral'),
	array('Arequipa', 'Coast', 'No', 178, 416, 115, 247, 'Peru'),
	array('Piura', 'Coast', 'No', 85, 270, 48, 165, 'Peru'),
	array('Cusco', 'Land', 'No', 208, 359, 123, 211, 'Peru'),
	array('Maracaibo', 'Coast', 'Yes', 224, 63, 134, 40, 'Venezuela'),
	array('Caracas', 'Coast', 'Yes', 279, 52, 165, 29, 'Venezuela'),
	array('Cumana', 'Coast', 'Yes', 342, 56, 202, 33, 'Neutral'),
	array('Ciudad Bolivar', 'Coast', 'Yes', 337, 105, 199, 62, 'Neutral'),
	array('Barinas', 'Land', 'No', 254, 85, 166, 54, 'Venezuela'),
	array('Orinoco', 'Land', 'No', 283, 138, 169, 81, 'Venezuela'),
	array('Veraguas', 'Coast', 'No', 30, 43, 17, 25, 'Neutral'),
	array('Veraguas (North Coast)', 'Coast', 'No', 58, 56, 27, 18, 'Neutral'),
	array('Veraguas (South Coast)', 'Coast', 'No', 19, 52, 12, 30, 'Neutral'),
	array('Quito', 'Coast', 'Yes', 98, 190, 58, 110, 'Neutral'),
	array('Canelos', 'Land', 'No', 138, 207, 79, 131, 'Neutral'),
	array('Guayaquil', 'Coast', 'No', 100, 232, 57, 144, 'Neutral'),
	array('Montevideo', 'Coast', 'Yes', 461, 665, 280, 404, 'Neutral'),
	array('Galapagosinseln', 'Coast', 'Yes', 4, 189, 3, 112, 'Neutral'),
	array('Juan-Fernandez-Inseln', 'Coast', 'Yes', 82, 755, 54, 437, 'Neutral'),
	array('Falklandinseln', 'Coast', 'Yes', 484, 940, 287, 552, 'Neutral'),
	array('Golf von Darien', 'Sea', 'No', 140, 30, 100, 13, 'Neutral'),
	array('Golf von Paria', 'Sea', 'No', 372, 49, 178, 15, 'Neutral'),
	array('Atlantischer Ozean', 'Sea', 'No', 625, 115, 363, 59, 'Neutral'),
	array('Boca de Navios', 'Sea', 'No', 522, 134, 309, 85, 'Neutral'),
	array('Sao Marcos Bucht', 'Sea', 'No', 602, 191, 365, 106, 'Neutral'),
	array('Allerheiligenbucht', 'Sea', 'No', 716, 463, 414, 296, 'Neutral'),
	array('Bucht von Sao Sebastiao', 'Sea', 'No', 600, 565, 358, 326, 'Neutral'),
	array('Bucht von Paranagua', 'Sea', 'No', 600, 660, 379, 378, 'Neutral'),
	array('Rio de la Plata', 'Sea', 'No', 510, 722, 294, 435, 'Neutral'),
	array('S&uumld-Atlantik', 'Sea', 'No', 596, 792, 376, 452, 'Neutral'),
	array('Golf von San Jorge', 'Sea', 'No', 448, 852, 264, 503, 'Neutral'),
	array('Scotiasee', 'Sea', 'No', 623, 931, 392, 559, 'Neutral'),
	array('Magellanstra&szlig;e', 'Sea', 'No', 324, 988, 190, 579, 'Neutral'),
	array('Drake-Passage', 'Sea', 'No', 138, 841, 115, 519, 'Neutral'),
	array('Golf von Guafo', 'Sea', 'No', 136, 645, 105, 380, 'Neutral'),
	array('S&uumld-Pazifik', 'Sea', 'No', 67, 506, 34, 304, 'Neutral'),
	array('Bucht von Arica', 'Sea', 'No', 153, 471, 82, 262, 'Neutral'),
	array('Nazca Meer', 'Sea', 'No', 47, 300, 27, 191, 'Neutral'),
	array('Bucht von Sechura', 'Sea', 'No', 62, 200, 35, 116, 'Neutral'),
	array('Golf von Panama', 'Sea', 'No', 96, 133, 51, 71, 'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		 $countryID=0;
	else
		 $countryID=$this->countryID($country);
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);		

$bordersRawData=array(
	array('Buenos Aires','Bahia Blanca','Yes','Yes'),
	array('Buenos Aires','Rosario','No','Yes'),
	array('Buenos Aires','Santa Fe','Yes','Yes'),
	array('Buenos Aires','Montevideo','Yes','Yes'),
	array('Buenos Aires','Rio de la Plata','Yes','No'),
	array('Salta','San Miguel de Tucuman','No','Yes'),
	array('Salta','Potosi','No','Yes'),
	array('Salta','Formosa','No','Yes'),
	array('Salta','Chaco','No','Yes'),
	array('Cordoba','San Miguel de Tucuman','No','Yes'),
	array('Cordoba','Rosario','No','Yes'),
	array('Cordoba','Mendoza','No','Yes'),
	array('Cordoba','Santa Fe','No','Yes'),
	array('Patagonien','Bahia Blanca','Yes','Yes'),
	array('Patagonien','Mendoza','No','Yes'),
	array('Patagonien','Punta Arenas','Yes','Yes'),
	array('Patagonien','Arauncanian Ureinwohner-Territorium','No','Yes'),
	array('Patagonien','Golf von San Jorge','Yes','No'),
	array('San Miguel de Tucuman','Salta','No','Yes'),
	array('San Miguel de Tucuman','Cordoba','No','Yes'),
	array('San Miguel de Tucuman','Corrientes','No','Yes'),
	array('San Miguel de Tucuman','Santa Fe','No','Yes'),
	array('San Miguel de Tucuman','Formosa','No','Yes'),
	array('Corrientes','San Miguel de Tucuman','No','Yes'),
	array('Corrientes','Santa Fe','Yes','Yes'),
	array('Corrientes','Formosa','No','Yes'),
	array('Corrientes','Asuncion','Yes','Yes'),
	array('Corrientes','Misiones','Yes','Yes'),
	array('Bahia Blanca','Buenos Aires','Yes','Yes'),
	array('Bahia Blanca','Patagonien','Yes','Yes'),
	array('Bahia Blanca','Rosario','No','Yes'),
	array('Bahia Blanca','Mendoza','No','Yes'),
	array('Bahia Blanca','Rio de la Plata','Yes','No'),
	array('Bahia Blanca','Golf von San Jorge','Yes','No'),
	array('Rosario','Buenos Aires','No','Yes'),
	array('Rosario','Cordoba','No','Yes'),
	array('Rosario','Bahia Blanca','No','Yes'),
	array('Rosario','Mendoza','No','Yes'),
	array('Rosario','Santa Fe','No','Yes'),
	array('Mendoza','Cordoba','No','Yes'),
	array('Mendoza','Patagonien','No','Yes'),
	array('Mendoza','Bahia Blanca','No','Yes'),
	array('Mendoza','Rosario','No','Yes'),
	array('Mendoza','Santiago de Chile','No','Yes'),
	array('Santa Fe','Buenos Aires','Yes','Yes'),
	array('Santa Fe','Cordoba','No','Yes'),
	array('Santa Fe','San Miguel de Tucuman','No','Yes'),
	array('Santa Fe','Corrientes','Yes','Yes'),
	array('Santa Fe','Rosario','No','Yes'),
	array('Santa Fe','Misiones','Yes','Yes'),
	array('Santa Fe','Montevideo','Yes','Yes'),
	array('Antofagasta','Potosi','No','Yes'),
	array('Antofagasta','Atacama','Yes','Yes'),
	array('Antofagasta','Copiapo','Yes','Yes'),
	array('Antofagasta','Golf von Guafo','Yes','No'),
	array('Antofagasta','Bucht von Arica','Yes','No'),
	array('La Paz','Santa Cruz','No','Yes'),
	array('La Paz','Potosi','No','Yes'),
	array('La Paz','Riberalta','No','Yes'),
	array('La Paz','Cusco','No','Yes'),
	array('Santa Cruz','La Paz','No','Yes'),
	array('Santa Cruz','Potosi','No','Yes'),
	array('Santa Cruz','Riberalta','No','Yes'),
	array('Santa Cruz','Mato Grosso','No','Yes'),
	array('Santa Cruz','Guapore','No','Yes'),
	array('Santa Cruz','Pantanal','No','Yes'),
	array('Santa Cruz','Chaco','No','Yes'),
	array('Potosi','Salta','No','Yes'),
	array('Potosi','Antofagasta','No','Yes'),
	array('Potosi','La Paz','No','Yes'),
	array('Potosi','Santa Cruz','No','Yes'),
	array('Potosi','Chaco','No','Yes'),
	array('Atacama','Antofagasta','Yes','Yes'),
	array('Atacama','Arica','Yes','Yes'),
	array('Atacama','Bucht von Arica','Yes','No'),
	array('Riberalta','La Paz','No','Yes'),
	array('Riberalta','Santa Cruz','No','Yes'),
	array('Riberalta','Aquiris Ureinwohner-Territorium','No','Yes'),
	array('Riberalta','Guapore','No','Yes'),
	array('Riberalta','Cusco','No','Yes'),
	array('Salvador','Rio de Janeiro','Yes','Yes'),
	array('Salvador','Pernambuco','Yes','Yes'),
	array('Salvador','Goias','No','Yes'),
	array('Salvador','Minas Gerais','No','Yes'),
	array('Salvador','Sao Marcos Bucht','Yes','No'),
	array('Salvador','Allerheiligenbucht','Yes','No'),
	array('Rio de Janeiro','Salvador','Yes','Yes'),
	array('Rio de Janeiro','Sao Paulo','Yes','Yes'),
	array('Rio de Janeiro','Minas Gerais','No','Yes'),
	array('Rio de Janeiro','Allerheiligenbucht','Yes','No'),
	array('Rio de Janeiro','Bucht von Sao Sebastiao','Yes','No'),
	array('Sao Paulo','Rio de Janeiro','Yes','Yes'),
	array('Sao Paulo','Rio Grande do Sul','Yes','Yes'),
	array('Sao Paulo','Parana','No','Yes'),
	array('Sao Paulo','Pantanal','No','Yes'),
	array('Sao Paulo','Goias','No','Yes'),
	array('Sao Paulo','Minas Gerais','No','Yes'),
	array('Sao Paulo','Bucht von Sao Sebastiao','Yes','No'),
	array('Manaus','Para','Yes','Yes'),
	array('Manaus','Mato Grosso','Yes','Yes'),
	array('Manaus','Amazonas','Yes','Yes'),
	array('Manaus','Rio Branco','No','Yes'),
	array('Maranhao','Para','Yes','Yes'),
	array('Maranhao','Pernambuco','Yes','Yes'),
	array('Maranhao','Mato Grosso','Yes','Yes'),
	array('Maranhao','Goias','No','Yes'),
	array('Maranhao','Boca de Navios','Yes','No'),
	array('Maranhao','Sao Marcos Bucht','Yes','No'),
	array('Rio Grande do Sul','Sao Paulo','Yes','Yes'),
	array('Rio Grande do Sul','Parana','No','Yes'),
	array('Rio Grande do Sul','Misiones','No','Yes'),
	array('Rio Grande do Sul','Montevideo','Yes','Yes'),
	array('Rio Grande do Sul','Bucht von Sao Sebastiao','Yes','No'),
	array('Rio Grande do Sul','Bucht von Paranagua','Yes','No'),
	array('Rio Grande do Sul','Rio de la Plata','Yes','No'),
	array('Parana','Sao Paulo','No','Yes'),
	array('Parana','Rio Grande do Sul','No','Yes'),
	array('Parana','Pantanal','Yes','Yes'),
	array('Parana','Asuncion','Yes','Yes'),
	array('Parana','Misiones','Yes','Yes'),
	array('Aquiris Ureinwohner-Territorium','Riberalta','No','Yes'),
	array('Aquiris Ureinwohner-Territorium','Amazonas','No','Yes'),
	array('Aquiris Ureinwohner-Territorium','Guapore','No','Yes'),
	array('Aquiris Ureinwohner-Territorium','Iquitos','No','Yes'),
	array('Aquiris Ureinwohner-Territorium','Cusco','No','Yes'),
	array('Para','Manaus','Yes','Yes'),
	array('Para','Maranhao','Yes','Yes'),
	array('Para','Mato Grosso','Yes','Yes'),
	array('Para','Rio Branco','No','Yes'),
	array('Para','Boca de Navios','Yes','No'),
	array('Pernambuco','Salvador','Yes','Yes'),
	array('Pernambuco','Maranhao','Yes','Yes'),
	array('Pernambuco','Goias','No','Yes'),
	array('Pernambuco','Sao Marcos Bucht','Yes','No'),
	array('Mato Grosso','Santa Cruz','No','Yes'),
	array('Mato Grosso','Manaus','Yes','Yes'),
	array('Mato Grosso','Maranhao','Yes','Yes'),
	array('Mato Grosso','Para','Yes','Yes'),
	array('Mato Grosso','Amazonas','Yes','Yes'),
	array('Mato Grosso','Guapore','Yes','Yes'),
	array('Mato Grosso','Pantanal','No','Yes'),
	array('Mato Grosso','Goias','No','Yes'),
	array('Amazonas','Manaus','Yes','Yes'),
	array('Amazonas','Aquiris Ureinwohner-Territorium','No','Yes'),
	array('Amazonas','Mato Grosso','Yes','Yes'),
	array('Amazonas','Guapore','Yes','Yes'),
	array('Amazonas','Rio Branco','No','Yes'),
	array('Amazonas','Popayan','No','Yes'),
	array('Amazonas','Llanos','No','Yes'),
	array('Amazonas','Iquitos','No','Yes'),
	array('Amazonas','Orinoco','No','Yes'),
	array('Guapore','Santa Cruz','No','Yes'),
	array('Guapore','Riberalta','No','Yes'),
	array('Guapore','Aquiris Ureinwohner-Territorium','No','Yes'),
	array('Guapore','Mato Grosso','Yes','Yes'),
	array('Guapore','Amazonas','Yes','Yes'),
	array('Pantanal','Santa Cruz','No','Yes'),
	array('Pantanal','Sao Paulo','No','Yes'),
	array('Pantanal','Parana','Yes','Yes'),
	array('Pantanal','Mato Grosso','No','Yes'),
	array('Pantanal','Goias','No','Yes'),
	array('Pantanal','Concepcion','No','Yes'),
	array('Pantanal','Chaco','No','Yes'),
	array('Pantanal','Asuncion','Yes','Yes'),
	array('Rio Branco','Manaus','No','Yes'),
	array('Rio Branco','Para','No','Yes'),
	array('Rio Branco','Amazonas','No','Yes'),
	array('Rio Branco','Ciudad Bolivar','No','Yes'),
	array('Rio Branco','Orinoco','No','Yes'),
	array('Goias','Salvador','No','Yes'),
	array('Goias','Sao Paulo','No','Yes'),
	array('Goias','Maranhao','No','Yes'),
	array('Goias','Pernambuco','No','Yes'),
	array('Goias','Mato Grosso','No','Yes'),
	array('Goias','Pantanal','No','Yes'),
	array('Goias','Minas Gerais','No','Yes'),
	array('Minas Gerais','Salvador','No','Yes'),
	array('Minas Gerais','Rio de Janeiro','No','Yes'),
	array('Minas Gerais','Sao Paulo','No','Yes'),
	array('Minas Gerais','Goias','No','Yes'),
	array('Santiago de Chile','Mendoza','No','Yes'),
	array('Santiago de Chile','Valparaiso','Yes','Yes'),
	array('Santiago de Chile','Arauncanian Ureinwohner-Territorium','Yes','Yes'),
	array('Santiago de Chile','Drake-Passage','Yes','No'),
	array('Valparaiso','Santiago de Chile','Yes','Yes'),
	array('Valparaiso','Copiapo','Yes','Yes'),
	array('Valparaiso','Drake-Passage','Yes','No'),
	array('Valparaiso','Golf von Guafo','Yes','No'),
	array('Punta Arenas','Patagonien','Yes','Yes'),
	array('Punta Arenas','Arauncanian Ureinwohner-Territorium','Yes','Yes'),
	array('Punta Arenas','Golf von San Jorge','Yes','No'),
	array('Punta Arenas','Magellanstra&szlig;e','Yes','No'),
	array('Punta Arenas','Drake-Passage','Yes','No'),
	array('Copiapo','Antofagasta','Yes','Yes'),
	array('Copiapo','Valparaiso','Yes','Yes'),
	array('Copiapo','Golf von Guafo','Yes','No'),
	array('Arauncanian Ureinwohner-Territorium','Patagonien','No','Yes'),
	array('Arauncanian Ureinwohner-Territorium','Santiago de Chile','Yes','Yes'),
	array('Arauncanian Ureinwohner-Territorium','Punta Arenas','Yes','Yes'),
	array('Arauncanian Ureinwohner-Territorium','Drake-Passage','Yes','No'),
	array('Cartagena','Bogota','No','Yes'),
	array('Cartagena','Panama','No','Yes'),
	array('Cartagena','Panama (North Coast)','Yes','No'),
	array('Cartagena','Medellin','No','Yes'),
	array('Cartagena','Santa Marta','Yes','Yes'),
	array('Cartagena','Golf von Darien','Yes','No'),
	array('Cali','Bogota','No','Yes'),
	array('Cali','Medellin','Yes','Yes'),
	array('Cali','Quito','Yes','Yes'),
	array('Cali','Canelos','No','Yes'),
	array('Cali','Bucht von Sechura','Yes','No'),
	array('Cali','Golf von Panama','Yes','No'),
	array('Bogota','Cartagena','No','Yes'),
	array('Bogota','Cali','No','Yes'),
	array('Bogota','Medellin','No','Yes'),
	array('Bogota','Santa Marta','No','Yes'),
	array('Bogota','Popayan','No','Yes'),
	array('Bogota','Llanos','No','Yes'),
	array('Panama','Cartagena','No','Yes'),
	array('Panama','Medellin','No','Yes'),
	array('Panama','Veraguas','No','Yes'),
	array('Panama (North Coast)','Cartagena','Yes','No'),
	array('Panama (North Coast)','Veraguas (North Coast)','Yes','No'),
	array('Panama (North Coast)','Golf von Darien','Yes','No'),
	array('Panama (South Coast)','Medellin','Yes','No'),
	array('Panama (South Coast)','Veraguas (South Coast)','Yes','No'),
	array('Panama (South Coast)','Golf von Panama','Yes','No'),
	array('Medellin','Cartagena','No','Yes'),
	array('Medellin','Cali','Yes','Yes'),
	array('Medellin','Bogota','No','Yes'),
	array('Medellin','Panama','No','Yes'),
	array('Medellin','Panama (South Coast)','Yes','No'),
	array('Medellin','Golf von Panama','Yes','No'),
	array('Santa Marta','Cartagena','Yes','Yes'),
	array('Santa Marta','Bogota','No','Yes'),
	array('Santa Marta','Llanos','No','Yes'),
	array('Santa Marta','Maracaibo','Yes','Yes'),
	array('Santa Marta','Golf von Darien','Yes','No'),
	array('Popayan','Amazonas','No','Yes'),
	array('Popayan','Bogota','No','Yes'),
	array('Popayan','Llanos','No','Yes'),
	array('Popayan','Iquitos','No','Yes'),
	array('Popayan','Canelos','No','Yes'),
	array('Llanos','Amazonas','No','Yes'),
	array('Llanos','Bogota','No','Yes'),
	array('Llanos','Santa Marta','No','Yes'),
	array('Llanos','Popayan','No','Yes'),
	array('Llanos','Maracaibo','No','Yes'),
	array('Llanos','Barinas','No','Yes'),
	array('Llanos','Orinoco','No','Yes'),
	array('Concepcion','Pantanal','No','Yes'),
	array('Concepcion','Formosa','No','Yes'),
	array('Concepcion','Chaco','No','Yes'),
	array('Concepcion','Asuncion','No','Yes'),
	array('Formosa','Salta','No','Yes'),
	array('Formosa','San Miguel de Tucuman','No','Yes'),
	array('Formosa','Corrientes','No','Yes'),
	array('Formosa','Concepcion','No','Yes'),
	array('Formosa','Chaco','No','Yes'),
	array('Formosa','Asuncion','No','Yes'),
	array('Chaco','Salta','No','Yes'),
	array('Chaco','Santa Cruz','No','Yes'),
	array('Chaco','Potosi','No','Yes'),
	array('Chaco','Pantanal','No','Yes'),
	array('Chaco','Concepcion','No','Yes'),
	array('Chaco','Formosa','No','Yes'),
	array('Asuncion','Corrientes','Yes','Yes'),
	array('Asuncion','Parana','Yes','Yes'),
	array('Asuncion','Pantanal','Yes','Yes'),
	array('Asuncion','Concepcion','No','Yes'),
	array('Asuncion','Formosa','No','Yes'),
	array('Asuncion','Misiones','Yes','Yes'),
	array('Misiones','Corrientes','Yes','Yes'),
	array('Misiones','Santa Fe','Yes','Yes'),
	array('Misiones','Rio Grande do Sul','No','Yes'),
	array('Misiones','Parana','Yes','Yes'),
	array('Misiones','Asuncion','Yes','Yes'),
	array('Misiones','Montevideo','Yes','Yes'),
	array('Lima','Trujillo','Yes','Yes'),
	array('Lima','Arequipa','Yes','Yes'),
	array('Lima','Cusco','No','Yes'),
	array('Lima','Bucht von Arica','Yes','No'),
	array('Lima','Nazca Meer','Yes','No'),
	array('Trujillo','Lima','Yes','Yes'),
	array('Trujillo','Iquitos','No','Yes'),
	array('Trujillo','Piura','Yes','Yes'),
	array('Trujillo','Nazca Meer','Yes','No'),
	array('Iquitos','Aquiris Ureinwohner-Territorium','No','Yes'),
	array('Iquitos','Amazonas','No','Yes'),
	array('Iquitos','Popayan','No','Yes'),
	array('Iquitos','Trujillo','No','Yes'),
	array('Iquitos','Cusco','No','Yes'),
	array('Iquitos','Canelos','No','Yes'),
	array('Arica','Atacama','Yes','Yes'),
	array('Arica','Arequipa','Yes','Yes'),
	array('Arica','Bucht von Arica','Yes','No'),
	array('Arequipa','Lima','Yes','Yes'),
	array('Arequipa','Arica','Yes','Yes'),
	array('Arequipa','Bucht von Arica','Yes','No'),
	array('Piura','Trujillo','Yes','Yes'),
	array('Piura','Guayaquil','Yes','Yes'),
	array('Piura','Nazca Meer','Yes','No'),
	array('Piura','Bucht von Sechura','Yes','No'),
	array('Cusco','La Paz','No','Yes'),
	array('Cusco','Riberalta','No','Yes'),
	array('Cusco','Aquiris Ureinwohner-Territorium','No','Yes'),
	array('Cusco','Lima','No','Yes'),
	array('Cusco','Iquitos','No','Yes'),
	array('Maracaibo','Santa Marta','Yes','Yes'),
	array('Maracaibo','Llanos','No','Yes'),
	array('Maracaibo','Caracas','Yes','Yes'),
	array('Maracaibo','Barinas','No','Yes'),
	array('Maracaibo','Golf von Darien','Yes','No'),
	array('Caracas','Maracaibo','Yes','Yes'),
	array('Caracas','Cumana','Yes','Yes'),
	array('Caracas','Ciudad Bolivar','No','Yes'),
	array('Caracas','Barinas','No','Yes'),
	array('Caracas','Golf von Darien','Yes','No'),
	array('Caracas','Golf von Paria','Yes','No'),
	array('Cumana','Caracas','Yes','Yes'),
	array('Cumana','Ciudad Bolivar','Yes','Yes'),
	array('Cumana','Golf von Paria','Yes','No'),
	array('Ciudad Bolivar','Rio Branco','No','Yes'),
	array('Ciudad Bolivar','Caracas','No','Yes'),
	array('Ciudad Bolivar','Cumana','Yes','Yes'),
	array('Ciudad Bolivar','Barinas','No','Yes'),
	array('Ciudad Bolivar','Orinoco','No','Yes'),
	array('Ciudad Bolivar','Golf von Paria','Yes','No'),
	array('Ciudad Bolivar','Boca de Navios','Yes','No'),
	array('Barinas','Llanos','No','Yes'),
	array('Barinas','Maracaibo','No','Yes'),
	array('Barinas','Caracas','No','Yes'),
	array('Barinas','Ciudad Bolivar','No','Yes'),
	array('Barinas','Orinoco','No','Yes'),
	array('Orinoco','Amazonas','No','Yes'),
	array('Orinoco','Rio Branco','No','Yes'),
	array('Orinoco','Llanos','No','Yes'),
	array('Orinoco','Ciudad Bolivar','No','Yes'),
	array('Orinoco','Barinas','No','Yes'),
	array('Veraguas','Panama','No','Yes'),
	array('Veraguas (North Coast)','Panama (North Coast)','Yes','No'),
	array('Veraguas (North Coast)','Golf von Darien','Yes','No'),
	array('Veraguas (South Coast)','Panama (South Coast)','Yes','No'),
	array('Veraguas (South Coast)','Golf von Panama','Yes','No'),
	array('Quito','Cali','Yes','Yes'),
	array('Quito','Guayaquil','Yes','Yes'),
	array('Quito','Bucht von Sechura','Yes','No'),
	array('Canelos','Cali','No','Yes'),
	array('Canelos','Popayan','No','Yes'),
	array('Canelos','Iquitos','No','Yes'),
	array('Canelos','Guayaquil','No','Yes'),
	array('Guayaquil','Piura','Yes','Yes'),
	array('Guayaquil','Quito','Yes','Yes'),
	array('Guayaquil','Canelos','No','Yes'),
	array('Guayaquil','Bucht von Sechura','Yes','No'),
	array('Montevideo','Buenos Aires','Yes','Yes'),
	array('Montevideo','Santa Fe','Yes','Yes'),
	array('Montevideo','Rio Grande do Sul','Yes','Yes'),
	array('Montevideo','Misiones','Yes','Yes'),
	array('Montevideo','Rio de la Plata','Yes','No'),
	array('Galapagosinseln','Nazca Meer','Yes','No'),
	array('Galapagosinseln','Bucht von Sechura','Yes','No'),
	array('Galapagosinseln','Golf von Panama','Yes','No'),
	array('Juan-Fernandez-Inseln','Drake-Passage','Yes','No'),
	array('Juan-Fernandez-Inseln','Golf von Guafo','Yes','No'),
	array('Falklandinseln','Golf von San Jorge','Yes','No'),
	array('Falklandinseln','Scotiasee','Yes','No'),
	array('Golf von Darien','Cartagena','Yes','No'),
	array('Golf von Darien','Panama (North Coast)','Yes','No'),
	array('Golf von Darien','Santa Marta','Yes','No'),
	array('Golf von Darien','Maracaibo','Yes','No'),
	array('Golf von Darien','Caracas','Yes','No'),
	array('Golf von Darien','Veraguas (North Coast)','Yes','No'),
	array('Golf von Darien','Golf von Paria','Yes','No'),
	array('Golf von Paria','Caracas','Yes','No'),
	array('Golf von Paria','Cumana','Yes','No'),
	array('Golf von Paria','Ciudad Bolivar','Yes','No'),
	array('Golf von Paria','Golf von Darien','Yes','No'),
	array('Golf von Paria','Atlantischer Ozean','Yes','No'),
	array('Golf von Paria','Boca de Navios','Yes','No'),
	array('Atlantischer Ozean','Golf von Paria','Yes','No'),
	array('Atlantischer Ozean','Boca de Navios','Yes','No'),
	array('Atlantischer Ozean','Sao Marcos Bucht','Yes','No'),
	array('Boca de Navios','Maranhao','Yes','No'),
	array('Boca de Navios','Para','Yes','No'),
	array('Boca de Navios','Ciudad Bolivar','Yes','No'),
	array('Boca de Navios','Golf von Paria','Yes','No'),
	array('Boca de Navios','Atlantischer Ozean','Yes','No'),
	array('Boca de Navios','Sao Marcos Bucht','Yes','No'),
	array('Sao Marcos Bucht','Salvador','Yes','No'),
	array('Sao Marcos Bucht','Maranhao','Yes','No'),
	array('Sao Marcos Bucht','Pernambuco','Yes','No'),
	array('Sao Marcos Bucht','Atlantischer Ozean','Yes','No'),
	array('Sao Marcos Bucht','Boca de Navios','Yes','No'),
	array('Sao Marcos Bucht','Allerheiligenbucht','Yes','No'),
	array('Allerheiligenbucht','Salvador','Yes','No'),
	array('Allerheiligenbucht','Rio de Janeiro','Yes','No'),
	array('Allerheiligenbucht','Sao Marcos Bucht','Yes','No'),
	array('Allerheiligenbucht','Bucht von Sao Sebastiao','Yes','No'),
	array('Allerheiligenbucht','Bucht von Paranagua','Yes','No'),
	array('Bucht von Sao Sebastiao','Rio de Janeiro','Yes','No'),
	array('Bucht von Sao Sebastiao','Sao Paulo','Yes','No'),
	array('Bucht von Sao Sebastiao','Rio Grande do Sul','Yes','No'),
	array('Bucht von Sao Sebastiao','Allerheiligenbucht','Yes','No'),
	array('Bucht von Sao Sebastiao','Bucht von Paranagua','Yes','No'),
	array('Bucht von Paranagua','Rio Grande do Sul','Yes','No'),
	array('Bucht von Paranagua','Allerheiligenbucht','Yes','No'),
	array('Bucht von Paranagua','Bucht von Sao Sebastiao','Yes','No'),
	array('Bucht von Paranagua','Rio de la Plata','Yes','No'),
	array('Bucht von Paranagua','S&uumld-Atlantik','Yes','No'),
	array('Rio de la Plata','Buenos Aires','Yes','No'),
	array('Rio de la Plata','Bahia Blanca','Yes','No'),
	array('Rio de la Plata','Rio Grande do Sul','Yes','No'),
	array('Rio de la Plata','Montevideo','Yes','No'),
	array('Rio de la Plata','Bucht von Paranagua','Yes','No'),
	array('Rio de la Plata','S&uumld-Atlantik','Yes','No'),
	array('Rio de la Plata','Golf von San Jorge','Yes','No'),
	array('S&uumld-Atlantik','Bucht von Paranagua','Yes','No'),
	array('S&uumld-Atlantik','Rio de la Plata','Yes','No'),
	array('S&uumld-Atlantik','Golf von San Jorge','Yes','No'),
	array('S&uumld-Atlantik','Scotiasee','Yes','No'),
	array('Golf von San Jorge','Patagonien','Yes','No'),
	array('Golf von San Jorge','Bahia Blanca','Yes','No'),
	array('Golf von San Jorge','Punta Arenas','Yes','No'),
	array('Golf von San Jorge','Falklandinseln','Yes','No'),
	array('Golf von San Jorge','Rio de la Plata','Yes','No'),
	array('Golf von San Jorge','S&uumld-Atlantik','Yes','No'),
	array('Golf von San Jorge','Scotiasee','Yes','No'),
	array('Golf von San Jorge','Magellanstra&szlig;e','Yes','No'),
	array('Scotiasee','Falklandinseln','Yes','No'),
	array('Scotiasee','S&uumld-Atlantik','Yes','No'),
	array('Scotiasee','Golf von San Jorge','Yes','No'),
	array('Scotiasee','Magellanstra&szlig;e','Yes','No'),
	array('Magellanstra&szlig;e','Punta Arenas','Yes','No'),
	array('Magellanstra&szlig;e','Golf von San Jorge','Yes','No'),
	array('Magellanstra&szlig;e','Scotiasee','Yes','No'),
	array('Magellanstra&szlig;e','Drake-Passage','Yes','No'),
	array('Drake-Passage','Santiago de Chile','Yes','No'),
	array('Drake-Passage','Valparaiso','Yes','No'),
	array('Drake-Passage','Punta Arenas','Yes','No'),
	array('Drake-Passage','Arauncanian Ureinwohner-Territorium','Yes','No'),
	array('Drake-Passage','Juan-Fernandez-Inseln','Yes','No'),
	array('Drake-Passage','Magellanstra&szlig;e','Yes','No'),
	array('Drake-Passage','Golf von Guafo','Yes','No'),
	array('Golf von Guafo','Antofagasta','Yes','No'),
	array('Golf von Guafo','Valparaiso','Yes','No'),
	array('Golf von Guafo','Copiapo','Yes','No'),
	array('Golf von Guafo','Juan-Fernandez-Inseln','Yes','No'),
	array('Golf von Guafo','Drake-Passage','Yes','No'),
	array('Golf von Guafo','S&uumld-Pazifik','Yes','No'),
	array('Golf von Guafo','Bucht von Arica','Yes','No'),
	array('S&uumld-Pazifik','Golf von Guafo','Yes','No'),
	array('S&uumld-Pazifik','Bucht von Arica','Yes','No'),
	array('S&uumld-Pazifik','Nazca Meer','Yes','No'),
	array('Bucht von Arica','Antofagasta','Yes','No'),
	array('Bucht von Arica','Atacama','Yes','No'),
	array('Bucht von Arica','Lima','Yes','No'),
	array('Bucht von Arica','Arica','Yes','No'),
	array('Bucht von Arica','Arequipa','Yes','No'),
	array('Bucht von Arica','Golf von Guafo','Yes','No'),
	array('Bucht von Arica','S&uumld-Pazifik','Yes','No'),
	array('Bucht von Arica','Nazca Meer','Yes','No'),
	array('Nazca Meer','Lima','Yes','No'),
	array('Nazca Meer','Trujillo','Yes','No'),
	array('Nazca Meer','Piura','Yes','No'),
	array('Nazca Meer','Galapagosinseln','Yes','No'),
	array('Nazca Meer','S&uumld-Pazifik','Yes','No'),
	array('Nazca Meer','Bucht von Arica','Yes','No'),
	array('Nazca Meer','Bucht von Sechura','Yes','No'),
	array('Bucht von Sechura','Cali','Yes','No'),
	array('Bucht von Sechura','Piura','Yes','No'),
	array('Bucht von Sechura','Quito','Yes','No'),
	array('Bucht von Sechura','Guayaquil','Yes','No'),
	array('Bucht von Sechura','Galapagosinseln','Yes','No'),
	array('Bucht von Sechura','Nazca Meer','Yes','No'),
	array('Bucht von Sechura','Golf von Panama','Yes','No'),
	array('Golf von Panama','Cali','Yes','No'),
	array('Golf von Panama','Panama (South Coast)','Yes','No'),
	array('Golf von Panama','Medellin','Yes','No'),
	array('Golf von Panama','Veraguas (South Coast)','Yes','No'),
	array('Golf von Panama','Galapagosinseln','Yes','No'),
	array('Golf von Panama','Bucht von Sechura','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	 list($from, $to, $fleets, $armies)=$borderRawRow;
	 InstallTerritory::$Territories[$from]->addBorder(InstallTerritory::$Territories[$to]  ,$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
